In [1]:
import caf.tem as ct
from pathlib import Path
import caf.base as cb
#import caf.base as cb
#import caf.toolkit as ctk
#from caf.tem.attraction_models import TP_generate_attraction
#from pathlib import Path
#from caf.tem.attraction_models import AttractionModel_TP

In [2]:
tem = ct.TEMModel( # add tem segmentations here? # pure segmentation as well? - pure follows input of mts applied (i.e. traveller types?) - hard coded in utils read pop
    model_years=[2023],
    scenario=ct.Scenarios("Core"),
    output_zoning="normits",
    iteration_name="TP_test_new_pure_seg",
    export_home=r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export"
    #add tem seg - from notem in nts processing. / pure seg opts. [hh_type, purpose, mode, period] - tem default. pure
)

In [3]:
dvec_fldr = Path(r"C:\Users\Spiral\Documents\Thomas Prince\(normitsefs) Transfer\TP_20250128-copy\tem_inputs")

HBProd = tem.HBProductionModel(
    population_paths={2023: dvec_fldr / "pop_2023.dvec"},
    trip_rates_path=dvec_fldr / "hb_trip_rates_production_dvector.dvec",
    mode_time_splits_path=dvec_fldr / "hb_mode_time_split_production_hb_fr.dvec") # Should this be hb_fr?

In [4]:
#HBProd.run()

In [5]:
HBAttr = tem.HBAttractionModel(trip_rates_paths={
        1: r"T:\ThomasPrince\hb_attraction_triprates_p1.dvec",
        2: r"T:\ThomasPrince\hb_attraction_triprates_p2.dvec",
        3: r"T:\ThomasPrince\hb_attraction_triprates_p3.dvec",
        4: r"T:\ThomasPrince\hb_attraction_triprates_p4.dvec",
        5: r"T:\ThomasPrince\hb_attraction_triprates_p5.dvec",
        6: r"T:\ThomasPrince\hb_attraction_triprates_p6.dvec",
        8: r"T:\ThomasPrince\hb_attraction_triprates_p8.dvec"
    },
    balance_production=False,
    emp_landuse_paths = {2023: r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Inputs\Land Use\employment\normits\Output E6.hdf"},
    hh_landuse_dirs = {2023: r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Inputs\Land Use\population\normits"},
    hh_landuse_prefix = "Output P14.1",
    hb_mts_path=r"C:\Users\Spiral\Documents\Thomas Prince\NTS Processing DVec\outputs_is\attractions\hb\mode_time_splits\hb_mode_time_split_attraction_hb_fr.dvec")

In [6]:
HBAttr.run()

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:819: SegmentationWarning: There are subsets in other's segmentation not in self. This will lead to rows present in self being cut in the product. Missing values are {'sic_2_digit': [2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 43, 45, 46, 47, 49, 50, 51, 52, 53, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 84, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1, -1]}
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit'] to ['soc', 'sic_4_digit', 'sic_2_digit', 'sic_1_digit']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:819: SegmentationWarning: There are subsets in other's segmentation not in self. This will lead to rows present in self being cut in the product. Missing values are {'sic_2_digit': [2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 43, 45, 49, 50, 51, 52, 53, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1, -1]}
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit'] to ['soc', 'sic_4_digit', 'sic_2_digit', 'sic_1_digit']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:819: SegmentationWarning: There are subsets in other's segmentation not in self. This will lead to rows present in self being cut in the product. Missing values are {'sic_2_digit': [2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 43, 45, 46, 47, 49, 50, 51, 52, 53, 55, 58, 59, 60, 61, 62, 63, 70, 71, 72, 73, 74, 78, 81, 82, 84, 85, 87, 88, 90, 91, 92, 93, 94, 97, 98, 99, 1, -1]}
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit'] to ['soc', 'sic_4_digit', 'sic_2_digit', 'sic_1_digit']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:819: SegmentationWarning: There are subsets in other's segmentation not in self. This will lead to rows present in self being cut in the product. Missing values are {'sic_2_digit': [2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 43, 45, 46, 47, 49, 50, 51, 52, 53, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 95, 96, 97, 98, 99, 1, -1]}
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit'] to ['soc', 'sic_4_digit', 'sic_2_digit', 'sic_1_digit']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:819: SegmentationWarning: There are subsets in other's segmentation not in self. This will lead to rows present in self being cut in the product. Missing values are {'sic_2_digit': [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 41, 42, 43, 45, 46, 47, 49, 50, 51, 52, 53, 56, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1, -1]}
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit'] to ['soc', 'sic_4_digit', 'sic_2_digit', 'sic_1_digit']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level m is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level tp is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['soc', 'p'] to ['soc', 'tp', 'p', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['soc', 'p'] to ['soc', 'tp', 'p', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['total', 'p'] to ['total', 'tp', 'p', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['total', 'p'] to ['total', 'tp', 'p', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['total', 'p'] to ['total', 'tp', 'p', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['total', 'p'] to ['total', 'tp', 'p', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['total', 'p'] to ['total', 'tp', 'p', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:541: TranslationWarning: 3 gor zones missing from zone_translation normits to gor
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1136: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other_grouped_data.rename(columns=translation_dict)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1141: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other.data.rename(columns=translation_dict).groupby(level=0, axis=1).sum()
c:\Users\Spiral\miniforge3\envs\caf.tem_dev\lib\site-packages\caf\toolkit\translation.py:906: UserWarning: Some values seem to have been dropped. The difference total is 21676.00000000021 (translated - original).
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['soc', 'tp', 'p', 'm'] to ['tp', 'ns_sec', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:541: TranslationWarning: 3 gor zones missing from zone_translation normits to gor
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1136: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other_grouped_data.rename(columns=translation_dict)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1141: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other.data.rename(columns=translation_dict).groupby(level=0, axis=1).sum()
c:\Users\Spiral\miniforge3\envs\caf.tem_dev\lib\site-packages\caf\toolkit\translation.py:906: UserWarning: Some values seem to have been dropped. The difference total is 21676.000000000153 (translated - original).
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['soc', 'tp', 'p', 'm'] to ['tp', 'ns_sec', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:541: TranslationWarning: 3 gor zones missing from zone_translation normits to gor
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1136: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other_grouped_data.rename(columns=translation_dict)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1141: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other.data.rename(columns=translation_dict).groupby(level=0, axis=1).sum()
c:\Users\Spiral\miniforge3\envs\caf.tem_dev\lib\site-packages\caf\toolkit\translation.py:906: UserWarning: Some values seem to have been dropped. The difference total is 5419.000000000035 (translated - original).
  warnings.warn(

TypeError: cannot concatenate object of type '<class 'caf.base.data_structures.DVector'>'; only Series and DataFrame objs are valid

In [ ]:
NHBAttr = tem.NHBAttractionModel(trip_rates_paths={
        1: r"T:\ThomasPrince\nhb_attraction_triprates_p1.dvec",
        2: r"T:\ThomasPrince\nhb_attraction_triprates_p2.dvec",
        3: r"T:\ThomasPrince\nhb_attraction_triprates_p3.dvec",
        4: r"T:\ThomasPrince\nhb_attraction_triprates_p4.dvec",
        5: r"T:\ThomasPrince\nhb_attraction_triprates_p5.dvec",
        6: r"T:\ThomasPrince\nhb_attraction_triprates_p6.dvec",
        8: r"T:\ThomasPrince\nhb_attraction_triprates_p8.dvec"
    },
    balance_production=False,
    emp_landuse_paths = {2023: r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Inputs\Land Use\employment\normits\Output E6.hdf"},
    hh_landuse_dirs = {2023: r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Inputs\Land Use\population\normits"},
    hh_landuse_prefix = "Output P14.1",
    nhb_mts_path=r"C:\Users\Spiral\Documents\Thomas Prince\NTS Processing DVec\outputs_is\attractions\hb\mode_time_splits\nhb_mode_time_split_attraction_nhb_fr.dvec")

In [16]:
HBAttr.production_paths[2023]

WindowsPath('C:/Users/Spiral/Documents/Thomas Prince/Common Analytical Framework/NoTEM/Export/TP_test_attr/Core/hb_productions/hb_normits_tem_segmented_2023_dvec.h5')

In [11]:
seg1 = cb.DVector.load(Path(HBAttr.model.export_home) / "seg_demand1.hdf")
seg2 = cb.DVector.load(Path(HBAttr.model.export_home) / "seg_demand2.hdf")
seg3 = cb.DVector.load(Path(HBAttr.model.export_home) / "seg_demand3.hdf")
seg4 = cb.DVector.load(Path(HBAttr.model.export_home) / "seg_demand4.hdf")
seg5 = cb.DVector.load(Path(HBAttr.model.export_home) / "seg_demand5.hdf")
seg6 = cb.DVector.load(Path(HBAttr.model.export_home) / "seg_demand6.hdf")
seg8 = cb.DVector.load(Path(HBAttr.model.export_home) / "mts_demand8.hdf")
pd = cb.DVector.load(HBAttr.production_paths[2023])

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [ ]:
for dvec in [seg1,  seg2, seg3,  seg4,  seg5, seg6, seg8]:
    print(dvec.segmentation.names)

In [13]:
pp = cb.DVector.load(HBAttr.production_model.export_paths.tem_segmented[2023])

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [20]:
bal1 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test_new_pure_seg\Core\hb_attractions\bal_demand1.hdf")
bal2 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test_new_pure_seg\Core\hb_attractions\bal_demand2.hdf")
bal3 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test_new_pure_seg\Core\hb_attractions\bal_demand3.hdf")
bal4 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test_new_pure_seg\Core\hb_attractions\bal_demand4.hdf")
bal5 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test_new_pure_seg\Core\hb_attractions\bal_demand5.hdf")
bal6 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test_new_pure_seg\Core\hb_attractions\bal_demand6.hdf")
bal8 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test_new_pure_seg\Core\hb_attractions\bal_demand8.hdf")

In [ ]:
bal1.concat(bal2).concat(bal3.aggregate(bal3.segmentation.names.remove("total")))

ValueError: Length of names must match number of levels in MultiIndex.

In [21]:
print(bal1.segmentation.names)
print(bal2.segmentation.names)
print(bal3.segmentation.names)
print(bal4.segmentation.names)
print(bal5.segmentation.names)
print(bal6.segmentation.names)
print(bal8.segmentation.names)

['tp', 'ns_sec', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']
['tp', 'ns_sec', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']
['tp', 'ns_sec', 'total', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']
['tp', 'ns_sec', 'total', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']
['tp', 'ns_sec', 'total', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']
['tp', 'ns_sec', 'total', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']
['tp', 'ns_sec', 'total', 'gender_3', 'adult_nssec', 'hh_type', 'm', 'soc', 'p', 'aws']

In [19]:
bal3.translate_zoning(bal3.zoning_system, check_totals=False, no_factors=True)# .data#.segmentation.names #+ bal4

In [16]:
bal4.segmentation.remove_segment().segmentation.names

['tp',
 'ns_sec',
 'total',
 'gender_3',
 'adult_nssec',
 'hh_type',
 'm',
 'soc',
 'p',
 'aws']

In [12]:
bal3.translate_zoning(cb.ZoningSystem.get_zoning("gor")).aggregate(["p", "m", "tp"]).data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:541: TranslationWarning: 3 gor zones missing from zone_translation normits to gor
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 3 zone IDs from zoning system gor aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 3 zone IDs from zoning system gor aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(

normits_id            1             2             3             4   \
p m tp
3 1 1       3.218920e+06  8.224936e+06  6.946142e+06  5.549553e+06
    2       3.113758e+06  7.846449e+06  7.569146e+06  5.549561e+06
    3       3.368997e+06  6.771900e+06  6.035328e+06  5.293679e+06
    4       4.585577e+06  5.427984e+06  8.104195e+06  5.220253e+06
    5       8.707546e+06  5.264695e+06  5.933353e+06  1.313025e+06
    6       2.071681e+06  7.654022e+06  5.874050e+06  2.845058e+06
  2 1       3.052703e+06  6.405240e+06  3.742735e+06  4.709396e+06
    2       6.451491e+06  5.564088e+06  3.929677e+06  3.170685e+06
    3       2.176796e+06  1.645552e+06  4.135849e+06  1.105082e+06
    4       3.368941e+07  0.000000e+00  0.000000e+00  0.000000e+00
    5       1.166884e+07  5.105085e+06  3.644131e+06  2.170374e+06
    6       1.293463e+07  6.643626e+06  6.580032e+05  4.109983e+06
  3 1       2.537322e+06  8.790489e+06  6.070664e+06  5.141551e+06
    2       2.724795e+06  8.366712e+06  6.187793e+06  5.407880e+06
    3       2.020780e+06  8.481088e+06  5.432862e+06  4.880969e+06
    4       2.151836e+06  8.434511e+06  5.736845e+06  4.645913e+06
    5       1.353615e+06  7.247203e+06  4.996621e+06  4.800305e+06
    6       2.348364e+06  8.574055e+06  5.665423e+06  4.968401e+06
  4 1       2.791610e+06  1.065401e+07  7.537102e+06  8.569391e+06
    2       2.361932e+06  1.075875e+07  7.591448e+06  8.392548e+06
    3       3.555815e+05  9.644810e+06  2.423616e+06  1.076967e+07
    4       3.360895e+06  1.251884e+07  1.057734e+07  8.797595e+06
    5       3.014720e+06  5.829360e+06  8.967600e+06  3.748342e+06
    6       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
  5 1       2.838320e+06  8.589978e+06  6.054573e+06  4.585487e+06
    2       3.514286e+06  1.196317e+07  5.607728e+06  2.968555e+06
    3       1.751404e+06  1.156255e+07  8.799675e+06  4.051145e+06
    4       4.719008e+06  1.079695e+07  3.790598e+06  2.639229e+06
    5       1.127044e+06  7.281394e+06  4.305168e+06  2.697998e+06
    6       1.509680e+06  9.335233e+06  3.432432e+06  3.195043e+06
  6 1       5.764580e+05  6.635140e+06  3.533253e+06  1.497269e+06
    2       5.884783e+05  6.253212e+06  4.366449e+06  1.560585e+06
    3       2.135908e+05  3.306622e+05  5.895401e+06  1.837006e+06
    4       3.827328e+05  3.377506e+06  4.432824e+06  3.027752e+06
    5       2.820342e+06  7.395498e+06  6.117905e+06  1.164787e+06
    6       3.559244e+05  8.105847e+06  3.717637e+06  1.541100e+06
  7 1       6.714943e+06  5.208381e+06  1.439675e+06  1.231386e+06
    2       4.315164e+06  3.498833e+06  1.746840e+06  1.484471e+06
    3       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
    4       1.194278e+07  0.000000e+00  0.000000e+00  0.000000e+00
    5       7.024330e+06  2.886664e+06  1.557031e+06  1.326682e+06
    6       1.314821e+07  6.686738e+06  0.000000e+00  3.577704e+04

normits_id            5             6             7             8   \
p m tp
3 1 1       6.223860e+06  6.437483e+06  1.071776e+07  9.754854e+06
    2       6.603179e+06  6.386595e+06  1.064050e+07  1.055649e+07
    3       5.473181e+06  4.858379e+06  1.677709e+07  9.472998e+06
    4       9.922226e+06  4.201194e+06  9.800361e+06  1.275572e+07
    5       4.125389e+06  7.756018e+06  1.869186e+07  6.504791e+06
    6       4.678642e+06  4.224467e+06  2.518887e+07  3.627173e+06
  2 1       3.644101e+06  1.256524e+07  9.875623e+06  1.468625e+07
    2       2.505111e+06  1.064938e+07  1.228027e+07  1.315794e+07
    3       1.185609e+06  1.438050e+07  1.664644e+07  2.085582e+07
    4       0.000000e+00  0.000000e+00  1.354000e+07  1.849880e+07
    5       2.699969e+06  6.589518e+06  1.844234e+07  1.125501e+07
    6       5.347489e+06  1.666934e+06  2.402656e+07  1.314035e+07
  3 1       6.845303e+06  8.088953e+06  7.026633e+06  1.198471e+07
    2       6.791400e+06  8.126454e+06  6.871933e+06  1.194205e+07
    3       5.568472e+06  9.869841e+06  7.841790e+06  1.436360e+07
    4       5.996946e+06  7.012445e+06  1.083332e+07  1.270304e+07
    5       5.457751e+06  7.216572e+06  1.474858e+07  1.371697e+07
    6       4.345450e+06  7.748682e+06  1.004057e+07  1.249107e+07
  4 1       8.161142e+06  5.047079e+06  4.324093e+06  1.076376e+07
    2       4.774378e+06  1.017099e+07  1.605180e+06  1.258624e+07
    3       5.089999e+06  1.336624e+07  8.642849e+06  1.137792e+07
    4       5.663983e+06  7.499946e+06  0.000000e+00  0.000000e+00
    5       8.809935e+06  0.000000e+00  0.000000e+00  2.534725e+07
    6       0.000000e+00  3.729833e+07  3.495980e+07  0.000000e+00
  5 1       5.714518e+06  5.756381e+06  1.441502e+07  7.893638e+06
    2       5.744434e+06  2.887520e+06  2.502223e+07  4.028852e+06
    3       5.337068e+06  1.995839e+06  2.861432e+07  5.247690e+06
    4       4.645778e+06  7.476597e+06  1.919585e+07  1.012386e+07
    5       8.109861e+06  3.498107e+06  2.951537e+07  6.975166e+06
    6       4.087625e+06  4.594725e+06  3.024309e+07  3.610653e+06
  6 1       5.206068e+06  8.346184e+06  2.330181e+07  1.547700e+07
    2       8.320187e+06  4.029790e+06  3.095284e+07  1.182553e+07
    3       3.297066e+06  0.000000e+00  3.520640e+07  1.291898e+07
    4       3.700194e+06  1.018263e+07  2.564267e+07  7.448526e+06
    5       4.483048e+06  1.174108e+06  3.453214e+07  4.845026e+06
    6       7.268599e+06  0.000000e+00  2.962795e+07  4.284684e+06
  7 1       6.857689e+05  1.144650e+06  5.378620e+07  1.499280e+06
    2       3.446134e+05  6.907066e+05  5.749541e+07  7.113266e+05
    3       0.000000e+00  2.911710e+06  6.514569e+07  4.200734e+06
    4       0.000000e+00  0.000000e+00  6.031534e+07  0.000000e+00
    5       0.000000e+00  0.000000e+00  5.946342e+07  0.000000e+00
    6       0.000000e+00  0.000000e+00  5.238740e+07  0.000000e+00

normits_id            9             10            11
p m tp
3 1 1       6.084218e+06  3.024903e+06  6.075501e+06
    2       5.954155e+06  2.905701e+06  5.132598e+06
    3       7.144814e+06  3.279227e+06  3.782535e+06
    4       7.154915e+06  3.254552e+06  1.831151e+06
    5       8.659787e+06  3.753088e+06  1.548575e+06
    6       4.474865e+06  2.474945e+06  9.144357e+06
  2 1       6.901235e+06  3.253406e+06  3.422198e+06
    2       6.091834e+06  2.637826e+06  5.819833e+06
    3       7.174608e+06  2.951869e+06  0.000000e+00
    4       4.676704e+06  1.853226e+06  0.000000e+00
    5       3.443388e+06  1.662170e+06  5.577303e+06
    6       1.481928e+06  1.067915e+06  1.180722e+06
  3 1       7.214059e+06  3.523882e+06  5.034562e+06
    2       7.288963e+06  3.553607e+06  4.996540e+06
    3       6.259262e+06  3.127854e+06  4.411608e+06
    4       6.271445e+06  3.249183e+06  5.222643e+06
    5       6.130858e+06  2.931152e+06  3.658497e+06
    6       7.421734e+06  3.462169e+06  5.192213e+06
  4 1       6.854926e+06  3.372874e+06  4.182137e+06
    2       7.829595e+06  3.734320e+06  2.452752e+06
    3       6.101077e+06  3.041320e+06  1.445042e+06
    4       8.788763e+06  4.867237e+06  1.018353e+07
    5       1.110453e+07  5.436399e+06  0.000000e+00
    6       0.000000e+00  0.000000e+00  0.000000e+00
  5 1       6.189755e+06  3.070521e+06  7.149935e+06
    2       4.206987e+06  1.953464e+06  4.360902e+06
    3       1.395964e+06  7.273704e+05  2.775102e+06
    4       3.817351e+06  1.983967e+06  3.068942e+06
    5       4.694478e+06  2.021625e+06  2.031913e+06
    6       3.500341e+06  1.612410e+06  7.136894e+06
  6 1       1.979080e+06  1.111829e+06  4.594036e+06
    2       1.044440e+06  5.862824e+05  2.730339e+06
    3       6.775819e+05  4.318995e+05  1.144954e+07
    4       7.520710e+06  3.290245e+06  3.252340e+06
    5       3.436728e+06  1.700349e+06  4.588195e+06
    6       5.803446e+06  2.655637e+06  8.897301e+06
  7 1       1.610939e+05  6.260221e+04  3.241448e+05
    2       0.000000e+00  0.000000e+00  1.970760e+06
    3       0.000000e+00  0.000000e+00  0.000000e+00
    4       0.000000e+00  0.000000e+00  0.000000e+00
    5       0.000000e+00  0.000000e+00  0.000000e+00
    6       0.000000e+00  0.000000e+00  0.000000e+00

In [12]:
seg3.data

normits_id                                                  1001001   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1              8.878447
                            2       1        1             28.351606
                            3       1        2              7.892823
                            4       1        2             57.388996
                            5       1        2            118.992421
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                  1001002   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             17.756894
                            2       1        1             56.703212
                            3       1        2             15.785646
                            4       1        2            114.777992
                            5       1        2            237.984843
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                  1001003   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             31.518487
                            2       1        1            100.648201
                            3       1        2             28.019521
                            4       1        2            203.730936
                            5       1        2            422.423096
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                 1001004   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             1.775689
                            2       1        1             5.670321
                            3       1        2             1.578565
                            4       1        2            11.477799
                            5       1        2            23.798484
...                                                             ...
        7 6  6   4   5      6       3        15            0.000000
                            7       2        15            0.000000
                                    3        15            0.000000
                            8       2        15            0.000000
                                    3        15            0.000000

normits_id                                                  1001005   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             17.756894
                            2       1        1             56.703212
                            3       1        2             15.785646
                            4       1        2            114.777992
                            5       1        2            237.984843
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                  1001006   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             10.210214
                            2       1        1             32.604347
                            3       1        2              9.076746
                            4       1        2             65.997346
                            5       1        2            136.841285
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                 1001007   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             3.551379
                            2       1        1            11.340642
                            3       1        2             3.157129
                            4       1        2            22.955598
                            5       1        2            47.596969
...                                                             ...
        7 6  6   4   5      6       3        15            0.000000
                            7       2        15            0.000000
                                    3        15            0.000000
                            8       2        15            0.000000
                                    3        15            0.000000

normits_id                                                 1001008   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             3.995301
                            2       1        1            12.758223
                            3       1        2             3.551770
                            4       1        2            25.825048
                            5       1        2            53.546590
...                                                             ...
        7 6  6   4   5      6       3        15            0.000000
                            7       2        15            0.000000
                                    3        15            0.000000
                            8       2        15            0.000000
                                    3        15            0.000000

normits_id                                                  1001009   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             16.203166
                            2       1        1             51.741681
                            3       1        2             14.404402
                            4       1        2            104.734918
                            5       1        2            217.161169
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                  1001010   ...  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec              ...
1     3 1 1  1   4   1      1       1        1             23.083963  ...
                            2       1        1             73.714175  ...
                            3       1        2             20.521339  ...
                            4       1        2            149.211390  ...
                            5       1        2            309.380295  ...
...                                                              ...  ...
        7 6  6   4   5      6       3        15             0.000000  ...
                            7       2        15             0.000000  ...
                                    3        15             0.000000  ...
                            8       2        15             0.000000  ...
                                    3        15             0.000000  ...

normits_id                                                  11357010  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             33.560116
                            2       1        1            129.251175
                            3       1        2             31.103971
                            4       1        2            256.184946
                            5       1        2            629.615037
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                 11358001  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             1.728411
                            2       1        1             6.656686
                            3       1        2             1.601915
                            4       1        2            13.194021
                            5       1        2            32.426394
...                                                             ...
        7 6  6   4   5      6       3        15            0.000000
                            7       2        15            0.000000
                                    3        15            0.000000
                            8       2        15            0.000000
                                    3        15            0.000000

normits_id                                                   11358002  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             372.001061
                            2       1        1            1432.699867
                            3       1        2             344.775624
                            4       1        2            2839.712193
                            5       1        2            6979.042010
...                                                               ...
        7 6  6   4   5      6       3        15              0.000000
                            7       2        15              0.000000
                                    3        15              0.000000
                            8       2        15              0.000000
                                    3        15              0.000000

normits_id                                                   11358003  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             104.801435
                            2       1        1             403.625199
                            3       1        2              97.131390
                            4       1        2             800.013615
                            5       1        2            1966.160036
...                                                               ...
        7 6  6   4   5      6       3        15              0.000000
                            7       2        15              0.000000
                                    3        15              0.000000
                            8       2        15              0.000000
                                    3        15              0.000000

normits_id                                                   11358004  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1              58.477440
                            2       1        1             225.216078
                            3       1        2              54.197683
                            4       1        2             446.394152
                            5       1        2            1097.084255
...                                                               ...
        7 6  6   4   5      6       3        15              0.000000
                            7       2        15              0.000000
                                    3        15              0.000000
                            8       2        15              0.000000
                                    3        15              0.000000

normits_id                                                   11358005  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1              70.630883
                            2       1        1             272.023033
                            3       1        2              65.461660
                            4       1        2             539.168840
                            5       1        2            1325.092730
...                                                               ...
        7 6  6   4   5      6       3        15              0.000000
                            7       2        15              0.000000
                                    3        15              0.000000
                            8       2        15              0.000000
                                    3        15              0.000000

normits_id                                                   11358006  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             523.831040
                            2       1        1            2017.447635
                            3       1        2             485.493706
                            4       1        2            3998.723514
                            5       1        2            9827.495709
...                                                               ...
        7 6  6   4   5      6       3        15              0.000000
                            7       2        15              0.000000
                                    3        15              0.000000
                            8       2        15              0.000000
                                    3        15              0.000000

normits_id                                                   11358007  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             103.216204
                            2       1        1             397.519944
                            3       1        2              95.662176
                            4       1        2             787.912569
                            5       1        2            1936.419800
...                                                               ...
        7 6  6   4   5      6       3        15              0.000000
                            7       2        15              0.000000
                                    3        15              0.000000
                            8       2        15              0.000000
                                    3        15              0.000000

normits_id                                                  11358008  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             35.931921
                            2       1        1            138.385783
                            3       1        2             33.302191
                            4       1        2            274.290382
                            5       1        2            674.112012
...                                                              ...
        7 6  6   4   5      6       3        15             0.000000
                            7       2        15             0.000000
                                    3        15             0.000000
                            8       2        15             0.000000
                                    3        15             0.000000

normits_id                                                   11358009
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     3 1 1  1   4   1      1       1        1             113.960552
                            2       1        1             438.900007
                            3       1        2             105.620184
                            4       1        2             869.930771
                            5       1        2            2137.992510
...                                                               ...
        7 6  6   4   5      6       3        15              0.000000
                            7       2        15              0.000000
                                    3        15              0.000000
                            8       2        15              0.000000
                                    3        15              0.000000

[29904 rows x 5430 columns]

In [8]:
seg1.data

normits_id                                              1001001   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            8.655133e-01
                              3        1            5.218073e-01
                      2       2        1            2.115866e+00
                              3        1            1.316517e+00
                      3       2        2            5.743153e-01
...                                                          ...
4   1 7 6  6   5      6       3        15           1.087861e-07
                      7       2        15           6.802015e-07
                              3        15           2.424950e-07
                      8       2        15           4.392573e-07
                              3        15           1.379284e-07

normits_id                                              1001002    1001003   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            1.405624e+00   9.171883
                              3        1            8.474332e-01   5.529615
                      2       2        1            3.436240e+00  22.421923
                              3        1            2.138069e+00  13.951185
                      3       2        2            9.327082e-01   6.086045
...                                                          ...        ...
4   1 7 6  6   5      6       3        15           1.551163e-07   0.000001
                      7       2        15           9.698876e-07   0.000008
                              3        15           3.457695e-07   0.000003
                      8       2        15           6.263295e-07   0.000005
                              3        15           1.966697e-07   0.000002

normits_id                                              1001004   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            1.556936e+00
                              3        1            9.386575e-01
                      2       2        1            3.806143e+00
                              3        1            2.368227e+00
                      3       2        2            1.033112e+00
...                                                          ...
4   1 7 6  6   5      6       3        15           2.413875e-07
                      7       2        15           1.509311e-06
                              3        15           5.380766e-07
                      8       2        15           9.746760e-07
                              3        15           3.060517e-07

normits_id                                              1001005   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            1.005276e+00
                              3        1            6.060687e-01
                      2       2        1            2.457536e+00
                              3        1            1.529108e+00
                      3       2        2            6.670558e-01
...                                                          ...
4   1 7 6  6   5      6       3        15           9.304235e-08
                      7       2        15           5.817612e-07
                              3        15           2.074006e-07
                      8       2        15           3.756871e-07
                              3        15           1.179671e-07

normits_id                                              1001006   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            2.626771e+00
                              3        1            1.583648e+00
                      2       2        1            6.421501e+00
                              3        1            3.995534e+00
                      3       2        2            1.743006e+00
...                                                          ...
4   1 7 6  6   5      6       3        15           3.639909e-07
                      7       2        15           2.275908e-06
                              3        15           8.113719e-07
                      8       2        15           1.469725e-06
                              3        15           4.614989e-07

normits_id                                              1001007   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            3.552379e+00
                              3        1            2.141685e+00
                      2       2        1            8.684275e+00
                              3        1            5.403459e+00
                      3       2        2            2.357197e+00
...                                                          ...
4   1 7 6  6   5      6       3        15           5.357307e-07
                      7       2        15           3.349736e-06
                              3        15           1.194197e-06
                      8       2        15           2.163177e-06
                              3        15           6.792453e-07

normits_id                                              1001008   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            4.331963e-01
                              3        1            2.611687e-01
                      2       2        1            1.059008e+00
                              3        1            6.589271e-01
                      3       2        2            2.874494e-01
...                                                          ...
4   1 7 6  6   5      6       3        15           5.607432e-08
                      7       2        15           3.506130e-07
                              3        15           1.249952e-07
                      8       2        15           2.264173e-07
                              3        15           7.109582e-08

normits_id                                              1001009   \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            2.886766e+00
                              3        1            1.740395e+00
                      2       2        1            7.057094e+00
                              3        1            4.391007e+00
                      3       2        2            1.915527e+00
...                                                          ...
4   1 7 6  6   5      6       3        15           3.491778e-07
                      7       2        15           2.183287e-06
                              3        15           7.783521e-07
                      8       2        15           1.409913e-06
                              3        15           4.427176e-07

normits_id                                              1001010   ...  \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec                ...
1   1 1 1  2   1      1       2        1            7.441599e+00  ...
                              3        1            4.486448e+00  ...
                      2       2        1            1.819201e+01  ...
                              3        1            1.131928e+01  ...
                      3       2        2            4.937907e+00  ...
...                                                          ...  ...
4   1 7 6  6   5      6       3        15           9.958562e-07  ...
                      7       2        15           6.226740e-06  ...
                              3        15           2.219862e-06  ...
                      8       2        15           4.021075e-06  ...
                              3        15           1.262632e-06  ...

normits_id                                              11357010  11358001  \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            6.162378e+00  0.756288
                              3        1            3.798584e+00  0.466187
                      2       2        1            1.583004e+01  1.942767
                              3        1            1.030906e+01  1.265196
                      3       2        2            4.760656e+00  0.584259
...                                                          ...       ...
4   1 7 6  6   5      6       3        15           6.207894e-07  0.000000
                      7       2        15           3.668020e-06  0.000000
                              3        15           1.670753e-06  0.000000
                      8       2        15           2.984941e-06  0.000000
                              3        15           1.110333e-06  0.000000

normits_id                                            11358002   11358003  \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1             49.081530  35.258953
                              3        1             30.254610  21.734161
                      2       2        1            126.081643  90.573921
                              3        1             82.108658  58.984821
                      3       2        2             37.917226  27.238794
...                                                        ...        ...
4   1 7 6  6   5      6       3        15             0.000005   0.000004
                      7       2        15             0.000027   0.000024
                              3        15             0.000012   0.000011
                      8       2        15             0.000022   0.000019
                              3        15             0.000008   0.000007

normits_id                                           11358004   11358005  \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            23.232738  20.462075
                              3        1            14.321017  12.613138
                      2       2        1            59.680734  52.563398
                              3        1            38.866126  34.231074
                      3       2        2            17.948116  15.807680
...                                                       ...        ...
4   1 7 6  6   5      6       3        15            0.000003   0.000002
                      7       2        15            0.000016   0.000012
                              3        15            0.000007   0.000005
                      8       2        15            0.000013   0.000009
                              3        15            0.000005   0.000003

normits_id                                            11358006   11358007  \
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            280.760088  23.155129
                              3        1            173.064837  14.273178
                      2       2        1            721.222278  59.481371
                              3        1            469.684500  38.736294
                      3       2        2            216.897145  17.888160
...                                                        ...        ...
4   1 7 6  6   5      6       3        15             0.000025   0.000002
                      7       2        15             0.000146   0.000015
                              3        15             0.000067   0.000007
                      8       2        15             0.000119   0.000012
                              3        15             0.000044   0.000004

normits_id                                           11358008    11358009
soc p m tp aws ns_sec hh_type gender_3 adult_nssec
1   1 1 1  2   1      1       2        1            12.348647   79.230338
                              3        1             7.611896   48.838799
                      2       2        1            31.721457  203.528518
                              3        1            20.658093  132.544700
                      3       2        2             9.539768   61.208251
...                                                       ...         ...
4   1 7 6  6   5      6       3        15            0.000001    0.000008
                      7       2        15            0.000008    0.000048
                              3        15            0.000004    0.000022
                      8       2        15            0.000007    0.000039
                              3        15            0.000002    0.000015

[29904 rows x 5430 columns]

In [18]:
seg6.split_by_other(pp.filter_segment_value("p", [6]), agg_zone=cb.ZoningSystem.get_zoning("gor")).data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:541: TranslationWarning: 3 gor zones missing from zone_translation normits to gor
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1136: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other_grouped_data.rename(columns=translation_dict)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1141: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other.data.rename(columns=translation_dict).groupby(level=0, axis=1).sum()
c:\Users\Spiral\miniforge3\envs\caf.tem_dev\lib\site-packages\caf\toolkit\translation.py:906: UserWarning: Some values seem to have been dropped. The difference total is 5418.999999999996 (translated - original).
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['p', 'tp', 'total', 'm'] to ['soc', 'ns_sec', 'tp', 'aws', 'p', 'total', 'gender_3', 'hh_type', 'adult_nssec', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(

normits_id                                                1001001   1001002   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1            0.035676  0.035676
                            2       1        1            0.145180  0.145180
                            3       1        2            0.026068  0.026068
                            4       1        2            0.318640  0.318640
                            5       1        2            0.862478  0.862478
...                                                            ...       ...
        7 6  6   4   5      6       3        15           0.000006  0.000006
                            7       2        15           0.000005  0.000005
                                    3        15           0.000004  0.000004
                            8       2        15           0.000004  0.000004
                                    3        15           0.000002  0.000002

normits_id                                                1001003   1001004   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1            0.266737  0.112604
                            2       1        1            1.085445  0.458224
                            3       1        2            0.194899  0.082277
                            4       1        2            2.382334  1.005708
                            5       1        2            6.448372  2.722197
...                                                            ...       ...
        7 6  6   4   5      6       3        15           0.000047  0.000020
                            7       2        15           0.000038  0.000016
                                    3        15           0.000026  0.000011
                            8       2        15           0.000026  0.000011
                                    3        15           0.000018  0.000008

normits_id                                                1001005   1001006   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1            0.035676  0.120408
                            2       1        1            0.145180  0.489982
                            3       1        2            0.026068  0.087980
                            4       1        2            0.318640  1.075411
                            5       1        2            0.862478  2.910864
...                                                            ...       ...
        7 6  6   4   5      6       3        15           0.000006  0.000021
                            7       2        15           0.000005  0.000017
                                    3        15           0.000004  0.000012
                            8       2        15           0.000004  0.000012
                                    3        15           0.000002  0.000008

normits_id                                                1001007   1001008   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1            0.234870  0.061160
                            2       1        1            0.955767  0.248880
                            3       1        2            0.171614  0.044688
                            4       1        2            2.097715  0.546241
                            5       1        2            5.677981  1.478534
...                                                            ...       ...
        7 6  6   4   5      6       3        15           0.000041  0.000011
                            7       2        15           0.000034  0.000009
                                    3        15           0.000023  0.000006
                            8       2        15           0.000023  0.000006
                                    3        15           0.000016  0.000004

normits_id                                                1001009   1001010   \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1            0.098110  0.410279
                            2       1        1            0.399244  1.669567
                            3       1        2            0.071687  0.299782
                            4       1        2            0.876261  3.664364
                            5       1        2            2.371815  9.918499
...                                                            ...       ...
        7 6  6   4   5      6       3        15           0.000017  0.000072
                            7       2        15           0.000014  0.000059
                                    3        15           0.000010  0.000041
                            8       2        15           0.000010  0.000041
                                    3        15           0.000007  0.000028

normits_id                                                ...  11357010  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec  ...
1     6 1 1  1   4   1      1       1        1            ...  0.188885
                            2       1        1            ...  0.961990
                            3       1        2            ...  0.161298
                            4       1        2            ...  2.057148
                            5       1        2            ...  6.503385
...                                                       ...       ...
        7 6  6   4   5      6       3        15           ...  0.000044
                            7       2        15           ...  0.000035
                                    3        15           ...  0.000032
                            8       2        15           ...  0.000029
                                    3        15           ...  0.000024

normits_id                                                    11358001  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1            1.950716e-15
                            2       1        1            9.934994e-15
                            3       1        2            1.665814e-15
                            4       1        2            2.124528e-14
                            5       1        2            6.716396e-14
...                                                                ...
        7 6  6   4   5      6       3        15           0.000000e+00
                            7       2        15           0.000000e+00
                                    3        15           0.000000e+00
                            8       2        15           0.000000e+00
                                    3        15           0.000000e+00

normits_id                                                 11358002  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1             1.028212
                            2       1        1             5.236684
                            3       1        2             0.878042
                            4       1        2            11.198277
                            5       1        2            35.401781
...                                                             ...
        7 6  6   4   5      6       3        15            0.000242
                            7       2        15            0.000191
                                    3        15            0.000172
                            8       2        15            0.000160
                                    3        15            0.000130

normits_id                                                 11358003  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1             0.736274
                            2       1        1             3.749843
                            3       1        2             0.628741
                            4       1        2             8.018772
                            5       1        2            25.350222
...                                                             ...
        7 6  6   4   5      6       3        15            0.000173
                            7       2        15            0.000137
                                    3        15            0.000123
                            8       2        15            0.000115
                                    3        15            0.000093

normits_id                                                 11358004  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1             0.373976
                            2       1        1             1.904662
                            3       1        2             0.319357
                            4       1        2             4.072984
                            5       1        2            12.876166
...                                                             ...
        7 6  6   4   5      6       3        15            0.000088
                            7       2        15            0.000070
                                    3        15            0.000063
                            8       2        15            0.000058
                                    3        15            0.000047

normits_id                                                 11358005  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1             0.515843
                            2       1        1             2.627189
                            3       1        2             0.440504
                            4       1        2             5.618057
                            5       1        2            17.760697
...                                                             ...
        7 6  6   4   5      6       3        15            0.000121
                            7       2        15            0.000096
                                    3        15            0.000086
                            8       2        15            0.000080
                                    3        15            0.000065

normits_id                                                  11358006  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1              5.750969
                            2       1        1             29.289680
                            3       1        2              4.911040
                            4       1        2             62.633901
                            5       1        2            198.008282
...                                                              ...
        7 6  6   4   5      6       3        15             0.001352
                            7       2        15             0.001069
                                    3        15             0.000962
                            8       2        15             0.000895
                                    3        15             0.000726

normits_id                                                 11358007  \
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1             0.816844
                            2       1        1             4.160184
                            3       1        2             0.697544
                            4       1        2             8.896258
                            5       1        2            28.124270
...                                                             ...
        7 6  6   4   5      6       3        15            0.000192
                            7       2        15            0.000152
                                    3        15            0.000137
                            8       2        15            0.000127
                                    3        15            0.000103

normits_id                                                 11358008   11358009
total p m tp aws soc ns_sec hh_type gender_3 adult_nssec
1     6 1 1  1   4   1      1       1        1             0.446880   2.070704
                            2       1        1             2.275960  10.546094
                            3       1        2             0.381613   1.768278
                            4       1        2             4.866980  22.552073
                            5       1        2            15.386272  71.295212
...                                                             ...        ...
        7 6  6   4   5      6       3        15            0.000105   0.000487
                            7       2        15            0.000083   0.000385
                                    3        15            0.000075   0.000347
                            8       2        15            0.000070   0.000322
                                    3        15            0.000056   0.000261

[29904 rows x 5430 columns]

In [8]:
mts_ = mts6.aggregate(["soc", "p", "m"])
mts_.data

normits_id                                      1001001   1001002    1001003   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   6.675543  9.518541  77.786995
                                            2   3.039753  4.334332  35.420832
                                            3   0.766248  1.092580   8.928730
                                            4   1.809122  2.579596  21.080860
                                            5   1.706362  2.433072  19.883441
...                                                  ...       ...        ...
 21         3    99          616        1 7 2   0.000000  0.000000   0.000000
                                            3   0.000000  0.000000   0.000000
                                            4   0.000000  0.000000   0.000000
                                            5   0.000000  0.000000   0.000000
                                            6   0.000000  0.000000   0.000000

normits_id                                       1001004   1001005   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   14.812481  5.709444
                                            2    6.744963  2.599834
                                            3    1.700241  0.655355
                                            4    4.014294  1.547302
                                            5    3.786277  1.459413
...                                                   ...       ...
 21         3    99          616        1 7 2    0.000000  0.000000
                                            3    0.000000  0.000000
                                            4    0.000000  0.000000
                                            5    0.000000  0.000000
                                            6    0.000000  0.000000

normits_id                                       1001006    1001007   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   22.335911  32.874536
                                            2   10.170808  14.969641
                                            3    2.563813   3.773482
                                            4    6.053200   8.909246
                                            5    5.709371   8.403190
...                                                   ...        ...
 21         3    99          616        1 7 2    0.000000   0.000000
                                            3    0.000000   0.000000
                                            4    0.000000   0.000000
                                            5    0.000000   0.000000
                                            6    0.000000   0.000000

normits_id                                      1001008    1001009   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   3.440940  21.426922
                                            2   1.566855   9.756893
                                            3   0.394966   2.459475
                                            4   0.932521   5.806857
                                            5   0.879552   5.477020
...                                                  ...        ...
 21         3    99          616        1 7 2   0.000000   0.000000
                                            3   0.000000   0.000000
                                            4   0.000000   0.000000
                                            5   0.000000   0.000000
                                            6   0.000000   0.000000

normits_id                                       1001010   ...   11357010  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp             ...
-1          4   -1          -1          1 1 1   61.109643  ...  44.411358
                                            2   27.826687  ...  16.276331
                                            3    7.014431  ...   4.456905
                                            4   16.561172  ...  12.337271
                                            5   15.620477  ...   7.286887
...                                                   ...  ...        ...
 21         3    99          616        1 7 2    0.000000  ...   0.000000
                                            3    0.000000  ...   0.000000
                                            4    0.000000  ...   0.000000
                                            5    0.000000  ...   0.000000
                                            6    0.000000  ...   0.000000

normits_id                                      11358001    11358002  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   7.761164  329.248489
                                            2   2.829981  120.666369
                                            3   0.644505   33.041755
                                            4   2.231984   91.463720
                                            5   1.042310   54.022138
...                                                  ...         ...
 21         3    99          616        1 7 2   0.000000    0.000000
                                            3   0.000000    0.000000
                                            4   0.000000    0.000000
                                            5   0.000000    0.000000
                                            6   0.000000    0.000000

normits_id                                        11358003    11358004  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   285.429142  193.428871
                                            2   104.607005   70.889800
                                            3    28.644261   19.411568
                                            4    79.290907   53.733653
                                            5    46.832387   31.737249
...                                                    ...         ...
 21         3    99          616        1 7 2     0.000000    0.000000
                                            3     0.000000    0.000000
                                            4     0.000000    0.000000
                                            5     0.000000    0.000000
                                            6     0.000000    0.000000

normits_id                                        11358005     11358006  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   139.792021  1771.048100
                                            2    51.232416   649.071905
                                            3    14.028838   177.733653
                                            4    38.833582   491.989040
                                            5    22.936670   290.588442
...                                                    ...          ...
 21         3    99          616        1 7 2     0.000000     0.000000
                                            3     0.000000     0.000000
                                            4     0.000000     0.000000
                                            5     0.000000     0.000000
                                            6     0.000000     0.000000

normits_id                                        11358007   11358008  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   175.681884  97.751009
                                            2    64.385702  35.824794
                                            3    17.630567   9.809809
                                            4    48.803622  27.154782
                                            5    28.825375  16.038702
...                                                    ...        ...
 21         3    99          616        1 7 2     0.000000   0.000000
                                            3     0.000000   0.000000
                                            4     0.000000   0.000000
                                            5     0.000000   0.000000
                                            6     0.000000   0.000000

normits_id                                        11358009
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   582.594751
                                            2   213.515310
                                            3    58.466336
                                            4   161.842150
                                            5    95.590459
...                                                    ...
 21         3    99          616        1 7 2     0.000000
                                            3     0.000000
                                            4     0.000000
                                            5     0.000000
                                            6     0.000000

[77658 rows x 5430 columns]

In [9]:
pd.data

normits_id                                      7294002     7300001  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.313249    9.580920
                 2       1        1            0.151105    9.728457
                 3       1        2            1.080462   30.511476
                 4       1        2            7.076441  359.556767
                 5       1        2            0.494937   23.445386
...                                                 ...         ...
8 6   4   5      6       3        15           0.095401    8.037112
                 7       2        15           0.026242    4.401600
                         3        15           0.019513    2.809774
                 8       2        15           0.016972    1.887854
                         3        15           0.011470    1.134887

normits_id                                        7305004     7306005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             13.615169    7.657227
                 2       1        1             10.901597    9.865916
                 3       1        2             37.044660   21.851379
                 4       1        2            374.712877  393.115294
                 5       1        2              9.619440   21.633907
...                                                   ...         ...
8 6   4   5      6       3        15             1.694288    6.085480
                 7       2        15             1.728158    4.351812
                         3        15             1.238918    3.006858
                 8       2        15             0.587040    2.033811
                         3        15             0.480968    1.023472

normits_id                                        7307006     7312002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              9.339888   11.862930
                 2       1        1             13.635719    9.680031
                 3       1        2             24.428142   27.475625
                 4       1        2            489.146671  299.604341
                 5       1        2             29.701615   10.512776
...                                                   ...         ...
8 6   4   5      6       3        15             1.774001    5.430465
                 7       2        15             2.558564    3.564083
                         3        15             1.696127    2.161217
                 8       2        15             1.195858    1.421234
                         3        15             0.863464    0.860006

normits_id                                        7313003     7315005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              5.669655   12.405102
                 2       1        1              8.060367   17.505798
                 3       1        2             18.627661   25.705002
                 4       1        2            243.573021  486.842302
                 5       1        2             24.269095   24.810451
...                                                   ...         ...
8 6   4   5      6       3        15             4.370449    2.593577
                 7       2        15             3.885543    2.198381
                         3        15             2.369484    1.696777
                 8       2        15             2.761352    0.999852
                         3        15             1.310707    0.659768

normits_id                                        7316006     7318008  ...  \
p aws soc ns_sec hh_type gender_3 adult_nssec                          ...
1 1   4   1      1       1        1             12.702372    8.911514  ...
                 2       1        1             23.320755   11.251901  ...
                 3       1        2             26.471989   27.984913  ...
                 4       1        2            646.968469  361.196607  ...
                 5       1        2             36.628288   17.867437  ...
...                                                   ...         ...  ...
8 6   4   5      6       3        15             2.972614    4.114171  ...
                 7       2        15             3.965451    6.404432  ...
                         3        15             2.716394    4.995465  ...
                 8       2        15             2.125822    2.998513  ...
                         3        15             1.357996    2.380013  ...

normits_id                                       6255001    6255002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.054578   0.236815
                 2       1        1             1.309479   3.046713
                 3       1        2             0.147817   0.337238
                 4       1        2            23.412928  40.197876
                 5       1        2            26.715225  30.700061
...                                                  ...        ...
8 6   4   5      6       3        15            0.038061   0.038168
                 7       2        15            0.034807   0.040111
                         3        15            0.032652   0.021814
                 8       2        15            0.062286   0.102891
                         3        15            0.049232   0.056713

normits_id                                       6255005     6255006  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.238060    2.252650
                 2       1        1             1.599194   10.089501
                 3       1        2             0.196724    2.989700
                 4       1        2            22.259417  165.238644
                 5       1        2            11.622010   62.463525
...                                                  ...         ...
8 6   4   5      6       3        15            0.189353    2.210982
                 7       2        15            0.289403    1.681657
                         3        15            0.153220    1.300795
                 8       2        15            0.302689    1.359804
                         3        15            0.159754    1.141283

normits_id                                        6255007    6256002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              3.673018   0.263692
                 2       1        1             21.038480   4.806764
                 3       1        2              3.145661   0.122506
                 4       1        2            341.060562  80.680369
                 5       1        2            137.787136  52.272639
...                                                   ...        ...
8 6   4   5      6       3        15             0.280794   0.010708
                 7       2        15             0.536038   0.017950
                         3        15             0.379264   0.027166
                 8       2        15             0.611441   0.028445
                         3        15             0.408374   0.022127

normits_id                                       6256006     6256009  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.254156    3.032856
                 2       1        1             3.173634   24.247488
                 3       1        2             0.252875    3.198995
                 4       1        2            51.729753  380.454820
                 5       1        2            30.613523  158.623127
...                                                  ...         ...
8 6   4   5      6       3        15            0.001879    0.044729
                 7       2        15            0.012211    0.104724
                         3        15            0.012766    0.079433
                 8       2        15            0.017760    0.121347
                         3        15            0.018002    0.078842

normits_id                                        6256010     6257001
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              1.275689    6.532106
                 2       1        1             14.725667   30.193443
                 3       1        2              1.765148    7.907665
                 4       1        2            291.720822  402.116212
                 5       1        2            105.806366  194.403722
...                                                   ...         ...
8 6   4   5      6       3        15             0.029889    0.221753
                 7       2        15             0.030839    0.719602
                         3        15             0.027393    0.445577
                 8       2        15             0.033454    0.519208
                         3        15             0.028675    0.327299

[5696 rows x 5430 columns]

In [18]:
cb.ZoningSystem.get_zoning("gor").zones_data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)

        zone_name  internal  external            descriptions
zone_id
 1              1      True     False              north east
 2              2      True     False              north west
 3              3      True     False  yorkshire & the humber
 4              4     False      True           east midlands
 5              5     False      True           west midlands
 6              6     False      True         east of england
 7              7     False      True                  london
 8              8     False      True              south east
 9              9     False      True              south west
 10            10     False      True                   wales
 11            11     False      True                scotland
-10           -10     False     False                    DEAD
-9             -9     False     False                     DNA
-8             -8     False     False                     nan

In [19]:
translation = pd.zoning_system.translate(cb.ZoningSystem.get_zoning("gor"))
translation

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:541: TranslationWarning: 3 gor zones missing from zone_translation normits to gor
  warnings.warn(

      gor_id  normits_id  gor_to_normits  normits_to_gor
0          4     4015001        0.000214               1
1          4     4015002        0.000200               1
2          4     4015003        0.000152               1
3          4     4015004        0.000133               1
4          4     4015005        0.000206               1
...      ...         ...             ...             ...
5425       3     3190004        0.013916               1
5426       3     3190011        0.007870               1
5427       3     3188005        0.002503               1
5428       3     3188023        0.015565               1
5429       3     3187007        0.004830               1

[5430 rows x 4 columns]

In [23]:
mts_.data

normits_id    1001001      1001002      1001003      1001004     1001005   \
soc p m
1   1 1     108.874124   176.815387  1153.744000   195.849160  126.455119
      2      38.588342    62.668817   408.922395    69.414972   44.819587
      3     620.285447  1007.365265  6573.192824  1115.805843  720.449148
      4      30.503158    49.538195   323.243334    54.870869   35.428808
      5      46.353331    75.279431   491.208333    83.383090   53.838467
      6       6.210119    10.085450    65.808910    11.171126    7.212929
      7       1.288674     2.092852    13.656137     2.318143    1.496769
2   1 1     120.538482   156.968796  1443.866265   219.380202   82.486860
      2      42.722549    55.634574   511.750658    77.755098   29.235883
      3     686.740459   894.293852  8226.098137  1249.868575  469.950037
      4      33.771149    43.977795   404.526607    61.463538   23.110263
      5      51.319449    66.829713   614.728346    93.401468   35.118911
      6       6.875447     8.953412    82.357322    12.513324    4.705004
      7       1.426738     1.857940    17.090131     2.596665    0.976345
3   1 1      70.595858    89.172530   931.381293   275.497875   39.749072
      2      25.021346    31.605490   330.110205    97.644929   14.088295
      3     402.203772   508.040117  5306.332106  1569.586194  226.461258
      4      19.778773    24.983381   260.944191    77.185972   11.136459
      5      30.056298    37.965346   396.537059   117.293656   16.923230
      6       4.026748     5.086351    53.125466    15.714244    2.267265
      7       0.835598     1.055479    11.024171     3.260894    0.470485
4   1 1      14.912794    21.263896   173.771852    33.090266   12.754582
      2       5.285553     7.536579    61.590095    11.728209    4.520617
      3      84.962234   121.146189   990.025425   188.524229   72.666316
      4       4.178103     5.957485    48.685491     9.270868    3.573439
      5       6.349145     9.053137    73.983641    14.088233    5.430283
      6       0.850617     1.212881     9.911849     1.887450    0.727514
      7       0.176513     0.251687     2.056827     0.391669    0.150968

normits_id     1001006      1001007     1001008      1001009      1001010   \
soc p m
1   1 1      330.425205   446.858664   54.492373   363.130283   936.089141
      2      117.112866   158.380468   19.313775   128.704552   331.778812
      3     1882.522107  2545.875137  310.457842  2068.851819  5333.153998
      4       92.574908   125.195957   15.267075   101.737858   262.263184
      5      140.679054   190.250783   23.200214   154.603293   398.541433
      6       18.847268    25.488567    3.108214    20.712748    53.393999
      7        3.911034     5.289183    0.644992     4.298143    11.079894
2   1 1      374.977262   601.750970   67.363775   373.499170  1178.256320
      2      132.903486   213.279070   23.875796   132.379605   417.610316
      3     2136.347270  3428.338656  383.789718  2127.926184  6712.846166
      4      105.057015   168.591984   18.873243   104.642899   330.110927
      5      159.647162   256.196427   28.680234   159.017863   501.644492
      6       21.388493    34.323538    3.842392    21.304183    67.207079
      7        4.438368     7.122545    0.797342     4.420873    13.946274
3   1 1      315.588717   458.730068   32.384557   224.008527   639.413992
      2      111.854358   162.588060   11.478084    79.395519   226.628005
      3     1797.994609  2613.509751  184.503617  1276.237400  3642.915121
      4       88.418184   128.521957    9.073150    62.760251   179.143996
      5      134.362396   195.305052   13.787777    95.371985   272.231519
      6       18.001003    26.165706    1.847197    12.777321    36.471815
      7        3.735424     5.429697    0.383316     2.651447     7.568339
4   1 1       49.897193    73.439899    7.686870    47.866561   136.515569
      2       17.685101    26.029361    2.724463    16.965383    48.385321
      3      284.277855   418.407044   43.794184   272.708792   777.766263
      4       13.979648    20.575585    2.153623    13.410728    38.247434
      5       21.243809    31.267153    3.272697    20.379264    58.121720
      6        2.846108     4.188971    0.438455     2.730282     7.786771
      7        0.590601     0.869262    0.090985     0.566566     1.615848

normits_id  ...     11357010    11358001      11358002      11358003  \
soc p m     ...
1   1 1     ...   801.902166   93.619593   6386.915567   4588.201541
      2     ...   110.517075   17.667164    880.236087    632.339747
      3     ...  4985.209857  595.887507  39705.734415  28523.613617
      4     ...   245.316747   44.194351   1953.875942   1403.615957
      5     ...   916.879766   19.619530   7302.678429   5246.062841
      6     ...   316.270200    1.683453   2518.999385   1809.586605
      7     ...    14.000406    0.270470    111.509128     80.105388
2   1 1     ...   863.908615  116.146918   5928.195598   5674.417314
      2     ...   119.062720   21.918346    817.015920    782.040539
      3     ...  5370.687253  739.273645  36853.995876  35276.324613
      4     ...   264.285670   54.828670   1813.544995   1735.909510
      5     ...   987.776766   24.340502   6778.186694   6488.021405
      6     ...   340.725542    2.088536   2338.080237   2237.990087
      7     ...    15.082976    0.335552    103.500338     99.069624
3   1 1     ...   450.946777  101.008172   3300.794009   3521.775684
      2     ...    62.148877   19.061479    454.910978    485.366374
      3     ...  2803.414698  642.915718  20520.147623  21893.931196
      4     ...   137.952984   47.682227   1009.774113   1077.376507
      5     ...   515.604014   21.167928   3774.065424   4026.731691
      6     ...   177.853401    1.816314   1301.833098   1388.988266
      7     ...     7.873078    0.291816     57.628546     61.486664
4   1 1     ...    91.881011   15.274439    681.169990    590.513768
      2     ...    12.662917    2.882474     93.877929     81.383811
      3     ...   571.199507   97.221609   4234.650424   3671.065099
      4     ...    28.108106    7.210498    208.382535    180.649115
      5     ...   105.055010    3.201011    778.836880    675.182270
      6     ...    36.237869    0.274663    268.653432    232.898619
      7     ...     1.604150    0.044128     11.892544     10.309777

normits_id      11358004      11358005       11358006      11358007  \
soc p m
1   1 1      3023.245918   2662.703130   36534.944270   3013.146769
      2       416.659674    366.970153    5035.196733    415.267823
      3     18794.705866  16553.308432  227127.911548  18731.922180
      4       924.867004    814.570278   11176.717133    921.777487
      5      3456.722187   3044.484385   41773.364092   3445.175012
      6      1192.368136   1050.170067   14409.381362   1188.385032
      7        52.782836     46.488121     637.863414     52.606515
2   1 1      3704.224182   2533.821675   29755.063063   3245.715444
      2       510.511180    349.207885    4100.802651    447.320124
      3     23028.164384  15752.087123  184979.215555  20177.739009
      4      1133.190886    775.143050    9102.625713    992.924558
      5      4235.339852   2897.123767   34021.376185   3711.089634
      6      1460.945951    999.339223   11735.396336   1280.110113
      7        64.672032     44.237980     519.493501     56.666930
3   1 1      2668.080316   1448.236468   17293.343077   2199.736808
      2       367.711230    199.593996    2383.345214    303.164759
      3     16586.736950   9003.296187  107508.057703  13675.171461
      4       816.215259    443.042399    5290.354419    672.940292
      5      3050.632558   1655.886179   19772.881310   2515.137451
      6      1052.290829    571.184437    6820.494198    867.576158
      7        46.582001     25.284753     301.924392     38.405194
4   1 1       400.177817    289.210529    3664.055740    363.461734
      2        55.151967     39.858605     504.975219     50.091806
      3      2487.797744   1797.943988   22778.447995   2259.543741
      4       122.421817     88.474865    1120.902615    111.189686
      5       457.555746    330.677847    4189.412015    415.575271
      6       157.830124    114.064627    1445.103518    143.349302
      7         6.986703      5.049325      63.970731      6.345677

normits_id      11358008      11358009
soc p m
1   1 1      1606.913278  10310.140563
      2       221.462620   1420.929664
      3      9989.747188  64095.367893
      4       491.584578   3154.063239
      5      1837.314241  11788.419668
      6       633.766568   4066.319253
      7        28.055091    180.004694
2   1 1      2048.957849  11060.273247
      2       282.384607   1524.311938
      3     12737.819268  68758.740813
      4       626.814212   3383.542741
      5      2342.739641  12646.107187
      6       808.108939   4362.171569
      7        35.772745    193.101257
3   1 1      1034.557442   6517.426756
      2       142.581311    898.222963
      3      6431.565065  40517.087334
      4       316.490311   1993.801735
      5      1182.893407   7451.902453
      6       408.029437   2570.472995
      7        18.062333    113.787722
4   1 1       202.233437   1205.308676
      2        27.871540    166.114016
      3      1257.230829   7493.079511
      4        61.866960    368.726281
      5       231.229886   1378.127137
      6        79.760864    475.373720
      7         3.530793     21.043478

[28 rows x 5430 columns]

In [22]:
pd.data

normits_id                                      7294002     7300001  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.313249    9.580920
                 2       1        1            0.151105    9.728457
                 3       1        2            1.080462   30.511476
                 4       1        2            7.076441  359.556767
                 5       1        2            0.494937   23.445386
...                                                 ...         ...
8 6   4   5      6       3        15           0.095401    8.037112
                 7       2        15           0.026242    4.401600
                         3        15           0.019513    2.809774
                 8       2        15           0.016972    1.887854
                         3        15           0.011470    1.134887

normits_id                                        7305004     7306005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             13.615169    7.657227
                 2       1        1             10.901597    9.865916
                 3       1        2             37.044660   21.851379
                 4       1        2            374.712877  393.115294
                 5       1        2              9.619440   21.633907
...                                                   ...         ...
8 6   4   5      6       3        15             1.694288    6.085480
                 7       2        15             1.728158    4.351812
                         3        15             1.238918    3.006858
                 8       2        15             0.587040    2.033811
                         3        15             0.480968    1.023472

normits_id                                        7307006     7312002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              9.339888   11.862930
                 2       1        1             13.635719    9.680031
                 3       1        2             24.428142   27.475625
                 4       1        2            489.146671  299.604341
                 5       1        2             29.701615   10.512776
...                                                   ...         ...
8 6   4   5      6       3        15             1.774001    5.430465
                 7       2        15             2.558564    3.564083
                         3        15             1.696127    2.161217
                 8       2        15             1.195858    1.421234
                         3        15             0.863464    0.860006

normits_id                                        7313003     7315005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              5.669655   12.405102
                 2       1        1              8.060367   17.505798
                 3       1        2             18.627661   25.705002
                 4       1        2            243.573021  486.842302
                 5       1        2             24.269095   24.810451
...                                                   ...         ...
8 6   4   5      6       3        15             4.370449    2.593577
                 7       2        15             3.885543    2.198381
                         3        15             2.369484    1.696777
                 8       2        15             2.761352    0.999852
                         3        15             1.310707    0.659768

normits_id                                        7316006     7318008  ...  \
p aws soc ns_sec hh_type gender_3 adult_nssec                          ...
1 1   4   1      1       1        1             12.702372    8.911514  ...
                 2       1        1             23.320755   11.251901  ...
                 3       1        2             26.471989   27.984913  ...
                 4       1        2            646.968469  361.196607  ...
                 5       1        2             36.628288   17.867437  ...
...                                                   ...         ...  ...
8 6   4   5      6       3        15             2.972614    4.114171  ...
                 7       2        15             3.965451    6.404432  ...
                         3        15             2.716394    4.995465  ...
                 8       2        15             2.125822    2.998513  ...
                         3        15             1.357996    2.380013  ...

normits_id                                       6255001    6255002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.054578   0.236815
                 2       1        1             1.309479   3.046713
                 3       1        2             0.147817   0.337238
                 4       1        2            23.412928  40.197876
                 5       1        2            26.715225  30.700061
...                                                  ...        ...
8 6   4   5      6       3        15            0.038061   0.038168
                 7       2        15            0.034807   0.040111
                         3        15            0.032652   0.021814
                 8       2        15            0.062286   0.102891
                         3        15            0.049232   0.056713

normits_id                                       6255005     6255006  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.238060    2.252650
                 2       1        1             1.599194   10.089501
                 3       1        2             0.196724    2.989700
                 4       1        2            22.259417  165.238644
                 5       1        2            11.622010   62.463525
...                                                  ...         ...
8 6   4   5      6       3        15            0.189353    2.210982
                 7       2        15            0.289403    1.681657
                         3        15            0.153220    1.300795
                 8       2        15            0.302689    1.359804
                         3        15            0.159754    1.141283

normits_id                                        6255007    6256002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              3.673018   0.263692
                 2       1        1             21.038480   4.806764
                 3       1        2              3.145661   0.122506
                 4       1        2            341.060562  80.680369
                 5       1        2            137.787136  52.272639
...                                                   ...        ...
8 6   4   5      6       3        15             0.280794   0.010708
                 7       2        15             0.536038   0.017950
                         3        15             0.379264   0.027166
                 8       2        15             0.611441   0.028445
                         3        15             0.408374   0.022127

normits_id                                       6256006     6256009  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.254156    3.032856
                 2       1        1             3.173634   24.247488
                 3       1        2             0.252875    3.198995
                 4       1        2            51.729753  380.454820
                 5       1        2            30.613523  158.623127
...                                                  ...         ...
8 6   4   5      6       3        15            0.001879    0.044729
                 7       2        15            0.012211    0.104724
                         3        15            0.012766    0.079433
                 8       2        15            0.017760    0.121347
                         3        15            0.018002    0.078842

normits_id                                        6256010     6257001
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              1.275689    6.532106
                 2       1        1             14.725667   30.193443
                 3       1        2              1.765148    7.907665
                 4       1        2            291.720822  402.116212
                 5       1        2            105.806366  194.403722
...                                                   ...         ...
8 6   4   5      6       3        15             0.029889    0.221753
                 7       2        15             0.030839    0.719602
                         3        15             0.027393    0.445577
                 8       2        15             0.033454    0.519208
                         3        15             0.028675    0.327299

[5696 rows x 5430 columns]

In [21]:
translation

      gor_id  normits_id  gor_to_normits  normits_to_gor
0          4     4015001        0.000214               1
1          4     4015002        0.000200               1
2          4     4015003        0.000152               1
3          4     4015004        0.000133               1
4          4     4015005        0.000206               1
...      ...         ...             ...             ...
5425       3     3190004        0.013916               1
5426       3     3190011        0.007870               1
5427       3     3188005        0.002503               1
5428       3     3188023        0.015565               1
5429       3     3187007        0.004830               1

[5430 rows x 4 columns]

In [28]:
mts.data

normits_id                                      1001001   1001002    1001003   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   6.675543  9.518541  77.786995
                                            2   3.039753  4.334332  35.420832
                                            3   0.766248  1.092580   8.928730
                                            4   1.809122  2.579596  21.080860
                                            5   1.706362  2.433072  19.883441
...                                                  ...       ...        ...
 21         3    99          616        1 7 2   0.000000  0.000000   0.000000
                                            3   0.000000  0.000000   0.000000
                                            4   0.000000  0.000000   0.000000
                                            5   0.000000  0.000000   0.000000
                                            6   0.000000  0.000000   0.000000

normits_id                                       1001004   1001005   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   14.812481  5.709444
                                            2    6.744963  2.599834
                                            3    1.700241  0.655355
                                            4    4.014294  1.547302
                                            5    3.786277  1.459413
...                                                   ...       ...
 21         3    99          616        1 7 2    0.000000  0.000000
                                            3    0.000000  0.000000
                                            4    0.000000  0.000000
                                            5    0.000000  0.000000
                                            6    0.000000  0.000000

normits_id                                       1001006    1001007   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   22.335911  32.874536
                                            2   10.170808  14.969641
                                            3    2.563813   3.773482
                                            4    6.053200   8.909246
                                            5    5.709371   8.403190
...                                                   ...        ...
 21         3    99          616        1 7 2    0.000000   0.000000
                                            3    0.000000   0.000000
                                            4    0.000000   0.000000
                                            5    0.000000   0.000000
                                            6    0.000000   0.000000

normits_id                                      1001008    1001009   \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   3.440940  21.426922
                                            2   1.566855   9.756893
                                            3   0.394966   2.459475
                                            4   0.932521   5.806857
                                            5   0.879552   5.477020
...                                                  ...        ...
 21         3    99          616        1 7 2   0.000000   0.000000
                                            3   0.000000   0.000000
                                            4   0.000000   0.000000
                                            5   0.000000   0.000000
                                            6   0.000000   0.000000

normits_id                                       1001010   ...   11357010  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp             ...
-1          4   -1          -1          1 1 1   61.109643  ...  44.411358
                                            2   27.826687  ...  16.276331
                                            3    7.014431  ...   4.456905
                                            4   16.561172  ...  12.337271
                                            5   15.620477  ...   7.286887
...                                                   ...  ...        ...
 21         3    99          616        1 7 2    0.000000  ...   0.000000
                                            3    0.000000  ...   0.000000
                                            4    0.000000  ...   0.000000
                                            5    0.000000  ...   0.000000
                                            6    0.000000  ...   0.000000

normits_id                                      11358001    11358002  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   7.761164  329.248489
                                            2   2.829981  120.666369
                                            3   0.644505   33.041755
                                            4   2.231984   91.463720
                                            5   1.042310   54.022138
...                                                  ...         ...
 21         3    99          616        1 7 2   0.000000    0.000000
                                            3   0.000000    0.000000
                                            4   0.000000    0.000000
                                            5   0.000000    0.000000
                                            6   0.000000    0.000000

normits_id                                        11358003    11358004  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   285.429142  193.428871
                                            2   104.607005   70.889800
                                            3    28.644261   19.411568
                                            4    79.290907   53.733653
                                            5    46.832387   31.737249
...                                                    ...         ...
 21         3    99          616        1 7 2     0.000000    0.000000
                                            3     0.000000    0.000000
                                            4     0.000000    0.000000
                                            5     0.000000    0.000000
                                            6     0.000000    0.000000

normits_id                                        11358005     11358006  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   139.792021  1771.048100
                                            2    51.232416   649.071905
                                            3    14.028838   177.733653
                                            4    38.833582   491.989040
                                            5    22.936670   290.588442
...                                                    ...          ...
 21         3    99          616        1 7 2     0.000000     0.000000
                                            3     0.000000     0.000000
                                            4     0.000000     0.000000
                                            5     0.000000     0.000000
                                            6     0.000000     0.000000

normits_id                                        11358007   11358008  \
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   175.681884  97.751009
                                            2    64.385702  35.824794
                                            3    17.630567   9.809809
                                            4    48.803622  27.154782
                                            5    28.825375  16.038702
...                                                    ...        ...
 21         3    99          616        1 7 2     0.000000   0.000000
                                            3     0.000000   0.000000
                                            4     0.000000   0.000000
                                            5     0.000000   0.000000
                                            6     0.000000   0.000000

normits_id                                        11358009
sic_1_digit soc sic_2_digit sic_4_digit p m tp
-1          4   -1          -1          1 1 1   582.594751
                                            2   213.515310
                                            3    58.466336
                                            4   161.842150
                                            5    95.590459
...                                                    ...
 21         3    99          616        1 7 2     0.000000
                                            3     0.000000
                                            4     0.000000
                                            5     0.000000
                                            6     0.000000

[77658 rows x 5430 columns]

In [30]:
mts_.split_by_other(pd.filter_segment_value("p", [1]), cb.ZoningSystem.get_zoning("gor")).data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:541: TranslationWarning: 3 gor zones missing from zone_translation normits to gor
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1136: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other_grouped_data.rename(columns=translation_dict)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:1141: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  other.data.rename(columns=translation_dict).groupby(level=0, axis=1).sum()
c:\Users\Spiral\miniforge3\envs\caf.tem_dev\lib\site-packages\caf\toolkit\translation.py:906: UserWarning: Some values seem to have been dropped. The difference total is 21676.00000000021 (translated - original).
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['m', 'soc', 'p'] to ['ns_sec', 'gender_3', 'hh_type', 'p', 'adult_nssec', 'aws', 'm', 'soc']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(

normits_id                                       1001001   1001002   \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1            1.933509  3.140086
                           3        1            1.165689  1.893119
                   2       2        1            4.726727  7.676370
                           3        1            2.941025  4.776328
                   3       2        2            1.282989  2.083619
...                                                   ...       ...
4   1 7 6   5      6       3        15           0.000003  0.000004
                   7       2        15           0.000019  0.000027
                           3        15           0.000007  0.000010
                   8       2        15           0.000012  0.000018
                           3        15           0.000004  0.000006

normits_id                                        1001003   1001004   \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1            20.489480  3.478109
                           3        1            12.352855  2.096909
                   2       2        1            50.089339  8.502714
                           3        1            31.166178  5.290489
                   3       2        2            13.595889  2.307915
...                                                    ...       ...
4   1 7 6   5      6       3        15            0.000036  0.000007
                   7       2        15            0.000223  0.000043
                           3        15            0.000080  0.000015
                   8       2        15            0.000144  0.000027
                           3        15            0.000045  0.000009

normits_id                                       1001005    1001006   \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1            2.245732   5.868062
                           3        1            1.353924   3.537782
                   2       2        1            5.489999  14.345279
                           3        1            3.415942   8.925802
                   3       2        2            1.490166   3.893779
...                                                   ...        ...
4   1 7 6   5      6       3        15           0.000003   0.000010
                   7       2        15           0.000016   0.000064
                           3        15           0.000006   0.000023
                   8       2        15           0.000011   0.000041
                           3        15           0.000003   0.000013

normits_id                                        1001007   1001008   \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1             7.935818  0.967737
                           3        1             4.784406  0.583436
                   2       2        1            19.400192  2.365765
                           3        1            12.071029  1.472007
                   3       2        2             5.265848  0.642146
...                                                    ...       ...
4   1 7 6   5      6       3        15            0.000015  0.000002
                   7       2        15            0.000094  0.000010
                           3        15            0.000034  0.000004
                   8       2        15            0.000061  0.000006
                           3        15            0.000019  0.000002

normits_id                                        1001009    1001010   ...  \
soc p m aws ns_sec hh_type gender_3 adult_nssec                        ...
1   1 1 2   1      1       2        1             6.448875  16.624121  ...
                           3        1             3.887947  10.022477  ...
                   2       2        1            15.765158  40.639940  ...
                           3        1             9.809267  25.286650  ...
                   3       2        2             4.279181  11.031012  ...
...                                                    ...        ...  ...
4   1 7 6   5      6       3        15            0.000010   0.000028  ...
                   7       2        15            0.000061   0.000175  ...
                           3        15            0.000022   0.000063  ...
                   8       2        15            0.000040   0.000113  ...
                           3        15            0.000012   0.000036  ...

normits_id                                        11357010      11358001  \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1            12.749115  1.488420e+00
                           3        1             7.858750  9.174847e-01
                   2       2        1            32.750187  3.823483e+00
                           3        1            21.328037  2.489982e+00
                   3       2        2             9.849144  1.149857e+00
...                                                    ...           ...
4   1 7 6   5      6       3        15            0.000026  7.105007e-07
                   7       2        15            0.000153  4.198092e-06
                           3        15            0.000070  1.912197e-06
                   8       2        15            0.000124  3.416300e-06
                           3        15            0.000046  1.270789e-06

normits_id                                         11358002    11358003  \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1            101.542958   72.945940
                           3        1             62.592641   44.964999
                   2       2        1            260.845636  187.385027
                           3        1            169.871558  122.031509
                   3       2        2             78.445544   56.353331
...                                                     ...         ...
4   1 7 6   5      6       3        15             0.000191    0.000166
                   7       2        15             0.001131    0.000981
                           3        15             0.000515    0.000447
                   8       2        15             0.000921    0.000798
                           3        15             0.000342    0.000297

normits_id                                         11358004    11358005  \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1             48.065350   42.333228
                           3        1             29.628221   26.094853
                   2       2        1            123.471258  108.746465
                           3        1             80.408687   70.819400
                   3       2        2             37.132191   32.703923
...                                                     ...         ...
4   1 7 6   5      6       3        15             0.000112    0.000081
                   7       2        15             0.000665    0.000480
                           3        15             0.000303    0.000219
                   8       2        15             0.000541    0.000391
                           3        15             0.000201    0.000145

normits_id                                          11358006    11358007  \
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1             580.854135   47.904788
                           3        1             358.047424   29.529248
                   2       2        1            1492.110027  123.058803
                           3        1             971.712846   80.140082
                   3       2        2             448.730461   37.008151
...                                                      ...         ...
4   1 7 6   5      6       3        15              0.001030    0.000102
                   7       2        15              0.006086    0.000604
                           3        15              0.002772    0.000275
                   8       2        15              0.004952    0.000491
                           3        15              0.001842    0.000183

normits_id                                        11358008    11358009
soc p m aws ns_sec hh_type gender_3 adult_nssec
1   1 1 2   1      1       2        1            25.547657  163.916708
                           3        1            15.747969  101.040780
                   2       2        1            65.627346  421.072604
                           3        1            42.738762  274.216814
                   3       2        2            19.736473  126.631482
...                                                    ...         ...
4   1 7 6   5      6       3        15            0.000057    0.000339
                   7       2        15            0.000336    0.002002
                           3        15            0.000153    0.000912
                   8       2        15            0.000273    0.001629
                           3        15            0.000102    0.000606

[4984 rows x 5430 columns]

In [12]:
cb.ZoningSystem.get_zoning("gor").name

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:179: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '-10' '-9' '-8']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  zones.loc[:, name] = zones[name].astype(str)

'gor'

In [ ]:
mts_.zoning_system.translate()

In [21]:
prod = cb.DVector.load(HBProd.model.export_paths.tem_segmented[2023])
prod.data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

normits_id                                      7294002     7300001  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.313249    9.580920
                 2       1        1            0.151105    9.728457
                 3       1        2            1.080462   30.511476
                 4       1        2            7.076441  359.556767
                 5       1        2            0.494937   23.445386
...                                                 ...         ...
8 6   4   5      6       3        15           0.095401    8.037112
                 7       2        15           0.026242    4.401600
                         3        15           0.019513    2.809774
                 8       2        15           0.016972    1.887854
                         3        15           0.011470    1.134887

normits_id                                        7305004     7306005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             13.615169    7.657227
                 2       1        1             10.901597    9.865916
                 3       1        2             37.044660   21.851379
                 4       1        2            374.712877  393.115294
                 5       1        2              9.619440   21.633907
...                                                   ...         ...
8 6   4   5      6       3        15             1.694288    6.085480
                 7       2        15             1.728158    4.351812
                         3        15             1.238918    3.006858
                 8       2        15             0.587040    2.033811
                         3        15             0.480968    1.023472

normits_id                                        7307006     7312002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              9.339888   11.862930
                 2       1        1             13.635719    9.680031
                 3       1        2             24.428142   27.475625
                 4       1        2            489.146671  299.604341
                 5       1        2             29.701615   10.512776
...                                                   ...         ...
8 6   4   5      6       3        15             1.774001    5.430465
                 7       2        15             2.558564    3.564083
                         3        15             1.696127    2.161217
                 8       2        15             1.195858    1.421234
                         3        15             0.863464    0.860006

normits_id                                        7313003     7315005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              5.669655   12.405102
                 2       1        1              8.060367   17.505798
                 3       1        2             18.627661   25.705002
                 4       1        2            243.573021  486.842302
                 5       1        2             24.269095   24.810451
...                                                   ...         ...
8 6   4   5      6       3        15             4.370449    2.593577
                 7       2        15             3.885543    2.198381
                         3        15             2.369484    1.696777
                 8       2        15             2.761352    0.999852
                         3        15             1.310707    0.659768

normits_id                                        7316006     7318008  ...  \
p aws soc ns_sec hh_type gender_3 adult_nssec                          ...
1 1   4   1      1       1        1             12.702372    8.911514  ...
                 2       1        1             23.320755   11.251901  ...
                 3       1        2             26.471989   27.984913  ...
                 4       1        2            646.968469  361.196607  ...
                 5       1        2             36.628288   17.867437  ...
...                                                   ...         ...  ...
8 6   4   5      6       3        15             2.972614    4.114171  ...
                 7       2        15             3.965451    6.404432  ...
                         3        15             2.716394    4.995465  ...
                 8       2        15             2.125822    2.998513  ...
                         3        15             1.357996    2.380013  ...

normits_id                                       6255001    6255002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.054578   0.236815
                 2       1        1             1.309479   3.046713
                 3       1        2             0.147817   0.337238
                 4       1        2            23.412928  40.197876
                 5       1        2            26.715225  30.700061
...                                                  ...        ...
8 6   4   5      6       3        15            0.038061   0.038168
                 7       2        15            0.034807   0.040111
                         3        15            0.032652   0.021814
                 8       2        15            0.062286   0.102891
                         3        15            0.049232   0.056713

normits_id                                       6255005     6255006  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.238060    2.252650
                 2       1        1             1.599194   10.089501
                 3       1        2             0.196724    2.989700
                 4       1        2            22.259417  165.238644
                 5       1        2            11.622010   62.463525
...                                                  ...         ...
8 6   4   5      6       3        15            0.189353    2.210982
                 7       2        15            0.289403    1.681657
                         3        15            0.153220    1.300795
                 8       2        15            0.302689    1.359804
                         3        15            0.159754    1.141283

normits_id                                        6255007    6256002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              3.673018   0.263692
                 2       1        1             21.038480   4.806764
                 3       1        2              3.145661   0.122506
                 4       1        2            341.060562  80.680369
                 5       1        2            137.787136  52.272639
...                                                   ...        ...
8 6   4   5      6       3        15             0.280794   0.010708
                 7       2        15             0.536038   0.017950
                         3        15             0.379264   0.027166
                 8       2        15             0.611441   0.028445
                         3        15             0.408374   0.022127

normits_id                                       6256006     6256009  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.254156    3.032856
                 2       1        1             3.173634   24.247488
                 3       1        2             0.252875    3.198995
                 4       1        2            51.729753  380.454820
                 5       1        2            30.613523  158.623127
...                                                  ...         ...
8 6   4   5      6       3        15            0.001879    0.044729
                 7       2        15            0.012211    0.104724
                         3        15            0.012766    0.079433
                 8       2        15            0.017760    0.121347
                         3        15            0.018002    0.078842

normits_id                                        6256010     6257001
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              1.275689    6.532106
                 2       1        1             14.725667   30.193443
                 3       1        2              1.765148    7.907665
                 4       1        2            291.720822  402.116212
                 5       1        2            105.806366  194.403722
...                                                   ...         ...
8 6   4   5      6       3        15             0.029889    0.221753
                 7       2        15             0.030839    0.719602
                         3        15             0.027393    0.445577
                 8       2        15             0.033454    0.519208
                         3        15             0.028675    0.327299

[5696 rows x 5430 columns]

In [27]:
list(mts_.segmentation.overlap(pd.segmentation))

['soc', 'p']

In [26]:
pd.data.groupby(level={"p", "aws"}).sum()

AssertionError: Level {'aws', 'p'} not in index

In [8]:
mts = cb.DVector.load(HBAttr.mts_path)

NameError: name 'HBAttr' is not defined

In [33]:
mts_ = mts.add_segments([cb.segmentation.SegmentsSuper("soc").get_segment(subset=[1])]).filter_segment_value("p", [1])#.data#.data.head(80).style

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [34]:
a = mts * mts_

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:819: SegmentationWarning: There are subsets in other's segmentation not in self. This will lead to rows present in self being cut in the product. Missing values are {'p': [2, 3, 4, 5, 6, 7, 8]}
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['p', 'm', 'tp'] to ['m', 'soc', 'tp', 'p']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(

In [35]:
a.data

tfn_at                1             2             3             4   \
p m tp soc
1 1 1  1    2.650947e-03  3.262507e-03  2.779851e-03  1.587168e-03
    2  1    2.030687e-04  2.186517e-04  2.106004e-04  2.162439e-04
    3  1    8.781875e-06  5.862122e-06  2.405964e-05  1.794597e-05
    4  1    4.016722e-05  8.643611e-05  1.479758e-04  1.332884e-04
    5  1    5.759191e-06  3.977150e-05  4.116369e-05  3.887631e-05
    6  1    1.244070e-05  9.890214e-06  4.601095e-05  1.546816e-05
  2 1  1    1.083712e-03  1.920797e-04  2.241536e-04  8.789501e-05
    2  1    2.367358e-05  6.572250e-06  5.542964e-06  5.156470e-06
    3  1    7.061571e-07  4.698408e-07  4.317979e-06  7.301041e-08
    4  1    3.256496e-05  4.588920e-05  4.024408e-05  3.483134e-05
    5  1    2.588710e-06  2.850494e-06  4.388630e-06  9.192990e-07
    6  1    1.070167e-06  1.049801e-06  1.380823e-06  1.186328e-07
  3 1  1    5.777807e-03  9.340753e-02  1.994007e-01  1.364100e-01
    2  1    2.812228e-04  3.850527e-03  6.193986e-03  5.363825e-03
    3  1    4.119736e-05  8.286537e-04  2.028884e-03  1.468085e-03
    4  1    1.356284e-03  1.724672e-02  1.532648e-02  2.305868e-02
    5  1    1.059595e-04  1.368620e-03  2.219454e-03  2.195826e-03
    6  1    4.604908e-05  6.269732e-04  7.358784e-04  8.853022e-04
  4 1  1    9.598725e-06  2.209679e-04  2.397035e-04  2.674164e-04
    2  1    2.534405e-07  5.013017e-06  2.260405e-06  1.087482e-06
    3  1    6.274807e-08  3.689310e-07  2.011807e-06  2.138518e-06
    4  1    1.968720e-05  6.850306e-05  7.358896e-05  8.394681e-05
    5  1    2.633014e-07  3.052612e-06  3.235220e-06  5.894768e-06
    6  1    1.719692e-07  6.382552e-07  2.663410e-07  7.711966e-07
  5 1  1    4.843732e-03  5.654272e-03  2.561024e-04  3.950661e-03
    2  1    2.783932e-04  5.461099e-04  1.561956e-05  2.598914e-04
    3  1    4.570788e-05  3.147459e-05  4.665717e-06  1.323179e-05
    4  1    8.548314e-04  8.978656e-04  9.696127e-05  4.469417e-04
    5  1    7.201923e-05  1.144815e-04  7.763545e-06  4.924924e-05
    6  1    2.735303e-05  5.286145e-05  3.719180e-06  1.126678e-05
  6 1  1    4.011213e-02  1.770107e-03  4.613120e-04  8.524157e-04
    2  1    1.275830e-04  8.665512e-06  3.500456e-06  5.176336e-06
    3  1    6.603326e-06  2.862922e-07  6.847494e-07  5.405730e-07
    4  1    5.712472e-03  3.189688e-04  5.739104e-05  7.108051e-05
    5  1    3.032228e-05  8.304842e-06  2.774842e-06  2.968655e-06
    6  1    1.138497e-05  1.448957e-06  1.181635e-06  3.147310e-07
  7 1  1    3.793320e-02  6.725873e-04  8.461946e-06  3.144201e-06
    2  1    4.306654e-04  1.150665e-05  1.083676e-07  8.700321e-08
    3  1    3.519232e-05  6.461910e-07  0.000000e+00  0.000000e+00
    4  1    1.436586e-03  7.944202e-05  6.989598e-07  1.192878e-07
    5  1    1.062150e-04  5.370124e-06  1.156525e-07  9.043160e-09
    6  1    2.995475e-05  1.006122e-06  6.598309e-08  2.087104e-08

tfn_at                5             6             7             8   \
p m tp soc
1 1 1  1    3.192758e-03  1.612215e-03  3.156028e-03  2.634846e-03
    2  1    3.811451e-04  4.265389e-04  6.181368e-04  4.310331e-04
    3  1    3.014942e-05  2.505794e-05  3.812746e-05  1.709409e-05
    4  1    2.077180e-04  9.679078e-05  1.934794e-04  2.895301e-04
    5  1    6.201900e-05  4.235639e-05  3.221061e-05  5.693915e-05
    6  1    2.059163e-05  2.460243e-05  1.776592e-05  2.952050e-05
  2 1  1    1.486209e-04  7.364547e-05  3.855905e-05  3.291935e-04
    2  1    7.883147e-06  5.617689e-06  1.067301e-06  1.706225e-05
    3  1    1.246202e-06  4.197119e-07  9.888631e-08  1.826760e-06
    4  1    3.127703e-05  2.597329e-05  1.481768e-05  3.757193e-05
    5  1    1.326729e-06  1.174722e-06  2.765328e-07  3.484888e-06
    6  1    5.012076e-07  3.866821e-07  3.244515e-07  1.403703e-06
  3 1  1    1.378192e-01  1.310473e-01  1.355055e-01  1.336533e-01
    2  1    5.304653e-03  5.067716e-03  5.326931e-03  4.634778e-03
    3  1    1.463250e-03  1.821717e-03  2.003718e-03  1.291051e-03
    4  1    1.736265e-02  2.057354e-02  2.152513e-02  2.378052e-02
    5  1    2.138693e-03  2.467065e-03  2.245675e-03  2.051447e-03
    6  1    7.980561e-04  8.309468e-04  7.798902e-04  8.563590e-04
  4 1  1    2.812898e-04  3.143627e-04  2.396704e-04  3.928175e-04
    2  1    2.058477e-06  7.686660e-07  3.942990e-06  4.429101e-06
    3  1    5.398500e-07  6.154817e-08  2.081961e-07  1.487622e-06
    4  1    5.025190e-05  4.447009e-05  1.162204e-04  7.400447e-05
    5  1    3.812881e-06  3.023354e-06  5.789981e-06  5.039770e-06
    6  1    1.132243e-06  1.384934e-06  6.298324e-07  1.577632e-06
  5 1  1    2.877623e-03  3.947198e-03  3.272328e-03  2.662163e-03
    2  1    2.159043e-04  3.549480e-04  1.368005e-04  2.202257e-04
    3  1    1.600128e-05  1.098400e-05  1.433062e-05  9.946786e-06
    4  1    2.568293e-04  3.438718e-04  2.897259e-04  4.116910e-04
    5  1    5.431632e-05  7.552015e-05  2.680201e-05  4.524286e-05
    6  1    1.717117e-05  1.518612e-05  6.452356e-06  1.208948e-05
  6 1  1    7.097498e-04  4.966670e-06  7.215235e-04  1.065080e-04
    2  1    3.708400e-06  2.501811e-08  8.479552e-06  3.601375e-07
    3  1    4.628024e-08  0.000000e+00  4.541615e-07  7.283011e-09
    4  1    7.024904e-05  8.675225e-07  5.117487e-05  7.383253e-06
    5  1    1.553497e-06  6.254527e-09  1.493191e-06  1.233873e-07
    6  1    1.796492e-07  5.945438e-09  5.710478e-08  8.970470e-09
  7 1  1    6.505981e-05  9.854102e-04  4.138538e-08  5.587916e-05
    2  1    9.272749e-07  1.901728e-05  0.000000e+00  8.247693e-07
    3  1    1.217783e-07  1.048228e-06  0.000000e+00  3.167708e-07
    4  1    1.632530e-06  5.793342e-05  0.000000e+00  9.169550e-06
    5  1    2.583622e-07  8.706692e-06  0.000000e+00  6.951517e-07
    6  1    3.348491e-07  1.722689e-06  0.000000e+00  9.072560e-08

tfn_at                9             10            11            12  \
p m tp soc
1 1 1  1    2.996464e-03  4.363178e-03  4.360496e-03  2.920288e-03
    2  1    4.184699e-04  4.650723e-04  5.873182e-04  3.585155e-04
    3  1    1.596969e-05  3.194074e-05  5.638463e-05  1.820179e-05
    4  1    1.424837e-04  1.820036e-04  1.724080e-04  1.865625e-04
    5  1    5.179716e-05  1.290925e-04  1.172527e-04  4.287132e-05
    6  1    2.245918e-05  2.282965e-05  3.536445e-05  7.492994e-06
  2 1  1    6.369137e-04  6.257099e-04  4.521269e-04  8.874575e-05
    2  1    4.215517e-05  2.658320e-05  1.350646e-05  1.247853e-05
    3  1    2.673043e-06  1.727657e-06  2.158294e-06  1.415751e-06
    4  1    1.219878e-04  7.567488e-05  7.133508e-05  1.329535e-04
    5  1    5.744893e-06  6.489696e-06  3.916300e-06  2.250083e-06
    6  1    1.549354e-06  2.578243e-06  1.868808e-06  1.331115e-06
  3 1  1    1.665152e-01  1.617892e-01  1.657997e-01  1.714646e-01
    2  1    5.980681e-03  5.428339e-03  5.774363e-03  7.744562e-03
    3  1    1.643560e-03  1.530172e-03  1.542090e-03  2.161171e-03
    4  1    2.022346e-02  1.634283e-02  1.776542e-02  2.358977e-02
    5  1    2.267614e-03  2.148488e-03  2.228714e-03  2.823933e-03
    6  1    9.073295e-04  9.683694e-04  8.260150e-04  1.055555e-03
  4 1  1    3.453580e-04  4.068350e-04  5.274936e-04  3.169299e-04
    2  1    4.342827e-06  2.013669e-06  5.665263e-06  3.949132e-06
    3  1    2.890412e-07  1.208870e-06  2.735636e-07  1.906112e-06
    4  1    1.692302e-04  6.737648e-05  6.701737e-05  1.244267e-04
    5  1    7.387782e-06  4.023051e-06  5.230959e-06  6.467518e-06
    6  1    8.144158e-07  5.944677e-07  2.013012e-06  1.642251e-06
  5 1  1    7.091067e-04  8.153797e-04  8.615794e-04  4.977916e-04
    2  1    4.587544e-05  4.985940e-05  6.100038e-05  2.320222e-05
    3  1    2.360898e-06  3.888149e-06  2.137128e-06  1.886095e-06
    4  1    5.639762e-05  1.045113e-04  5.465335e-05  5.874168e-05
    5  1    1.290460e-05  1.711700e-05  1.436527e-05  8.663823e-06
    6  1    1.878559e-06  3.929649e-06  1.966803e-06  1.109572e-06
  6 1  1    1.063794e-04  2.642095e-04  8.446915e-05  1.515203e-05
    2  1    8.494980e-07  1.706472e-06  8.702175e-07  4.629047e-07
    3  1    4.827415e-08  2.064103e-07  7.066186e-08  2.190398e-08
    4  1    2.729512e-05  2.722031e-05  6.596021e-06  2.084677e-06
    5  1    5.820667e-07  1.018066e-06  1.112910e-07  6.364988e-07
    6  1    4.320373e-08  2.042715e-07  2.976154e-08  1.760851e-07
  7 1  1    0.000000e+00  4.648349e-09  0.000000e+00  0.000000e+00
    2  1    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
    3  1    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
    4  1    9.473087e-09  8.672237e-10  0.000000e+00  0.000000e+00
    5  1    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
    6  1    0.000000e+00  9.695608e-10  0.000000e+00  0.000000e+00

tfn_at                13            14            15            16  \
p m tp soc
1 1 1  1    3.286461e-03  3.044181e-03  3.271298e-03  1.826922e-03
    2  1    4.955589e-04  6.443409e-04  6.783028e-04  4.626062e-04
    3  1    5.125163e-05  4.360094e-05  4.310081e-05  9.255718e-05
    4  1    2.607050e-04  2.159548e-04  2.402607e-04  5.531032e-05
    5  1    6.271840e-05  7.718025e-05  2.137417e-04  1.920143e-04
    6  1    2.356830e-05  4.833853e-05  6.156246e-05  1.931373e-05
  2 1  1    3.299116e-04  2.054484e-04  4.229047e-04  9.249223e-05
    2  1    1.692811e-05  1.933080e-05  4.720298e-05  5.124338e-06
    3  1    4.194992e-06  8.789664e-07  6.335369e-07  6.234344e-07
    4  1    6.488268e-05  7.796400e-05  1.437503e-04  1.656389e-05
    5  1    5.469415e-06  3.106608e-06  8.713239e-06  1.813545e-06
    6  1    2.460448e-06  1.908081e-06  4.467068e-06  3.717044e-07
  3 1  1    1.539513e-01  1.672797e-01  1.484504e-01  1.720341e-01
    2  1    8.070220e-03  7.260683e-03  6.000130e-03  1.035448e-02
    3  1    1.838461e-03  1.752468e-03  2.124176e-03  1.473312e-03
    4  1    2.486159e-02  1.805052e-02  1.769490e-02  2.801319e-02
    5  1    2.487791e-03  2.683099e-03  2.516667e-03  2.681541e-03
    6  1    1.173954e-03  1.385002e-03  1.289950e-03  8.719784e-04
  4 1  1    3.145373e-04  4.506071e-04  4.314873e-04  8.419080e-04
    2  1    4.869700e-06  1.852176e-06  1.887980e-06  1.111714e-05
    3  1    3.244555e-07  1.713315e-07  4.121341e-07  1.427337e-06
    4  1    8.227501e-05  6.492583e-05  8.041249e-05  1.019128e-04
    5  1    8.482663e-06  7.653557e-06  6.501977e-06  5.766688e-06
    6  1    1.943240e-06  1.228489e-06  2.226086e-06  9.704717e-07
  5 1  1    6.286444e-04  6.589247e-04  9.373266e-04  2.946419e-05
    2  1    3.310650e-05  8.737630e-05  5.920014e-05  1.357390e-05
    3  1    1.526773e-06  2.385292e-06  3.670307e-06  3.961783e-07
    4  1    5.848051e-05  3.110088e-05  6.447541e-05  5.647046e-05
    5  1    8.435387e-06  1.523323e-05  1.843927e-05  2.281773e-06
    6  1    6.213958e-07  2.763985e-06  3.419598e-06  2.235489e-07
  6 1  1    4.952582e-06  3.907255e-05  2.479549e-05  3.014544e-05
    2  1    2.009326e-08  4.478378e-07  6.570849e-07  9.501258e-07
    3  1    1.498903e-09  0.000000e+00  1.779944e-09  3.524976e-07
    4  1    1.535294e-06  7.981095e-07  1.119203e-06  6.339257e-06
    5  1    5.121702e-09  2.794131e-07  6.592905e-08  9.791391e-08
    6  1    8.175608e-10  7.977223e-09  1.987954e-08  2.063837e-07
  7 1  1    5.201212e-09  1.750844e-08  3.847855e-07  0.000000e+00
    2  1    0.000000e+00  3.071229e-09  1.994045e-07  0.000000e+00
    3  1    0.000000e+00  0.000000e+00  1.267110e-09  0.000000e+00
    4  1    0.000000e+00  0.000000e+00  2.162593e-08  1.248668e-06
    5  1    0.000000e+00  1.295947e-09  4.373720e-08  7.260450e-08
    6  1    1.681088e-09  1.136116e-09  2.883518e-09  2.283083e-08

tfn_at                17            18            19            20
p m tp soc
1 1 1  1    3.787589e-03  8.576776e-04  1.826707e-03  2.750928e-03
    2  1    5.035890e-04  2.803619e-04  3.914289e-04  3.694912e-04
    3  1    2.611935e-05  2.118433e-06  4.080319e-05  2.770498e-05
    4  1    3.132502e-04  7.173913e-05  1.416321e-04  2.122899e-04
    5  1    6.831295e-05  4.673792e-05  5.506817e-05  7.405854e-05
    6  1    3.674995e-05  5.003701e-06  2.766486e-05  7.055150e-05
  2 1  1    1.037854e-04  1.822454e-04  1.272799e-04  7.200131e-05
    2  1    1.206646e-05  2.043155e-05  7.496792e-06  3.181401e-06
    3  1    3.350941e-06  3.154958e-07  4.539948e-07  3.020213e-07
    4  1    2.700936e-05  2.771861e-05  1.485248e-05  7.514778e-06
    5  1    2.176514e-06  1.251329e-06  1.053858e-06  8.111294e-07
    6  1    4.801536e-07  1.709719e-06  1.479042e-06  2.442793e-07
  3 1  1    1.698294e-01  1.969970e-01  1.553061e-01  1.448563e-01
    2  1    8.009098e-03  7.021907e-03  8.066299e-03  5.827221e-03
    3  1    1.722617e-03  1.442407e-03  2.102311e-03  1.443193e-03
    4  1    2.006810e-02  2.681150e-02  2.507183e-02  1.082065e-02
    5  1    2.703045e-03  2.930858e-03  3.914611e-03  1.679355e-03
    6  1    1.168262e-03  1.400328e-03  1.845733e-03  1.200767e-03
  4 1  1    1.093521e-03  1.156846e-03  1.512322e-03  3.733097e-04
    2  1    9.348769e-06  2.013739e-05  2.654323e-05  1.700542e-06
    3  1    2.759010e-06  1.142131e-06  1.535517e-06  3.089306e-07
    4  1    1.889109e-04  3.276501e-04  2.688773e-04  8.115416e-05
    5  1    1.799588e-05  1.827482e-05  2.166067e-05  4.397722e-06
    6  1    1.968737e-06  5.943420e-06  6.507275e-06  8.255811e-07
  5 1  1    2.076879e-04  6.863622e-05  1.047576e-04  5.324281e-03
    2  1    1.626367e-05  8.649420e-06  2.644268e-06  2.205303e-04
    3  1    4.315957e-07  6.497432e-08  4.410928e-07  1.703776e-05
    4  1    1.198993e-05  1.201265e-05  3.180903e-05  4.041986e-04
    5  1    4.117697e-06  5.852549e-07  1.920640e-06  6.974457e-05
    6  1    6.239457e-07  1.023602e-07  1.578221e-06  1.344755e-05
  6 1  1    2.316779e-06  2.222007e-05  1.043104e-06  1.109488e-03
    2  1    0.000000e+00  3.219050e-07  2.833177e-08  7.839067e-06
    3  1    0.000000e+00  1.211012e-07  1.557740e-08  7.962637e-07
    4  1    2.601790e-07  1.269245e-06  4.807811e-07  1.364203e-05
    5  1    8.839998e-09  1.370430e-08  6.349055e-08  2.042914e-06
    6  1    2.681755e-09  8.667566e-08  2.079829e-08  4.522854e-07
  7 1  1    3.018879e-08  3.893096e-08  0.000000e+00  9.580114e-07
    2  1    0.000000e+00  0.000000e+00  0.000000e+00  2.500956e-07
    3  1    0.000000e+00  0.000000e+00  0.000000e+00  6.042476e-08
    4  1    3.103722e-08  0.000000e+00  0.000000e+00  0.000000e+00
    5  1    0.000000e+00  0.000000e+00  0.000000e+00  1.543976e-08
    6  1    0.000000e+00  0.000000e+00  0.000000e+00  2.073417e-09

In [8]:
cb.Segmentation(cb.SegmentationInput(enum_segments=["soc"], naming_order=["soc"]))

In [63]:
HBProd.export_paths.export_paths.tem_segmented[2023]

WindowsPath('C:/Users/Spiral/Documents/Thomas Prince/Common Analytical Framework/NoTEM/Export/TP_v2/Core/hb_productions/hb_normits_tem_segmented_2023_dvec.h5')

In [4]:
HBattr = tem.HBAttractionModel(trip_rates_paths={
        1: r"T:\ThomasPrince\hb_attraction_triprates_p1.dvec",
        2: r"T:\ThomasPrince\hb_attraction_triprates_p2.dvec",
        3: r"T:\ThomasPrince\hb_attraction_triprates_p3.dvec",
        4: r"T:\ThomasPrince\hb_attraction_triprates_p4.dvec",
        5: r"T:\ThomasPrince\hb_attraction_triprates_p5.dvec",
        6: r"T:\ThomasPrince\hb_attraction_triprates_p6.dvec",
        8: r"T:\ThomasPrince\hb_attraction_triprates_p8.dvec"
    },
    balance_production=False,
    emp_landuse_paths = {2023: r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf"},
    hh_landuse_dirs = {2023: r"F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs"},
    hh_landuse_prefix = "Output P14.1",
    hb_mts_split_path=r"C:\Users\Spiral\Documents\Thomas Prince\NTS Processing DVec\outputs_is\attractions\hb\mode_time_splits\hb_mode_time_split_attraction_hb_fr.dvec")

In [8]:
pure_demand = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_v2\Core\hb_attractions\hb_normits_pure_demand_2023_dvec.h5")

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [9]:
pure_demand.data

                                             1001001     1001002   \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  116.714960  166.421855
                                        2   17.490968   24.940071
                                        3    0.000000    0.000000
                                        4    0.000000    0.000000
                                        5    0.000000    0.000000
...                                               ...         ...
 616         99         3    21         3    0.000000    0.000000
                                        4    0.000000    0.000000
                                        5    0.000000    0.000000
                                        6    0.000000    0.000000
                                        8    0.000000    0.000000

                                              1001003     1001004    1001005   \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  1360.025180  258.980923  99.823719
                                        2   203.814122   38.811024  14.959637
                                        3     0.000000    0.000000   0.000000
                                        4     0.000000    0.000000   0.000000
                                        5     0.000000    0.000000   0.000000
...                                                ...         ...        ...
 616         99         3    21         3     0.000000    0.000000   0.000000
                                        4     0.000000    0.000000   0.000000
                                        5     0.000000    0.000000   0.000000
                                        6     0.000000    0.000000   0.000000
                                        8     0.000000    0.000000   0.000000

                                             1001006     1001007    1001008   \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  390.520315  574.777274  60.161276
                                        2   58.523589   86.136439   9.015802
                                        3    0.000000    0.000000   0.000000
                                        4    0.000000    0.000000   0.000000
                                        5    0.000000    0.000000   0.000000
...                                               ...         ...        ...
 616         99         3    21         3    0.000000    0.000000   0.000000
                                        4    0.000000    0.000000   0.000000
                                        5    0.000000    0.000000   0.000000
                                        6    0.000000    0.000000   0.000000
                                        8    0.000000    0.000000   0.000000

                                             1001009      1001010   ...  \
sic_4_digit sic_2_digit soc sic_1_digit p                           ...
-1          -1          4   -1          1  374.627575  1068.438926  ...
                                        2   56.141894   160.116845  ...
                                        3    0.000000     0.000000  ...
                                        4    0.000000     0.000000  ...
                                        5    0.000000     0.000000  ...
...                                               ...          ...  ...
 616         99         3    21         3    0.000000     0.000000  ...
                                        4    0.000000     0.000000  ...
                                        5    0.000000     0.000000  ...
                                        6    0.000000     0.000000  ...
                                        8    0.000000     0.000000  ...

                                            11357010    11358001     11358002  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  846.74857  126.108822  6277.463733
                                        2  117.32830   12.965870   869.826269
                                        3    0.00000    0.000000     0.000000
                                        4    0.00000    0.000000     0.000000
                                        5    0.00000    0.000000     0.000000
...                                              ...         ...          ...
 616         99         3    21         3    0.00000    0.000000     0.000000
                                        4    0.00000    0.000000     0.000000
                                        5    0.00000    0.000000     0.000000
                                        6    0.00000    0.000000     0.000000
                                        8    0.00000    0.000000     0.000000

                                              11358003     11358004  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  5442.002459  3687.921918
                                        2   754.061974   511.010736
                                        3     0.000000     0.000000
                                        4     0.000000     0.000000
                                        5     0.000000     0.000000
...                                                ...          ...
 616         99         3    21         3     0.000000     0.000000
                                        4     0.000000     0.000000
                                        5     0.000000     0.000000
                                        6     0.000000     0.000000
                                        8     0.000000     0.000000

                                              11358005      11358006  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  2665.279787  33766.867833
                                        2   369.310039   4678.849599
                                        3     0.000000      0.000000
                                        4     0.000000      0.000000
                                        5     0.000000      0.000000
...                                                ...           ...
 616         99         3    21         3     0.000000      0.000000
                                        4     0.000000      0.000000
                                        5     0.000000      0.000000
                                        6     0.000000      0.000000
                                        8     0.000000      0.000000

                                              11358007     11358008  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  3349.557217  1863.724308
                                        2   464.125797   258.243844
                                        3     0.000000     0.000000
                                        4     0.000000     0.000000
                                        5     0.000000     0.000000
...                                                ...          ...
 616         99         3    21         3     0.000000     0.000000
                                        4     0.000000     0.000000
                                        5     0.000000     0.000000
                                        6     0.000000     0.000000
                                        8     0.000000     0.000000

                                               11358009
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  11107.772819
                                        2   1539.129974
                                        3      0.000000
                                        4      0.000000
                                        5      0.000000
...                                                 ...
 616         99         3    21         3      0.000000
                                        4      0.000000
                                        5      0.000000
                                        6      0.000000
                                        8      0.000000

[12943 rows x 5430 columns]

In [3]:
pure_production = cb.DVector.load(HBProd.trip_rates_path)

NameError: name 'HBProd' is not defined

In [16]:
pure_production.data

                                                      1         2         3  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.007905  0.014785  0.040716
                 2       1        1            0.013089  0.021696  0.065175
                 3       1        2            0.007254  0.012891  0.032245
                 4       1        2            0.055611  0.105189  0.282388
                 5       1        2            0.017164  0.029233  0.081469
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.168882  0.135028  0.141341
                 7       2        15           0.506160  0.440260  0.471015
                         3        15           0.335909  0.285860  0.308587
                 8       2        15           0.630635  0.828064  0.571972
                         3        15           0.432040  0.539231  0.362945

                                                      4         5         6  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.021608  0.028700  0.036847
                 2       1        1            0.035957  0.046342  0.062144
                 3       1        2            0.023958  0.025984  0.035110
                 4       1        2            0.169451  0.205875  0.273344
                 5       1        2            0.046586  0.056295  0.071256
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.115564  0.107696  0.145048
                 7       2        15           0.394626  0.426106  0.490627
                         3        15           0.258106  0.219246  0.296748
                 8       2        15           0.489652  0.499022  0.587258
                         3        15           0.314154  0.333153  0.383186

                                                      7         8         9  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.020657  0.020283  0.034148
                 2       1        1            0.040156  0.039379  0.047195
                 3       1        2            0.024985  0.022839  0.028854
                 4       1        2            0.191913  0.172094  0.215683
                 5       1        2            0.048853  0.045471  0.060919
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.192470  0.139262  0.145298
                 7       2        15           0.619737  0.471813  0.486686
                         3        15           0.418859  0.307637  0.319909
                 8       2        15           0.737675  0.558485  0.593760
                         3        15           0.497354  0.365914  0.381189

                                                     10        11        12  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.036338  0.029644  0.029764
                 2       1        1            0.056855  0.056177  0.053397
                 3       1        2            0.034872  0.030451  0.035693
                 4       1        2            0.252671  0.244490  0.233538
                 5       1        2            0.072426  0.065917  0.064347
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.166717  0.187901  0.138746
                 7       2        15           0.562528  0.576935  0.454883
                         3        15           0.363129  0.390114  0.297195
                 8       2        15           0.673347  0.698433  0.540324
                         3        15           0.431382  0.482425  0.318520

                                                     13        14        15  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.049293  0.032254  0.030055
                 2       1        1            0.070968  0.060264  0.060580
                 3       1        2            0.038334  0.033750  0.033101
                 4       1        2            0.325651  0.258862  0.276551
                 5       1        2            0.086187  0.073228  0.073460
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.157592  0.182304  0.176421
                 7       2        15           0.520116  0.530565  0.584408
                         3        15           0.342113  0.349512  0.382232
                 8       2        15           0.560358  0.714369  0.693121
                         3        15           0.406929  0.472960  0.453009

                                                     16        17        18  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.031605  0.022620  0.022265
                 2       1        1            0.052636  0.037829  0.036420
                 3       1        2            0.021661  0.024822  0.026800
                 4       1        2            0.235306  0.179406  0.173384
                 5       1        2            0.065068  0.050138  0.045107
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.219683  0.153960  0.126949
                 7       2        15           0.695135  0.499272  0.411482
                         3        15           0.462217  0.334332  0.271362
                 8       2        15           0.846628  0.599091  0.427562
                         3        15           0.580419  0.390083  0.312567

                                                     19        20
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.032650  0.047289
                 2       1        1            0.052326  0.077026
                 3       1        2            0.027005  0.041723
                 4       1        2            0.238100  0.309877
                 5       1        2            0.062817  0.083678
...                                                 ...       ...
8 6   4   5      6       3        15           0.152679  0.136877
                 7       2        15           0.531050  0.454089
                         3        15           0.347176  0.278561
                 8       2        15           0.626486  0.540531
                         3        15           0.389860  0.355910

[5696 rows x 20 columns]

In [14]:
HBProd.trip_rates_path

WindowsPath('C:/Users/Spiral/Documents/Thomas Prince/(normitsefs) Transfer/TP_20250128-copy/tem_inputs/hb_trip_rates_production_dvector.dvec')

In [12]:
pure_production.data

normits_id                                      7294002     7300001  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.313249    9.580920
                 2       1        1            0.151105    9.728457
                 3       1        2            1.080462   30.511476
                 4       1        2            7.076441  359.556767
                 5       1        2            0.494937   23.445386
...                                                 ...         ...
8 6   4   5      6       3        15           0.095401    8.037112
                 7       2        15           0.026242    4.401600
                         3        15           0.019513    2.809774
                 8       2        15           0.016972    1.887854
                         3        15           0.011470    1.134887

normits_id                                        7305004     7306005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             13.615169    7.657227
                 2       1        1             10.901597    9.865916
                 3       1        2             37.044660   21.851379
                 4       1        2            374.712877  393.115294
                 5       1        2              9.619440   21.633907
...                                                   ...         ...
8 6   4   5      6       3        15             1.694288    6.085480
                 7       2        15             1.728158    4.351812
                         3        15             1.238918    3.006858
                 8       2        15             0.587040    2.033811
                         3        15             0.480968    1.023472

normits_id                                        7307006     7312002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              9.339888   11.862930
                 2       1        1             13.635719    9.680031
                 3       1        2             24.428142   27.475625
                 4       1        2            489.146671  299.604341
                 5       1        2             29.701615   10.512776
...                                                   ...         ...
8 6   4   5      6       3        15             1.774001    5.430465
                 7       2        15             2.558564    3.564083
                         3        15             1.696127    2.161217
                 8       2        15             1.195858    1.421234
                         3        15             0.863464    0.860006

normits_id                                        7313003     7315005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              5.669655   12.405102
                 2       1        1              8.060367   17.505798
                 3       1        2             18.627661   25.705002
                 4       1        2            243.573021  486.842302
                 5       1        2             24.269095   24.810451
...                                                   ...         ...
8 6   4   5      6       3        15             4.370449    2.593577
                 7       2        15             3.885543    2.198381
                         3        15             2.369484    1.696777
                 8       2        15             2.761352    0.999852
                         3        15             1.310707    0.659768

normits_id                                        7316006     7318008  ...  \
p aws soc ns_sec hh_type gender_3 adult_nssec                          ...
1 1   4   1      1       1        1             12.702372    8.911514  ...
                 2       1        1             23.320755   11.251901  ...
                 3       1        2             26.471989   27.984913  ...
                 4       1        2            646.968469  361.196607  ...
                 5       1        2             36.628288   17.867437  ...
...                                                   ...         ...  ...
8 6   4   5      6       3        15             2.972614    4.114171  ...
                 7       2        15             3.965451    6.404432  ...
                         3        15             2.716394    4.995465  ...
                 8       2        15             2.125822    2.998513  ...
                         3        15             1.357996    2.380013  ...

normits_id                                       6255001    6255002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.054578   0.236815
                 2       1        1             1.309479   3.046713
                 3       1        2             0.147817   0.337238
                 4       1        2            23.412928  40.197876
                 5       1        2            26.715225  30.700061
...                                                  ...        ...
8 6   4   5      6       3        15            0.038061   0.038168
                 7       2        15            0.034807   0.040111
                         3        15            0.032652   0.021814
                 8       2        15            0.062286   0.102891
                         3        15            0.049232   0.056713

normits_id                                       6255005     6255006  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.238060    2.252650
                 2       1        1             1.599194   10.089501
                 3       1        2             0.196724    2.989700
                 4       1        2            22.259417  165.238644
                 5       1        2            11.622010   62.463525
...                                                  ...         ...
8 6   4   5      6       3        15            0.189353    2.210982
                 7       2        15            0.289403    1.681657
                         3        15            0.153220    1.300795
                 8       2        15            0.302689    1.359804
                         3        15            0.159754    1.141283

normits_id                                        6255007    6256002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              3.673018   0.263692
                 2       1        1             21.038480   4.806764
                 3       1        2              3.145661   0.122506
                 4       1        2            341.060562  80.680369
                 5       1        2            137.787136  52.272639
...                                                   ...        ...
8 6   4   5      6       3        15             0.280794   0.010708
                 7       2        15             0.536038   0.017950
                         3        15             0.379264   0.027166
                 8       2        15             0.611441   0.028445
                         3        15             0.408374   0.022127

normits_id                                       6256006     6256009  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.254156    3.032856
                 2       1        1             3.173634   24.247488
                 3       1        2             0.252875    3.198995
                 4       1        2            51.729753  380.454820
                 5       1        2            30.613523  158.623127
...                                                  ...         ...
8 6   4   5      6       3        15            0.001879    0.044729
                 7       2        15            0.012211    0.104724
                         3        15            0.012766    0.079433
                 8       2        15            0.017760    0.121347
                         3        15            0.018002    0.078842

normits_id                                        6256010     6257001
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              1.275689    6.532106
                 2       1        1             14.725667   30.193443
                 3       1        2              1.765148    7.907665
                 4       1        2            291.720822  402.116212
                 5       1        2            105.806366  194.403722
...                                                   ...         ...
8 6   4   5      6       3        15             0.029889    0.221753
                 7       2        15             0.030839    0.719602
                         3        15             0.027393    0.445577
                 8       2        15             0.033454    0.519208
                         3        15             0.028675    0.327299

[5696 rows x 5430 columns]

In [10]:
p4 = cb.DVector.load(r"T:\ThomasPrince\hb_attraction_triprates_p4.dvec")

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [22]:
p4.data

tfn_at,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
sic_2_digit,,,,,,,,,,,,,,,,,,,,
46,23.294713,32.70374,28.296696,36.35762,29.592681,32.171902,31.051995,33.906039,27.28857,29.461202,31.024163,26.231325,30.400461,30.253732,32.195774,48.218435,28.655813,37.954698,25.848563,36.513429
47,23.294713,32.70374,28.296696,36.35762,29.592681,32.171902,31.051995,33.906039,27.28857,29.461202,31.024163,26.231325,30.400461,30.253732,32.195774,48.218435,28.655813,37.954698,25.848563,36.513429

In [23]:
no_zone = p4.remove_zoning()#.data#.translate_zoning(cb.ZoningSystem.get_zoning("gb"))

In [25]:
no_zone.data

sic_2_digit
46    631.421552
47    631.421552
Name: val, dtype: object

In [27]:
(p4 * no_zone).data

tfn_at,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
sic_2_digit,,,,,,,,,,,,,,,,,,,,
46,14708.783793,20649.846567,17867.143744,22956.984892,18685.45671,20314.032107,19606.899037,21409.003765,17230.59104,18602.438004,19589.325121,16563.023851,19195.506406,19102.858421,20329.105563,30446.158782,18093.897647,23965.41453,16321.340036,23055.366154
47,14708.783793,20649.846567,17867.143744,22956.984892,18685.45671,20314.032107,19606.899037,21409.003765,17230.59104,18602.438004,19589.325121,16563.023851,19195.506406,19102.858421,20329.105563,30446.158782,18093.897647,23965.41453,16321.340036,23055.366154

In [18]:
#.translate_zoning(cb.ZoningSystem.get_zoning("lsoa_2021"))

ValueError: Cannot translate the zoning system of a DVector that does not have a zoning system to begin with.

In [9]:
cb.segmentation.SegmentsSuper("soc").get_segment()

Segment(name='soc', values={1: 'SOC1', 2: 'SOC2', 3: 'SOC3', 4: 'SOC4'}, alias=None, exclusions=[Exclusion(other_name='economic_status', exclusions={1: {2, 4, 5, 6, -8}, 2: {2, 4, 5, 6, -8}, 3: {2, 4, 5, 6, -8}, 4: {1, 3}}), Exclusion(other_name='aws', exclusions={1: {1, 4, 5, 6}, 2: {1, 4, 5, 6}, 3: {1, 4, 5, 6}, 4: {2, 3}}), Exclusion(other_name='adult_nssec', exclusions={1: {10}, 2: {10}, 3: {1, 10}})], lookups=[])

In [52]:
p4 = p4.add_segments([cb.segmentation.SegmentsSuper("total").get_segment()], split_method="split")

In [53]:
p4_ = p4.aggregate(["total"]).add_segments(["soc"], split_method="split")#.data

In [54]:
p4.data

,tfn_at,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
sic_2_digit,total,,,,,,,,,,,,,,,,,,,,
46,1,23.294713,32.70374,28.296696,36.35762,29.592681,32.171902,31.051995,33.906039,27.28857,29.461202,31.024163,26.231325,30.400461,30.253732,32.195774,48.218435,28.655813,37.954698,25.848563,36.513429
47,1,23.294713,32.70374,28.296696,36.35762,29.592681,32.171902,31.051995,33.906039,27.28857,29.461202,31.024163,26.231325,30.400461,30.253732,32.195774,48.218435,28.655813,37.954698,25.848563,36.513429

In [55]:
p4_.data

tfn_at            1         2          3         4          5          6   \
total soc
1     1    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951
      2    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951
      3    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951
      4    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951

tfn_at            7         8          9          10         11         12  \
total soc
1     1    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662
      2    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662
      3    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662
      4    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662

tfn_at            13         14         15         16         17         18  \
total soc
1     1    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349
      2    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349
      3    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349
      4    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349

tfn_at            19         20
total soc
1     1    12.924282  18.256715
      2    12.924282  18.256715
      3    12.924282  18.256715
      4    12.924282  18.256715

In [58]:
(p4_+p4).data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['total', 'soc'] to ['total', 'soc', 'sic_2_digit']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:947: UserWarning: This operation has dropped some rows due to exclusions in the resulting segmentation. MultiIndex([(1, 4, 46),
            (1, 4, 47)],
           names=['total', 'soc', 'sic_2_digit']) rows have been dropped from the pure product.
  warnings.warn(

tfn_at                        1          2          3         4          5   \
total soc sic_2_digit
1     1   46           34.942069  49.055611  42.445044  54.53643  44.389022
          47           34.942069  49.055611  42.445044  54.53643  44.389022
      2   46           34.942069  49.055611  42.445044  54.53643  44.389022
          47           34.942069  49.055611  42.445044  54.53643  44.389022
      3   46           34.942069  49.055611  42.445044  54.53643  44.389022
          47           34.942069  49.055611  42.445044  54.53643  44.389022

tfn_at                        6          7          8          9          10  \
total soc sic_2_digit
1     1   46           48.257853  46.577993  50.859059  40.932855  44.191803
          47           48.257853  46.577993  50.859059  40.932855  44.191803
      2   46           48.257853  46.577993  50.859059  40.932855  44.191803
          47           48.257853  46.577993  50.859059  40.932855  44.191803
      3   46           48.257853  46.577993  50.859059  40.932855  44.191803
          47           48.257853  46.577993  50.859059  40.932855  44.191803

tfn_at                        11         12         13         14         15  \
total soc sic_2_digit
1     1   46           46.536244  39.346987  45.600692  45.380598  48.293661
          47           46.536244  39.346987  45.600692  45.380598  48.293661
      2   46           46.536244  39.346987  45.600692  45.380598  48.293661
          47           46.536244  39.346987  45.600692  45.380598  48.293661
      3   46           46.536244  39.346987  45.600692  45.380598  48.293661
          47           46.536244  39.346987  45.600692  45.380598  48.293661

tfn_at                        16         17         18         19         20
total soc sic_2_digit
1     1   46           72.327652  42.983719  56.932048  38.772845  54.770144
          47           72.327652  42.983719  56.932048  38.772845  54.770144
      2   46           72.327652  42.983719  56.932048  38.772845  54.770144
          47           72.327652  42.983719  56.932048  38.772845  54.770144
      3   46           72.327652  42.983719  56.932048  38.772845  54.770144
          47           72.327652  42.983719  56.932048  38.772845  54.770144

In [25]:
import pandas as pd
soc = pd.Series(data = [1], name="soc", index = ["sic_2_digit"])

In [14]:
p4_.data

tfn_at                 1          2         3          4         5   \
sic_2_digit soc
46          1    7.764904  10.901247  9.432232  12.119207  9.864227
            2    7.764904  10.901247  9.432232  12.119207  9.864227
            3    7.764904  10.901247  9.432232  12.119207  9.864227
47          1    7.764904  10.901247  9.432232  12.119207  9.864227
            2    7.764904  10.901247  9.432232  12.119207  9.864227
            3    7.764904  10.901247  9.432232  12.119207  9.864227

tfn_at                  6          7          8        9         10  \
sic_2_digit soc
46          1    10.723967  10.350665  11.302013  9.09619  9.820401
            2    10.723967  10.350665  11.302013  9.09619  9.820401
            3    10.723967  10.350665  11.302013  9.09619  9.820401
47          1    10.723967  10.350665  11.302013  9.09619  9.820401
            2    10.723967  10.350665  11.302013  9.09619  9.820401
            3    10.723967  10.350665  11.302013  9.09619  9.820401

tfn_at                  11        12         13         14         15  \
sic_2_digit soc
46          1    10.341388  8.743775  10.133487  10.084577  10.731925
            2    10.341388  8.743775  10.133487  10.084577  10.731925
            3    10.341388  8.743775  10.133487  10.084577  10.731925
47          1    10.341388  8.743775  10.133487  10.084577  10.731925
            2    10.341388  8.743775  10.133487  10.084577  10.731925
            3    10.341388  8.743775  10.133487  10.084577  10.731925

tfn_at                  16        17         18        19         20
sic_2_digit soc
46          1    16.072812  9.551938  12.651566  8.616188  12.171143
            2    16.072812  9.551938  12.651566  8.616188  12.171143
            3    16.072812  9.551938  12.651566  8.616188  12.171143
47          1    16.072812  9.551938  12.651566  8.616188  12.171143
            2    16.072812  9.551938  12.651566  8.616188  12.171143
            3    16.072812  9.551938  12.651566  8.616188  12.171143

In [51]:
p4_.add_segments([cb.segmentation.SegmentsSuper("soc").get_segment()], None, "split", None).data

tfn_at            1         2          3         4          5          6   \
total soc
1     1    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951
      2    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951
      3    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951
      4    11.647356  16.35187  14.148348  18.17881  14.796341  16.085951

tfn_at            7         8          9          10         11         12  \
total soc
1     1    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662
      2    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662
      3    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662
      4    15.525998  16.95302  13.644285  14.730601  15.512081  13.115662

tfn_at            13         14         15         16         17         18  \
total soc
1     1    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349
      2    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349
      3    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349
      4    15.200231  15.126866  16.097887  24.109217  14.327906  18.977349

tfn_at            19         20
total soc
1     1    12.924282  18.256715
      2    12.924282  18.256715
      3    12.924282  18.256715
      4    12.924282  18.256715

In [ ]:
# employment data to sub categories

In [53]:
emp = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Land Use\employment\Output E6 - lsoa_2021.hdf")

In [58]:
emp.translate_zoning(cb.ZoningSystem.get_zoning("normits")).aggregate(["soc", "sic_2_digit"]).data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:554: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  translation[zone_system.column_name].replace(to_replace=replacer, inplace=True)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 46 lsoa_2021 zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 4.4e-16
  warnings.warn(

normits_id           1001001       1001002       1001003       1001004   \
soc sic_2_digit
1    1           5.857798e-01  5.088519e-01  5.307486e-01  4.962361e-01
     2           1.421971e-12  8.832828e-13  8.835070e-13  1.762762e+00
     3           1.963556e+00  8.832828e-13  8.835070e-13  1.104937e-12
     5           0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     6           0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
...                       ...           ...           ...           ...
3    96          0.000000e+00  0.000000e+00  1.157179e+01  2.030663e+00
     97          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     98          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     99          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
4   -1           1.989263e+01  2.836456e+01  2.317996e+02  4.414011e+01

normits_id           1001005       1001006       1001007       1001008   \
soc sic_2_digit
1    1           6.562981e-01  1.270006e+00  3.407574e+00  4.354846e-01
     2           7.066262e-13  7.066262e-13  7.120155e-13  8.832827e-13
     3           7.066262e-13  7.066262e-13  7.120155e-13  8.832827e-13
     5           0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     6           0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
...                       ...           ...           ...           ...
3    96          0.000000e+00  2.627917e+00  1.274142e+00  1.023864e+00
     97          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     98          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     99          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
4   -1           1.701372e+01  6.655938e+01  9.796372e+01  1.025375e+01

normits_id           1001009       1001010   ...      11357010      11358001  \
soc sic_2_digit                              ...
1    1           1.622882e+01  8.480324e-01  ...  1.511062e+00  2.948891e-01
     2           1.236662e-12  1.237499e-12  ...  5.728814e-12  1.977257e+00
     3           1.236662e-12  1.237499e-12  ...  5.728814e-12  3.057242e-13
     5           0.000000e+00  1.452391e-12  ...  0.000000e+00  0.000000e+00
     6           0.000000e+00  1.452391e-12  ...  0.000000e+00  0.000000e+00
...                       ...           ...  ...           ...           ...
3    96          3.344622e+00  7.167047e+00  ...  8.522297e+00  1.807969e+00
     97          0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
     98          0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
     99          0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00
4   -1           6.385066e+01  1.821023e+02  ...  1.598884e+02  2.108327e+01

normits_id           11358002      11358003      11358004      11358005  \
soc sic_2_digit
1    1           1.015162e+00  2.060244e+00  8.236694e-01  3.026391e+00
     2           2.469551e-11  1.975857e+00  1.145681e-11  1.460008e-11
     3           2.469551e-11  2.380079e-11  1.145681e-11  1.460008e-11
     5           0.000000e+00  9.312443e-13  0.000000e+00  0.000000e+00
     6           0.000000e+00  9.312443e-13  0.000000e+00  0.000000e+00
...                       ...           ...           ...           ...
3    96          4.498862e+01  2.518830e+01  1.067563e+01  9.642504e+00
     97          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     98          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
     99          0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
4   -1           1.185350e+03  1.027593e+03  6.963765e+02  5.032748e+02

normits_id          11358006      11358007      11358008      11358009
soc sic_2_digit
1    1              0.706959  2.781152e+00  9.524405e-01  1.174759e+00
     2              3.951005  2.371560e-11  1.186859e-11  1.975702e+00
     3              3.951163  1.975804e+00  1.975733e+00  1.836210e-11
     5              0.000000  0.000000e+00  0.000000e+00  0.000000e+00
     6              0.000000  0.000000e+00  0.000000e+00  0.000000e+00
...                      ...           ...           ...           ...
3    96           136.908107  3.280962e+01  1.265579e+01  3.741044e+01
     97             0.000000  0.000000e+00  0.000000e+00  0.000000e+00
     98             0.000000  0.000000e+00  0.000000e+00  0.000000e+00
     99             0.000000  0.000000e+00  0.000000e+00  0.000000e+00
4   -1           6376.071524  6.324844e+02  3.519201e+02  2.097439e+03

[265 rows x 5430 columns]

In [60]:
emp.translate_zoning(cb.ZoningSystem.get_zoning("lsoa_2021"))

In [66]:
temp = emp.data.reset_index()

In [68]:
temp.loc[temp["sic_2_digit"].isin([46,47])]

,sic_1_digit,soc,sic_2_digit,sic_4_digit,E01000001,E01000002,E01000003,E01000005,E01000006,E01000007,...,W01002031,W01002032,W01002033,W01002034,W01002035,W01002036,W01002037,W01002038,W01002039,W01002040
979,7,1,46,331,2.134082e-13,3.119931e-13,6.033897e-14,1.670740e-13,3.813673e-14,2.181377e-13,...,7.467900e-14,7.951652e-13,7.945061e-13,3.672591e-15,3.672591e-15,1.572840e-12,1.572840e-12,6.693235e-14,6.673009e-14,3.566034e-12
980,7,1,46,332,1.440742e+00,3.704765e+00,1.852382e-01,1.646562e+00,1.548783e-03,1.209663e-02,...,9.525552e-04,7.364347e-02,4.647663e-01,1.501865e-04,5.990723e-05,1.845469e-02,1.350048e-02,7.061878e-03,1.310378e-03,7.332635e-02
981,7,1,46,333,9.604946e-02,2.469843e-01,1.234922e-02,1.097708e-01,7.743913e-04,6.048316e-03,...,4.762776e-03,3.682173e-01,2.323831e+00,7.509326e-04,2.995361e-04,1.845469e-02,1.350048e-02,7.061878e-03,1.310378e-03,7.332635e-02
982,7,1,46,334,7.203709e-01,1.852382e+00,9.261912e-02,8.232811e-01,7.743913e-04,6.048316e-03,...,3.333943e-03,2.577521e-01,1.626682e+00,5.256528e-04,2.096753e-04,1.572840e-12,1.572840e-12,6.693235e-14,6.673009e-14,3.566034e-12
983,7,1,46,335,1.920989e-01,4.939686e-01,2.469843e-02,2.195416e-01,7.743913e-04,6.048316e-03,...,1.905110e-03,1.472869e-01,9.295326e-01,3.003730e-04,1.198145e-04,2.768204e-02,2.025072e-02,1.059282e-02,1.965566e-03,1.099895e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,7,3,47,411,8.883210e-14,1.298685e-13,2.511636e-14,6.954530e-14,3.030607e-03,3.313842e-02,...,6.922801e-03,3.902588e-02,2.462936e-01,9.550600e-04,3.809596e-04,4.031638e-12,4.031638e-12,1.072292e-13,1.069052e-13,2.539101e-12
1242,7,3,47,412,8.883210e-14,1.298685e-13,2.511636e-14,6.954530e-14,1.010202e-03,1.104614e-02,...,5.427379e-13,4.213818e-13,4.210326e-13,2.335459e-14,2.335459e-14,4.031638e-12,4.031638e-12,1.072292e-13,1.069052e-13,2.539101e-12
1243,7,3,47,413,3.998101e-02,1.028083e-01,5.140416e-03,4.569258e-02,2.020405e-03,2.209228e-02,...,5.427379e-13,4.213818e-13,4.210326e-13,2.335459e-14,2.335459e-14,4.031638e-12,4.031638e-12,1.072292e-13,1.069052e-13,2.539101e-12
1244,7,3,47,414,3.998101e+00,1.028083e+01,5.140416e-01,4.569258e+00,5.051012e-02,5.523069e-01,...,5.192100e-02,2.926941e-01,1.847202e+00,7.162950e-03,2.857197e-03,3.547848e-01,2.595419e-01,8.485129e-02,1.574471e-02,3.915757e-01
1245,7,3,47,415,1.599240e-01,4.112333e-01,2.056166e-02,1.827703e-01,8.081619e-03,8.836911e-02,...,3.461400e-02,1.951294e-01,1.231468e+00,4.775300e-03,1.904798e-03,2.365232e-01,1.730279e-01,5.656753e-02,1.049647e-02,2.610505e-01

In [54]:
p4.data

tfn_at,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
sic_2_digit,,,,,,,,,,,,,,,,,,,,
46,23.294713,32.70374,28.296696,36.35762,29.592681,32.171902,31.051995,33.906039,27.28857,29.461202,31.024163,26.231325,30.400461,30.253732,32.195774,48.218435,28.655813,37.954698,25.848563,36.513429
47,23.294713,32.70374,28.296696,36.35762,29.592681,32.171902,31.051995,33.906039,27.28857,29.461202,31.024163,26.231325,30.400461,30.253732,32.195774,48.218435,28.655813,37.954698,25.848563,36.513429

In [5]:
HBattr.run()

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level m is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level tp is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['tp', 'soc', 'sic_4_digit', 'p', 'sic_2_digit', 'sic_1_digit', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['tp', 'soc', 'sic_4_digit', 'p', 'sic_2_digit', 'sic_1_digit', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['tp', 'soc', 'sic_4_digit', 'p', 'sic_2_digit', 'sic_1_digit', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['tp', 'soc', 'sic_4_digit', 'p', 'sic_2_digit', 'sic_1_digit', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['tp', 'soc', 'sic_4_digit', 'p', 'sic_2_digit', 'sic_1_digit', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['tp', 'soc', 'sic_4_digit', 'p', 'sic_2_digit', 'sic_1_digit', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['tp', 'soc', 'sic_4_digit', 'p', 'sic_2_digit', 'sic_1_digit', 'm']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:516: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->integer,key->axis0] [items->None]

  self._data.to_hdf(out_path, key="data", mode="w", complevel=1)
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:516: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->integer,key->block0_items] [items->None]

  self._data.to_hdf(out_path, key="data", mode="w", complevel=1)

In [13]:
test = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_v2\Core\hb_attractions\hb_normits_tem_segmented_2023_dvec.h5")

In [14]:
test2 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_v4\Core\hb_attractions\hb_normits_tem_segmented_2023_dvec.h5")

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [22]:
test2.data#.sum(axis=1)

normits_id     1001001       1001002       1001003      1001004   \
soc p
1   1        852.103194  1.383845e+03  9.029776e+03  1532.813203
    2        108.527762  1.762529e+02  1.150074e+03   195.226104
    3       1037.502071  2.075004e+03  3.683132e+03   207.500414
    4        482.610710  9.342953e+02  1.658700e+04   572.361939
    5        207.447924  2.024327e+02  2.475988e+03   639.991412
    6        504.164261  5.041643e+02  3.769416e+03  1591.268448
    8        277.781476  4.195158e-10  3.306808e-10   249.375431
2   1        943.394273  1.228516e+03  1.130042e+04  1716.978869
    2         78.391973  1.020844e+02  9.390157e+02   142.673498
    3       1037.502071  2.075004e+03  3.683132e+03   207.500414
    4        482.610710  9.342953e+02  1.658700e+04   572.361939
    5        207.447924  2.024327e+02  2.475988e+03   639.991412
    6        504.164261  5.041643e+02  3.769416e+03  1591.268448
    8        277.781476  4.195158e-10  3.306808e-10   249.375431
3   1        552.518393  6.979087e+02  7.289454e+03  2156.183764
    2         34.483001  4.355690e+01  4.549392e+02   134.568711
    3       1037.502071  2.075004e+03  3.683132e+03   207.500414
    4        482.610710  9.342953e+02  1.658700e+04   572.361939
    5        207.447924  2.024327e+02  2.475988e+03   639.991412
    6        504.164261  5.041643e+02  3.769416e+03  1591.268448
    8        277.781476  4.195158e-10  3.306808e-10   249.375431
4   1        116.714960  1.664219e+02  1.360025e+03   258.980923
    2         17.490968  2.494007e+01  2.038141e+02    38.811024
    3       1037.502071  2.075004e+03  3.683132e+03   207.500414
    4        482.610710  9.342953e+02  1.658700e+04   572.361939
    5        207.447924  2.024327e+02  2.475988e+03   639.991412
    6        504.164261  5.041643e+02  3.769416e+03  1591.268448
    8        277.781476  4.195158e-10  3.306808e-10   249.375431

normits_id      1001005       1001006      1001007       1001008   \
soc p
1   1       9.897008e+02  2.586072e+03  3497.338760  4.264845e+02
    2       1.260528e+02  3.293740e+02   445.437070  5.431902e+01
    3       2.075004e+03  1.193127e+03   415.000828  4.668759e+02
    4       3.479211e+02  7.526326e+02  2527.805845  6.144538e+02
    5       4.787260e+01  5.063154e+02   375.247831  1.377628e+02
    6       5.041643e+02  1.701554e+03  3319.081384  8.642816e+02
    8       3.047003e-10  3.317774e-10  1328.203302  3.512122e-10
2   1       6.455833e+02  2.934759e+03  4709.603190  5.272225e+02
    2       5.364517e+01  2.438658e+02   391.347602  4.380990e+01
    3       2.075004e+03  1.193127e+03   415.000828  4.668759e+02
    4       3.479211e+02  7.526326e+02  2527.805845  6.144538e+02
    5       4.787260e+01  5.063154e+02   375.247831  1.377628e+02
    6       5.041643e+02  1.701554e+03  3319.081384  8.642816e+02
    8       3.047003e-10  3.317774e-10  1328.203302  3.512122e-10
3   1       3.110961e+02  2.469955e+03  3590.250291  2.534577e+02
    2       1.941569e+01  1.541513e+02   224.069655  1.581845e+01
    3       2.075004e+03  1.193127e+03   415.000828  4.668759e+02
    4       3.479211e+02  7.526326e+02  2527.805845  6.144538e+02
    5       4.787260e+01  5.063154e+02   375.247831  1.377628e+02
    6       5.041643e+02  1.701554e+03  3319.081384  8.642816e+02
    8       3.047003e-10  3.317774e-10  1328.203302  3.512122e-10
4   1       9.982372e+01  3.905203e+02   574.777274  6.016128e+01
    2       1.495964e+01  5.852359e+01    86.136439  9.015802e+00
    3       2.075004e+03  1.193127e+03   415.000828  4.668759e+02
    4       3.479211e+02  7.526326e+02  2527.805845  6.144538e+02
    5       4.787260e+01  5.063154e+02   375.247831  1.377628e+02
    6       5.041643e+02  1.701554e+03  3319.081384  8.642816e+02
    8       3.047003e-10  3.317774e-10  1328.203302  3.512122e-10

normits_id     1001009       1001010   ...      11357010      11358001  \
soc p                                  ...
1   1       2842.038697   7326.300462  ...  7.390096e+03  7.729421e+02
    2        361.975055    933.111156  ...  8.251028e+02  1.806559e+02
    3       1893.441280   2697.505385  ...  4.475574e+03  2.857037e+02
    4          0.000000  11032.497115  ...  9.419249e+03  2.323523e+02
    5        714.170549   2077.082633  ...  1.413839e+03  2.687006e+02
    6       1386.451717   5797.889000  ...  3.561712e+03  3.733019e-11
    8        465.336492   3253.200655  ...  3.426543e-10  1.586958e+02
2   1       2923.190777   9221.621574  ...  7.961530e+03  9.589322e+02
    2        242.904477    766.276763  ...  5.577107e+02  1.387654e+02
    3       1893.441280   2697.505385  ...  4.475574e+03  2.857037e+02
    4          0.000000  11032.497115  ...  9.419249e+03  2.323523e+02
    5        714.170549   2077.082633  ...  1.413839e+03  2.687006e+02
    6       1386.451717   5797.889000  ...  3.561712e+03  3.733019e-11
    8        465.336492   3253.200655  ...  3.426543e-10  1.586958e+02
3   1       1753.202449   5004.372786  ...  4.155794e+03  8.339437e+02
    2        109.418407    312.325881  ...  2.341132e+02  3.737367e+01
    3       1893.441280   2697.505385  ...  4.475574e+03  2.857037e+02
    4          0.000000  11032.497115  ...  9.419249e+03  2.323523e+02
    5        714.170549   2077.082633  ...  1.413839e+03  2.687006e+02
    6       1386.451717   5797.889000  ...  3.561712e+03  3.733019e-11
    8        465.336492   3253.200655  ...  3.426543e-10  1.586958e+02
4   1        374.627575   1068.438926  ...  8.467486e+02  1.261088e+02
    2         56.141894    160.116845  ...  1.173283e+02  1.296587e+01
    3       1893.441280   2697.505385  ...  4.475574e+03  2.857037e+02
    4          0.000000  11032.497115  ...  9.419249e+03  2.323523e+02
    5        714.170549   2077.082633  ...  1.413839e+03  2.687006e+02
    6       1386.451717   5797.889000  ...  3.561712e+03  3.733019e-11
    8        465.336492   3253.200655  ...  3.426543e-10  1.586958e+02

normits_id      11358002      11358003      11358004      11358005  \
soc p
1   1       58859.948953  42283.525697  2.786135e+04  24538.694566
    2        6571.702148   4720.947632  3.110715e+03   2739.740599
    3       49610.023605  13976.308734  7.798545e+03   9419.327399
    4       33459.057897  51644.427524  3.590326e+04  17306.698985
    5       25775.048597   7129.096380  7.924265e+03   4259.147644
    6       19388.510506  13883.568294  7.051896e+03   9727.009530
    8        1070.308931    351.850876  6.714183e-10    492.338533
2   1       54632.519658  52293.773093  3.413705e+04  23350.960702
    2        3827.045919   3663.215099  2.391324e+03   1635.751003
    3       49610.023605  13976.308734  7.798545e+03   9419.327399
    4       33459.057897  51644.427524  3.590326e+04  17306.698985
    5       25775.048597   7129.096380  7.924265e+03   4259.147644
    6       19388.510506  13883.568294  7.051896e+03   9727.009530
    8        1070.308931    351.850876  6.714183e-10    492.338533
3   1       30419.153792  32455.656383  2.458825e+04  13346.524421
    2        1713.637971   1828.362667  1.385159e+03    751.865459
    3       49610.023605  13976.308734  7.798545e+03   9419.327399
    4       33459.057897  51644.427524  3.590326e+04  17306.698985
    5       25775.048597   7129.096380  7.924265e+03   4259.147644
    6       19388.510506  13883.568294  7.051896e+03   9727.009530
    8        1070.308931    351.850876  6.714183e-10    492.338533
4   1        6277.463733   5442.002459  3.687922e+03   2665.279787
    2         869.826269    754.061974  5.110107e+02    369.310039
    3       49610.023605  13976.308734  7.798545e+03   9419.327399
    4       33459.057897  51644.427524  3.590326e+04  17306.698985
    5       25775.048597   7129.096380  7.924265e+03   4259.147644
    6       19388.510506  13883.568294  7.051896e+03   9727.009530
    8        1070.308931    351.850876  6.714183e-10    492.338533

normits_id       11358006      11358007      11358008       11358009
soc p
1   1       336695.378552  27768.280818  14808.843564   95015.244974
    2        37591.975220   3100.323292   1653.404578   10608.434098
    3        69858.054073  13764.902383   4791.877280   15197.767648
    4       127003.876264  27880.092046  33303.457856   50956.082540
    5        66298.258224   7588.380409   4597.391223   50990.928891
    6       108443.291556  15402.832293   8426.607187   39046.283276
    8        17733.188550    158.900437    256.547754    2191.947268
2   1       274213.973004  29911.565812  18882.597260  101928.248752
    2        19208.879121   2095.325945   1322.739043    7140.144566
    3        69858.054073  13764.902383   4791.877280   15197.767648
    4       127003.876264  27880.092046  33303.457856   50956.082540
    5        66298.258224   7588.380409   4597.391223   50990.928891
    6       108443.291556  15402.832293   8426.607187   39046.283276
    8        17733.188550    158.900437    256.547754    2191.947268
3   1       159370.400313  20272.132124   9534.179307   60062.701959
    2         8978.000221   1142.013864    537.100138    3383.582838
    3        69858.054073  13764.902383   4791.877280   15197.767648
    4       127003.876264  27880.092046  33303.457856   50956.082540
    5        66298.258224   7588.380409   4597.391223   50990.928891
    6       108443.291556  15402.832293   8426.607187   39046.283276
    8        17733.188550    158.900437    256.547754    2191.947268
4   1        33766.867833   3349.557217   1863.724308   11107.772819
    2         4678.849599    464.125797    258.243844    1539.129974
    3        69858.054073  13764.902383   4791.877280   15197.767648
    4       127003.876264  27880.092046  33303.457856   50956.082540
    5        66298.258224   7588.380409   4597.391223   50990.928891
    6       108443.291556  15402.832293   8426.607187   39046.283276
    8        17733.188550    158.900437    256.547754    2191.947268

[28 rows x 5430 columns]

In [18]:
test.sum()

np.float64(511571590.8873227)

In [11]:
test2 = test.aggregate(["soc", "p", "m", "tp"])

In [31]:
check = test2.data

In [30]:
cb.segmentation.SegmentsSuper("p").get_segment()

Segment(name='p', values={1: 'HB Work', 2: 'HB Employers Business (EB)', 3: 'HB Education', 4: 'HB Shopping', 5: 'HB Personal Business (PB)', 6: 'HB Recreation / Social', 7: 'HB Visiting friends and relatives', 8: 'HB Holiday / Day trip', 11: 'NHB Work', 12: 'NHB Employers Business (EB)', 13: 'NHB Education', 14: 'NHB Shopping', 15: 'NHB Personal Business (PB)', 16: 'NHB Recreation / Social', 18: 'NHB Holiday / Day trip'}, alias=None, exclusions=[], lookups=[])

In [43]:
check.index==(1*)#[1]

SyntaxError: invalid syntax (1137006946.py, line 1)

In [ ]:
#check = check.reset_index()
check.loc[(check["soc"]==4) & (check["p"]==1)]#.sum()#.unique()

,soc,p,m,tp,1001001,1001002,1001003,1001004,1001005,1001006,...,11357010,11358001,11358002,11358003,11358004,11358005,11358006,11358007,11358008,11358009
1008,4,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1009,4,4,1,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1010,4,4,1,3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1011,4,4,1,4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1012,4,4,1,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1013,4,4,1,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1014,4,4,2,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1015,4,4,2,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1016,4,4,2,3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1017,4,4,2,4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1018,4,4,2,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1019,4,4,2,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1020,4,4,3,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1021,4,4,3,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1022,4,4,3,3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1023,4,4,3,4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1024,4,4,3,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1025,4,4,3,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1026,4,4,4,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1027,4,4,4,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1028,4,4,4,3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1029,4,4,4,4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1030,4,4,4,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1031,4,4,4,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1032,4,4,5,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1033,4,4,5,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1034,4,4,5,3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1035,4,4,5,4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1036,4,4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1037,4,4,5,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1038,4,4,6,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1039,4,4,6,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1040,4,4,6,3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1041,4,4,6,4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1042,4,4,6,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1043,4,4,6,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1044,4,4,7,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1045,4,4,7,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1046,4,4,7,3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1047,4,4,7,4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1048,4,4,7,5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1049,4,4,7,6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
NHBattr = tem.NHBAttractionModel(trip_rates_paths={
        1: r"T:\ThomasPrince\nhb_attraction_triprates_p1.dvec",
        2: r"T:\ThomasPrince\nhb_attraction_triprates_p2.dvec",
        3: r"T:\ThomasPrince\nhb_attraction_triprates_p3.dvec",
        4: r"T:\ThomasPrince\nhb_attraction_triprates_p4.dvec",
        5: r"T:\ThomasPrince\nhb_attraction_triprates_p5.dvec",
        6: r"T:\ThomasPrince\nhb_attraction_triprates_p6.dvec",
        8: r"T:\ThomasPrince\nhb_attraction_triprates_p8.dvec"
    },
    emp_landuse_paths = {2023: r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf"},
    hh_landuse_dirs = {2023: r"F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs"},
    hh_landuse_prefix = "Output P14.1",
    nhb_mts_split_path=r"C:\Users\Spiral\Documents\Thomas Prince\NTS Processing DVec\outputs_is\attractions\nhb\mode_time_splits\hb_mode_time_split_attraction.dvec")

In [34]:
hb_mts = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\NTS Processing DVec\outputs_is\attractions\hb\mode_time_splits\hb_mode_time_split_attraction_hb_fr.dvec")
hb_mts = hb_mts.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
hb_mts = hb_mts.filter_segment_value("p", [1])
hb_mts.data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level m is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level tp is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(
c:\Users\Spiral\miniforge3\envs\caf.tem_dev\lib\site-packages\caf\toolkit\translation.py:906: UserWarning: Some values seem to have been dropped. The difference total is 43279.99999999996 (translated - original).
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

normits_id  1001001   1001002   1001003   1001004   1001005   1001006   \
p m tp
1 1 1       0.057195  0.057195  0.057195  0.057195  0.057195  0.057195
    2       0.026044  0.026044  0.026044  0.026044  0.026044  0.026044
    3       0.006565  0.006565  0.006565  0.006565  0.006565  0.006565
    4       0.015500  0.015500  0.015500  0.015500  0.015500  0.015500
    5       0.014620  0.014620  0.014620  0.014620  0.014620  0.014620
    6       0.007846  0.007846  0.007846  0.007846  0.007846  0.007846
  2 1       0.020565  0.020565  0.020565  0.020565  0.020565  0.020565
    2       0.006870  0.006870  0.006870  0.006870  0.006870  0.006870
    3       0.000796  0.000796  0.000796  0.000796  0.000796  0.000796
    4       0.011990  0.011990  0.011990  0.011990  0.011990  0.011990
    5       0.002952  0.002952  0.002952  0.002952  0.002952  0.002952
    6       0.002114  0.002114  0.002114  0.002114  0.002114  0.002114
  3 1       0.385293  0.385293  0.385293  0.385293  0.385293  0.385293
    2       0.077461  0.077461  0.077461  0.077461  0.077461  0.077461
    3       0.046089  0.046089  0.046089  0.046089  0.046089  0.046089
    4       0.133022  0.133022  0.133022  0.133022  0.133022  0.133022
    5       0.050166  0.050166  0.050166  0.050166  0.050166  0.050166
    6       0.035916  0.035916  0.035916  0.035916  0.035916  0.035916
  4 1       0.020772  0.020772  0.020772  0.020772  0.020772  0.020772
    2       0.001374  0.001374  0.001374  0.001374  0.001374  0.001374
    3       0.000642  0.000642  0.000642  0.000642  0.000642  0.000642
    4       0.008967  0.008967  0.008967  0.008967  0.008967  0.008967
    5       0.002550  0.002550  0.002550  0.002550  0.002550  0.002550
    6       0.001492  0.001492  0.001492  0.001492  0.001492  0.001492
  5 1       0.030616  0.030616  0.030616  0.030616  0.030616  0.030616
    2       0.007694  0.007694  0.007694  0.007694  0.007694  0.007694
    3       0.001916  0.001916  0.001916  0.001916  0.001916  0.001916
    4       0.008030  0.008030  0.008030  0.008030  0.008030  0.008030
    5       0.004294  0.004294  0.004294  0.004294  0.004294  0.004294
    6       0.001849  0.001849  0.001849  0.001849  0.001849  0.001849
  6 1       0.004980  0.004980  0.004980  0.004980  0.004980  0.004980
    2       0.000811  0.000811  0.000811  0.000811  0.000811  0.000811
    3       0.000042  0.000042  0.000042  0.000042  0.000042  0.000042
    4       0.001058  0.001058  0.001058  0.001058  0.001058  0.001058
    5       0.000257  0.000257  0.000257  0.000257  0.000257  0.000257
    6       0.000141  0.000141  0.000141  0.000141  0.000141  0.000141
  7 1       0.000620  0.000620  0.000620  0.000620  0.000620  0.000620
    2       0.000447  0.000447  0.000447  0.000447  0.000447  0.000447
    3       0.000036  0.000036  0.000036  0.000036  0.000036  0.000036
    4       0.000147  0.000147  0.000147  0.000147  0.000147  0.000147
    5       0.000209  0.000209  0.000209  0.000209  0.000209  0.000209
    6       0.000054  0.000054  0.000054  0.000054  0.000054  0.000054

normits_id  1001007   1001008   1001009   1001010   ...  11357010  11358001  \
p m tp                                              ...
1 1 1       0.057195  0.057195  0.057195  0.057195  ...  0.052449  0.061543
    2       0.026044  0.026044  0.026044  0.026044  ...  0.019222  0.022441
    3       0.006565  0.006565  0.006565  0.006565  ...  0.005264  0.005111
    4       0.015500  0.015500  0.015500  0.015500  ...  0.014570  0.017699
    5       0.014620  0.014620  0.014620  0.014620  ...  0.008606  0.008265
    6       0.007846  0.007846  0.007846  0.007846  ...  0.008399  0.006062
  2 1       0.020565  0.020565  0.020565  0.020565  ...  0.008485  0.010188
    2       0.006870  0.006870  0.006870  0.006870  ...  0.001784  0.003474
    3       0.000796  0.000796  0.000796  0.000796  ...  0.000550  0.001831
    4       0.011990  0.011990  0.011990  0.011990  ...  0.002741  0.005197
    5       0.002952  0.002952  0.002952  0.002952  ...  0.000901  0.001475
    6       0.002114  0.002114  0.002114  0.002114  ...  0.000494  0.000693
  3 1       0.385293  0.385293  0.385293  0.385293  ...  0.380600  0.412104
    2       0.077461  0.077461  0.077461  0.077461  ...  0.076336  0.089494
    3       0.046089  0.046089  0.046089  0.046089  ...  0.037989  0.041504
    4       0.133022  0.133022  0.133022  0.133022  ...  0.104022  0.141662
    5       0.050166  0.050166  0.050166  0.050166  ...  0.040980  0.051991
    6       0.035916  0.035916  0.035916  0.035916  ...  0.034652  0.034180
  4 1       0.020772  0.020772  0.020772  0.020772  ...  0.019321  0.033068
    2       0.001374  0.001374  0.001374  0.001374  ...  0.001304  0.003058
    3       0.000642  0.000642  0.000642  0.000642  ...  0.000556  0.001661
    4       0.008967  0.008967  0.008967  0.008967  ...  0.009009  0.013744
    5       0.002550  0.002550  0.002550  0.002550  ...  0.002097  0.004242
    6       0.001492  0.001492  0.001492  0.001492  ...  0.000909  0.001403
  5 1       0.030616  0.030616  0.030616  0.030616  ...  0.072968  0.014411
    2       0.007694  0.007694  0.007694  0.007694  ...  0.014850  0.004033
    3       0.001916  0.001916  0.001916  0.001916  ...  0.004128  0.000657
    4       0.008030  0.008030  0.008030  0.008030  ...  0.020105  0.003463
    5       0.004294  0.004294  0.004294  0.004294  ...  0.008351  0.002029
    6       0.001849  0.001849  0.001849  0.001849  ...  0.003667  0.000790
  6 1       0.004980  0.004980  0.004980  0.004980  ...  0.033309  0.001522
    2       0.000811  0.000811  0.000811  0.000811  ...  0.002800  0.000000
    3       0.000042  0.000042  0.000042  0.000042  ...  0.000892  0.000000
    4       0.001058  0.001058  0.001058  0.001058  ...  0.003694  0.000510
    5       0.000257  0.000257  0.000257  0.000257  ...  0.001429  0.000094
    6       0.000141  0.000141  0.000141  0.000141  ...  0.000673  0.000052
  7 1       0.000620  0.000620  0.000620  0.000620  ...  0.000979  0.000174
    2       0.000447  0.000447  0.000447  0.000447  ...  0.000500  0.000000
    3       0.000036  0.000036  0.000036  0.000036  ...  0.000246  0.000000
    4       0.000147  0.000147  0.000147  0.000147  ...  0.000000  0.000176
    5       0.000209  0.000209  0.000209  0.000209  ...  0.000124  0.000000
    6       0.000054  0.000054  0.000054  0.000054  ...  0.000046  0.000000

normits_id  11358002  11358003  11358004  11358005  11358006  11358007  \
p m tp
1 1 1       0.052449  0.052449  0.052449  0.052449  0.052449  0.052449
    2       0.019222  0.019222  0.019222  0.019222  0.019222  0.019222
    3       0.005264  0.005264  0.005264  0.005264  0.005264  0.005264
    4       0.014570  0.014570  0.014570  0.014570  0.014570  0.014570
    5       0.008606  0.008606  0.008606  0.008606  0.008606  0.008606
    6       0.008399  0.008399  0.008399  0.008399  0.008399  0.008399
  2 1       0.008485  0.008485  0.008485  0.008485  0.008485  0.008485
    2       0.001784  0.001784  0.001784  0.001784  0.001784  0.001784
    3       0.000550  0.000550  0.000550  0.000550  0.000550  0.000550
    4       0.002741  0.002741  0.002741  0.002741  0.002741  0.002741
    5       0.000901  0.000901  0.000901  0.000901  0.000901  0.000901
    6       0.000494  0.000494  0.000494  0.000494  0.000494  0.000494
  3 1       0.380600  0.380600  0.380600  0.380600  0.380600  0.380600
    2       0.076336  0.076336  0.076336  0.076336  0.076336  0.076336
    3       0.037989  0.037989  0.037989  0.037989  0.037989  0.037989
    4       0.104022  0.104022  0.104022  0.104022  0.104022  0.104022
    5       0.040980  0.040980  0.040980  0.040980  0.040980  0.040980
    6       0.034652  0.034652  0.034652  0.034652  0.034652  0.034652
  4 1       0.019321  0.019321  0.019321  0.019321  0.019321  0.019321
    2       0.001304  0.001304  0.001304  0.001304  0.001304  0.001304
    3       0.000556  0.000556  0.000556  0.000556  0.000556  0.000556
    4       0.009009  0.009009  0.009009  0.009009  0.009009  0.009009
    5       0.002097  0.002097  0.002097  0.002097  0.002097  0.002097
    6       0.000909  0.000909  0.000909  0.000909  0.000909  0.000909
  5 1       0.072968  0.072968  0.072968  0.072968  0.072968  0.072968
    2       0.014850  0.014850  0.014850  0.014850  0.014850  0.014850
    3       0.004128  0.004128  0.004128  0.004128  0.004128  0.004128
    4       0.020105  0.020105  0.020105  0.020105  0.020105  0.020105
    5       0.008351  0.008351  0.008351  0.008351  0.008351  0.008351
    6       0.003667  0.003667  0.003667  0.003667  0.003667  0.003667
  6 1       0.033309  0.033309  0.033309  0.033309  0.033309  0.033309
    2       0.002800  0.002800  0.002800  0.002800  0.002800  0.002800
    3       0.000892  0.000892  0.000892  0.000892  0.000892  0.000892
    4       0.003694  0.003694  0.003694  0.003694  0.003694  0.003694
    5       0.001429  0.001429  0.001429  0.001429  0.001429  0.001429
    6       0.000673  0.000673  0.000673  0.000673  0.000673  0.000673
  7 1       0.000979  0.000979  0.000979  0.000979  0.000979  0.000979
    2       0.000500  0.000500  0.000500  0.000500  0.000500  0.000500
    3       0.000246  0.000246  0.000246  0.000246  0.000246  0.000246
    4       0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
    5       0.000124  0.000124  0.000124  0.000124  0.000124  0.000124
    6       0.000046  0.000046  0.000046  0.000046  0.000046  0.000046

normits_id  11358008  11358009
p m tp
1 1 1       0.052449  0.052449
    2       0.019222  0.019222
    3       0.005264  0.005264
    4       0.014570  0.014570
    5       0.008606  0.008606
    6       0.008399  0.008399
  2 1       0.008485  0.008485
    2       0.001784  0.001784
    3       0.000550  0.000550
    4       0.002741  0.002741
    5       0.000901  0.000901
    6       0.000494  0.000494
  3 1       0.380600  0.380600
    2       0.076336  0.076336
    3       0.037989  0.037989
    4       0.104022  0.104022
    5       0.040980  0.040980
    6       0.034652  0.034652
  4 1       0.019321  0.019321
    2       0.001304  0.001304
    3       0.000556  0.000556
    4       0.009009  0.009009
    5       0.002097  0.002097
    6       0.000909  0.000909
  5 1       0.072968  0.072968
    2       0.014850  0.014850
    3       0.004128  0.004128
    4       0.020105  0.020105
    5       0.008351  0.008351
    6       0.003667  0.003667
  6 1       0.033309  0.033309
    2       0.002800  0.002800
    3       0.000892  0.000892
    4       0.003694  0.003694
    5       0.001429  0.001429
    6       0.000673  0.000673
  7 1       0.000979  0.000979
    2       0.000500  0.000500
    3       0.000246  0.000246
    4       0.000000  0.000000
    5       0.000124  0.000124
    6       0.000046  0.000046

[42 rows x 5430 columns]

In [ ]:
cb.DVector.concat([])

In [7]:
hbattr = cb.DVector.load(HBattr.export_paths.export_paths.pure_demand[2023])
hbattr = hbattr.filter_segment_value("p", [1])
hbattr.data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

                                               1001001       1001002   \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  1.167150e+02  1.664219e+02
 1           1          1    1          1  1.791050e+00  1.555839e+00
                        2    1          1  6.830963e+00  5.933883e+00
                        3    1          1  3.183902e+00  2.765774e+00
 2           1          1    1          1  4.283594e-12  2.707178e-12
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               1001003       1001004   \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  1.360025e+03  2.589809e+02
 1           1          1    1          1  1.622789e+00  1.517266e+00
                        2    1          1  6.189227e+00  5.786766e+00
                        3    1          1  2.884789e+00  2.697203e+00
 2           1          1    1          1  2.705396e-12  3.385459e-12
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               1001005       1001006   \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  9.982372e+01  3.905203e+02
 1           1          1    1          1  2.006663e+00  3.883105e+00
                        2    1          1  7.653299e+00  1.480994e+01
                        3    1          1  3.567191e+00  6.902892e+00
 2           1          1    1          1  2.165742e-12  2.165742e-12
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               1001007       1001008   \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  5.747773e+02  6.016128e+01
 1           1          1    1          1  1.041882e+01  1.331515e+00
                        2    1          1  3.973680e+01  5.078323e+00
                        3    1          1  1.852126e+01  2.366999e+00
 2           1          1    1          1  2.156428e-12  2.707179e-12
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               1001009       1001010   ...  \
sic_4_digit sic_2_digit soc sic_1_digit p                              ...
-1          -1          4   -1          1  3.746276e+02  1.068439e+03  ...
 1           1          1    1          1  4.962039e+01  2.592900e+00  ...
                        2    1          1  1.892493e+02  9.889174e+00  ...
                        3    1          1  8.820884e+01  4.609329e+00  ...
 2           1          1    1          1  3.789578e-12  3.787355e-12  ...
...                                                 ...           ...  ...
 615         98         2    20         1  0.000000e+00  0.000000e+00  ...
                        3    20         1  0.000000e+00  0.000000e+00  ...
 616         99         1    21         1  0.000000e+00  0.000000e+00  ...
                        2    21         1  0.000000e+00  0.000000e+00  ...
                        3    21         1  0.000000e+00  0.000000e+00  ...

                                               11357010      11358001  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  8.467486e+02  1.261088e+02
 1           1          1    1          1  4.801818e+00  5.932086e-01
                        2    1          1  1.614858e+01  2.184759e+00
                        3    1          1  7.570958e+00  1.026996e+00
 2           1          1    1          1  1.820410e-11  6.149716e-13
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               11358002      11358003  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  6.277464e+03  5.442002e+03
 1           1          1    1          1  2.233356e+00  4.532535e+00
                        2    1          1  7.510808e+00  1.524298e+01
                        3    1          1  3.521301e+00  7.146383e+00
 2           1          1    1          1  5.432257e-11  5.233396e-11
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               11358004      11358005  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  3.687922e+03  2.665280e+03
 1           1          1    1          1  1.812072e+00  6.658058e+00
                        2    1          1  6.094024e+00  2.239114e+01
                        3    1          1  2.857069e+00  1.049767e+01
 2           1          1    1          1  2.520567e-11  3.632709e-11
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               11358006      11358007  \
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  3.376687e+04  3.349557e+03
 1           1          1    1          1  1.555309e+00  6.118532e+00
                        2    1          1  5.230524e+00  2.057671e+01
                        3    1          1  2.452233e+00  9.647003e+00
 2           1          1    1          1  3.796186e-11  6.527716e-10
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

                                               11358008      11358009
sic_4_digit sic_2_digit soc sic_1_digit p
-1          -1          4   -1          1  1.863724e+03  1.110777e+04
 1           1          1    1          1  2.095368e+00  2.584470e+00
                        2    1          1  7.046753e+00  8.691608e+00
                        3    1          1  3.303738e+00  4.074897e+00
 2           1          1    1          1  2.611088e-11  4.039490e-11
...                                                 ...           ...
 615         98         2    20         1  0.000000e+00  0.000000e+00
                        3    20         1  0.000000e+00  0.000000e+00
 616         99         1    21         1  0.000000e+00  0.000000e+00
                        2    21         1  0.000000e+00  0.000000e+00
                        3    21         1  0.000000e+00  0.000000e+00

[1849 rows x 5430 columns]

In [10]:
other.concat(other=hbattr)

NameError: name 'other' is not defined

In [19]:
cb.segmentation.SegmentsSuper("ns_sec").get_segment()

Segment(name='ns_sec', values={1: 'HRP managerial / professional', 2: 'HRP intermediate / technical', 3: 'HRP semi-routine / routine', 4: 'HRP never worked / long-term unemployed', 5: 'HRP no category, inc. full-time student'}, alias=None, exclusions=[], lookups=[])

In [ ]:
cb.segmentation.Segmentation.

AttributeError: 'DVector' object has no attribute 'items'

In [ ]:
(hbattr * hb_mts).data # hbproduction applies mts and filters also - check code - employment segmentation, trust user? Pure attraction segmentation?

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['sic_4_digit', 'sic_2_digit', 'soc', 'sic_1_digit', 'p'] to ['sic_4_digit', 'sic_2_digit', 'sic_1_digit', 'soc', 'm', 'tp', 'p']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(

                                                1001001   1001002    1001003   \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   6.675543  9.518541  77.786995
                                            2   3.039753  4.334332  35.420832
                                            3   0.766248  1.092580   8.928730
                                            4   1.809122  2.579596  21.080860
                                            5   1.706362  2.433072  19.883441
...                                                  ...       ...        ...
 616         99         3    21         1 7 2   0.000000  0.000000   0.000000
                                            3   0.000000  0.000000   0.000000
                                            4   0.000000  0.000000   0.000000
                                            5   0.000000  0.000000   0.000000
                                            6   0.000000  0.000000   0.000000

                                                 1001004   1001005   \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   14.812481  5.709444
                                            2    6.744963  2.599834
                                            3    1.700241  0.655355
                                            4    4.014294  1.547302
                                            5    3.786277  1.459413
...                                                   ...       ...
 616         99         3    21         1 7 2    0.000000  0.000000
                                            3    0.000000  0.000000
                                            4    0.000000  0.000000
                                            5    0.000000  0.000000
                                            6    0.000000  0.000000

                                                 1001006    1001007   \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   22.335911  32.874536
                                            2   10.170808  14.969641
                                            3    2.563813   3.773482
                                            4    6.053200   8.909246
                                            5    5.709371   8.403190
...                                                   ...        ...
 616         99         3    21         1 7 2    0.000000   0.000000
                                            3    0.000000   0.000000
                                            4    0.000000   0.000000
                                            5    0.000000   0.000000
                                            6    0.000000   0.000000

                                                1001008    1001009   \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   3.440940  21.426922
                                            2   1.566855   9.756893
                                            3   0.394966   2.459475
                                            4   0.932521   5.806857
                                            5   0.879552   5.477020
...                                                  ...        ...
 616         99         3    21         1 7 2   0.000000   0.000000
                                            3   0.000000   0.000000
                                            4   0.000000   0.000000
                                            5   0.000000   0.000000
                                            6   0.000000   0.000000

                                                 1001010   ...   11357010  \
sic_4_digit sic_2_digit soc sic_1_digit p m tp             ...
-1          -1          4   -1          1 1 1   61.109643  ...  44.411358
                                            2   27.826687  ...  16.276331
                                            3    7.014431  ...   4.456905
                                            4   16.561172  ...  12.337271
                                            5   15.620477  ...   7.286887
...                                                   ...  ...        ...
 616         99         3    21         1 7 2    0.000000  ...   0.000000
                                            3    0.000000  ...   0.000000
                                            4    0.000000  ...   0.000000
                                            5    0.000000  ...   0.000000
                                            6    0.000000  ...   0.000000

                                                11358001    11358002  \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   7.761164  329.248489
                                            2   2.829981  120.666369
                                            3   0.644505   33.041755
                                            4   2.231984   91.463720
                                            5   1.042310   54.022138
...                                                  ...         ...
 616         99         3    21         1 7 2   0.000000    0.000000
                                            3   0.000000    0.000000
                                            4   0.000000    0.000000
                                            5   0.000000    0.000000
                                            6   0.000000    0.000000

                                                  11358003    11358004  \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   285.429142  193.428871
                                            2   104.607005   70.889800
                                            3    28.644261   19.411568
                                            4    79.290907   53.733653
                                            5    46.832387   31.737249
...                                                    ...         ...
 616         99         3    21         1 7 2     0.000000    0.000000
                                            3     0.000000    0.000000
                                            4     0.000000    0.000000
                                            5     0.000000    0.000000
                                            6     0.000000    0.000000

                                                  11358005     11358006  \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   139.792021  1771.048100
                                            2    51.232416   649.071905
                                            3    14.028838   177.733653
                                            4    38.833582   491.989040
                                            5    22.936670   290.588442
...                                                    ...          ...
 616         99         3    21         1 7 2     0.000000     0.000000
                                            3     0.000000     0.000000
                                            4     0.000000     0.000000
                                            5     0.000000     0.000000
                                            6     0.000000     0.000000

                                                  11358007   11358008  \
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   175.681884  97.751009
                                            2    64.385702  35.824794
                                            3    17.630567   9.809809
                                            4    48.803622  27.154782
                                            5    28.825375  16.038702
...                                                    ...        ...
 616         99         3    21         1 7 2     0.000000   0.000000
                                            3     0.000000   0.000000
                                            4     0.000000   0.000000
                                            5     0.000000   0.000000
                                            6     0.000000   0.000000

                                                  11358009
sic_4_digit sic_2_digit soc sic_1_digit p m tp
-1          -1          4   -1          1 1 1   582.594751
                                            2   213.515310
                                            3    58.466336
                                            4   161.842150
                                            5    95.590459
...                                                    ...
 616         99         3    21         1 7 2     0.000000
                                            3     0.000000
                                            4     0.000000
                                            5     0.000000
                                            6     0.000000

[77658 rows x 5430 columns]

In [38]:
(hb_mts * hbattr).data

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:931: SegmentationWarning: This operation has changed the segmentation of the DVector from ['p', 'm', 'tp'] to ['sic_2_digit', 'sic_4_digit', 'sic_1_digit', 'soc', 'tp', 'm', 'p']. This can happen but it can also be a sign of an error. Check the output DVector.
  warnings.warn(

normits_id                                          1001001       1001002   \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           6.675543e+00  9.518541e+00
        1           1          1    1           1.024396e-01  8.898664e-02
                               2    1           3.906987e-01  3.393900e-01
                               3    1           1.821041e-01  1.581892e-01
        2           1          1    1           2.450013e-13  1.548377e-13
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          1001003       1001004   \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           7.778699e+01  1.481248e+01
        1           1          1    1           9.281586e-02  8.678042e-02
                               2    1           3.539944e-01  3.309756e-01
                               3    1           1.649963e-01  1.542672e-01
        2           1          1    1           1.547358e-13  1.936322e-13
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          1001005       1001006   \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           5.709444e+00  2.233591e+01
        1           1          1    1           1.147716e-01  2.220952e-01
                               2    1           4.377324e-01  8.470585e-01
                               3    1           2.040264e-01  3.948127e-01
        2           1          1    1           1.238702e-13  1.238702e-13
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          1001007       1001008   \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           3.287454e+01  3.440940e+00
        1           1          1    1           5.959073e-01  7.615636e-02
                               2    1           2.272757e+00  2.904560e-01
                               3    1           1.059329e+00  1.353811e-01
        2           1          1    1           1.233375e-13  1.548378e-13
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          1001009       1001010   \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           2.142692e+01  6.110964e+01
        1           1          1    1           2.838051e+00  1.483016e-01
                               2    1           1.082417e+01  5.656139e-01
                               3    1           5.045127e+00  2.636318e-01
        2           1          1    1           2.167459e-13  2.166188e-13
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                      ...      11357010  \
p m tp sic_4_digit sic_2_digit soc sic_1_digit  ...
1 1 1  -1          -1          4   -1           ...  4.441136e+01
        1           1          1    1           ...  2.518519e-01
                               2    1           ...  8.469815e-01
                               3    1           ...  3.970914e-01
        2           1          1    1           ...  9.547919e-13
...                                             ...           ...
  7 6   615         98         2    20          ...  0.000000e+00
                               3    20          ...  0.000000e+00
        616         99         1    21          ...  0.000000e+00
                               2    21          ...  0.000000e+00
                               3    21          ...  0.000000e+00

normits_id                                          11358001      11358002  \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           7.761164e+00  3.292485e+02
        1           1          1    1           3.650807e-02  1.171379e-01
                               2    1           1.344575e-01  3.939365e-01
                               3    1           6.320481e-02  1.846897e-01
        2           1          1    1           3.784743e-14  2.849180e-12
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          11358003      11358004  \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           2.854291e+02  1.934289e+02
        1           1          1    1           2.377282e-01  9.504189e-02
                               2    1           7.994832e-01  3.196272e-01
                               3    1           3.748227e-01  1.498512e-01
        2           1          1    1           2.744879e-12  1.322020e-12
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          11358005      11358006  \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           1.397920e+02  1.771048e+03
        1           1          1    1           3.492104e-01  8.157482e-02
                               2    1           1.174399e+00  2.743373e-01
                               3    1           5.505951e-01  1.286179e-01
        2           1          1    1           1.905330e-12  1.991073e-12
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          11358007      11358008  \
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           1.756819e+02  9.775101e+01
        1           1          1    1           3.209126e-01  1.099006e-01
                               2    1           1.079234e+00  3.695972e-01
                               3    1           5.059784e-01  1.732787e-01
        2           1          1    1           3.423741e-11  1.369497e-12
...                                                      ...           ...
  7 6   615         98         2    20          0.000000e+00  0.000000e+00
                               3    20          0.000000e+00  0.000000e+00
        616         99         1    21          0.000000e+00  0.000000e+00
                               2    21          0.000000e+00  0.000000e+00
                               3    21          0.000000e+00  0.000000e+00

normits_id                                          11358009
p m tp sic_4_digit sic_2_digit soc sic_1_digit
1 1 1  -1          -1          4   -1           5.825948e+02
        1           1          1    1           1.355536e-01
                               2    1           4.558686e-01
                               3    1           2.137254e-01
        2           1          1    1           2.118684e-12
...                                                      ...
  7 6   615         98         2    20          0.000000e+00
                               3    20          0.000000e+00
        616         99         1    21          0.000000e+00
                               2    21          0.000000e+00
                               3    21          0.000000e+00

[77658 rows x 5430 columns]

In [ ]:
hb_mts.__mul__()

In [14]:
cb.segmentation.SegmentsSuper("m").get_segment()

Segment(name='m', values={1: 'Walk', 2: 'Cycle', 3: 'Car driver', 4: 'Car passenger', 5: 'Bus / Coach', 6: 'Rail / underground', 7: 'Tram', 8: 'Air travel'}, alias=None, exclusions=[], lookups=[])

In [13]:
aa = cb.DVector.load(r"F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs\Output P13.3_NE.hdf")

In [ ]:
aa.data

In [ ]:
p1 = cb.DVector.load(HBattr.trip_rates_paths[1])
p2 = cb.DVector.load(HBattr.trip_rates_paths[2])
p3 = cb.DVector.load(HBattr.trip_rates_paths[3])
p4 = cb.DVector.load(HBattr.trip_rates_paths[4])
p5 = cb.DVector.load(HBattr.trip_rates_paths[5])
p6 = cb.DVector.load(HBattr.trip_rates_paths[6])
p8 = cb.DVector.load(HBattr.trip_rates_paths[8])

In [ ]:
segs = ["p", "sic_2_digit"]
cb.Segmentation(cb.SegmentationInput(enum_segments=segs, naming_order=segs)).names

In [91]:
dvecs: list[cb.DVector] = []
for p in [p1, p2, p3, p4, p5, p6, p8]:
    p = p.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
    #dvecs.append(p.expand_to_other(p5, match_props=False))

In [ ]:
p1.data # desired is by soc, trip rates by soc. Trip ends by soc bc. people by diff. soc have different trip rates. p3-p8 is not soc, 
# trip end from p3 to p8, only use emp. who work in these industries as a proxy for people working in these trip ends.
# p3 education, should get #students who go to prim/sec/uni as these are main source of attractions. we use #teachers/ professors as proxy 
# diff format of trip rates for 
p4.expand_to_other(p1, match_props=False).data

In [ ]:
p4.data

In [87]:
emp = cb.DVector.load(r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf")
emp = cb.DVector(segmentation=emp.segmentation, import_data=emp.data, zoning_system=cb.ZoningSystem.get_zoning("lsoa_2021"))
emp = emp.translate_zoning(cb.ZoningSystem.get_zoning("normits"))

In [ ]:
p1.zoning_system.name

In [110]:
p1 = p1.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
p2 = p2.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
p3 = p3.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
p4 = p4.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
p5 = p5.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
p6 = p6.translate_zoning(cb.ZoningSystem.get_zoning("normits"))
p8 = p8.translate_zoning(cb.ZoningSystem.get_zoning("normits"))

In [ ]:
emp.aggregate(["sic_2_digit", "soc"]).data

In [121]:
test1 = emp * p3
test2 = emp * p1

In [ ]:
p1.data

In [ ]:
test1.data.expand_to_other(test2, match_props=True).data

In [ ]:
test2.data

In [146]:
dic = {1: test1, 2: test2}

In [ ]:
cb.segmentation.SegmentsSuper("p").get_segment(subset=[1,2]).name

In [ ]:
mylist = [None, "a", "q"]
list(map(lambda x: "p" if x is None else x, mylist))

In [ ]:
new_list = list(map(lambda x: 0 if x is None else x, my_list))

In [ ]:
cb.DVector.combine_from_dic(dic, cb.segmentation.SegmentsSuper("p").get_segment(subset=[1,2]), dic[1].segmentation, dic[1].zoning_system)

In [ ]:
cb.ZoningSystem.get_zoning("gor")

In [46]:
c = a.expand_to_other(b, match_props=False)

In [ ]:
c.data

In [ ]:
a

In [ ]:
cb.segments.SegmentsSuper("p").get_segment(subset=list([1,2,3]))

In [ ]:
a = cb.DVector.load(HBattr.trip_rates_paths[4])
b = cb.DVector.load(HBattr.trip_rates_paths[3])

In [ ]:
a.expand_to_other(b, match_props=True)

In [ ]:
a.data

In [ ]:
cb.Segment(name = "Purpose", values = {1: "test"}, alias="ppp")

In [ ]:
cb.segmentation.SegmentsSuper("p").get_segment()

In [ ]:
p = 8
trip_rate = cb.DVector.load(HBattr.trip_rates_paths[p])
trip_rate.data
#trip_rate = trip_rate.translate_zoning(cb.ZoningSystem.get_zoning(HBattr.export_paths._zoning_system),
#                                    check_totals=False, 
#                                    no_factors=True)

In [ ]:
trip_rate = cb.DVector.load(HBattr.trip_rates_paths[p])
trip_rate.data

In [ ]:
trip_rate.translate_zoning(cb.ZoningSystem.get_zoning(HBattr.export_paths._zoning_system),
                                    check_totals=False, 
                                    no_factors=True)

In [ ]:
a = export_paths.asdf(
    trip_rates_paths={
        1: r"T:\ThomasPrince\hb_attraction_triprates_p1.dvec",
        2: r"T:\ThomasPrince\hb_attraction_triprates_p2.dvec",
        3: r"T:\ThomasPrince\hb_attraction_triprates_p3.dvec",
        4: r"T:\ThomasPrince\hb_attraction_triprates_p4.dvec",
        5: r"T:\ThomasPrince\hb_attraction_triprates_p5.dvec",
        6: r"T:\ThomasPrince\hb_attraction_triprates_p6.dvec",
        8: r"T:\ThomasPrince\hb_attraction_triprates_p8.dvec"
    },
    emp_landuse_path = r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf",
    hh_landuse_dir = r"F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs",
    hh_landuse_prefix = "Output P14.1")

In [ ]:
export_paths.hb_attraction.__dict__

In [7]:
model = AttractionModel_TP(
    export_paths,
    trip_rates_paths={
        1: r"T:\ThomasPrince\hb_attraction_triprates_p1.dvec",
        2: r"T:\ThomasPrince\hb_attraction_triprates_p2.dvec",
        3: r"T:\ThomasPrince\hb_attraction_triprates_p3.dvec",
        4: r"T:\ThomasPrince\hb_attraction_triprates_p4.dvec",
        5: r"T:\ThomasPrince\hb_attraction_triprates_p5.dvec",
        6: r"T:\ThomasPrince\hb_attraction_triprates_p6.dvec",
        8: r"T:\ThomasPrince\hb_attraction_triprates_p8.dvec"
    },
    emp_landuse_path = r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf",
    hh_landuse_dir = r"F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs",
    hh_landuse_prefix = "Output P14.1"
)

In [ ]:
model.run()

In [ ]:
# population data is P, 
a = {1: 5,
     2: 6,
     4: 7}

for i in a:
    print(a[i])

In [6]:
trip_rate = cb.DVector.load(model.trip_rates_path)

In [ ]:
trip_rate.data

In [ ]:
trip_rate.filter_segment_value("soc", [1]).data #- feel like purpose should be a segmentation, filtered like this...

In [ ]:
trip_rate2 = trip_rate.translate_zoning(cb.ZoningSystem.get_zoning("normits"), check_totals=False,no_factors=True)

In [ ]:
trip_rate2.data
#trip_rate.sum()

In [ ]:
out_dict = {
            1: [],  # commuting
            2: [],  # e.business
            3: [85],  # education
            4: [46, 47],  # Shopping: retail
            5: [86, 64, 65, 66, 68, 69, 75, 77, 79, 80, 95, 96, 56],
            6: [90, 91, 92, 93, 94],  # Social
            7: [],  # visit friend
            8: [55, 2, 3]
        }

In [11]:
hh = cb.DVector.load(r"F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs\Output P13.3_NE.hdf")

In [ ]:
hh.data

In [ ]:
trip_rate.data

In [ ]:
hh.

In [4]:
landuse = cb.DVector.load(model.landuse_path)

In [ ]:
landuse.filter_segment_value("sic_2_digit", []).data

In [ ]:
out_dict = {
            1: {'E01': 'All', 'exc': ['HH', '0-15', '16+']},  # commuting
            2: {'E01': 'All', 'exc': ['HH', '0-15', '16+']},  # e.business
            3: {'E03/04/05': 'S85'},  # 'Child': '0-15', 'Adult': '16+'},  # education
            4: {'E07': ['S46', 'S47']},  # shopping: retail
            # p.business: E08 (86/87) - health, E09 (64-69/75-81/95-96) - services, E11 (56) - food
            # 5: {'E08/09/11': ['S86', 'S87', 'S64', 'S65', 'S66', 'S68', 'S69', 'S75',
            #                   'S77', 'S79', 'S80', 'S81', 'S95', 'S96', 'S56']},
            5: {'E08': ['S86'],  # health
                'E09': ['S64', 'S65', 'S66', 'S68', 'S69', 'S75', 'S77', 'S79', 'S80', 'S95', 'S96'],
                'E11': ['S56']},
            6: {'E12': ['S90', 'S91', 'S92', 'S93', 'S94']},  # social
            7: {'E02': 'HH'},  # visit friends
            # holiday: E06 (55) - accommodation, E13 (S2-3) - fishing
            8: {'E06/13': ['S55', 'S02', 'S03']},
        }

In [ ]:
landuse.data

In [34]:
trip_rate3 = trip_rate2.translate_zoning(cb.ZoningSystem.get_zoning("lsoa_2021"), check_totals=False, no_factors=True)

In [ ]:
landuse2 = landuse.translate_zoning(cb.ZoningSystem.get_zoning("normits"), check_totals=False, no_factors=True)

In [ ]:
landuse.aggregate(["soc"]) * trip_rate3

In [ ]:
mts = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\NTS Processing DVec\outputs_is\attractions\hb\mode_time_splits\hb_mode_time_split_attraction_hb_fr.dvec")

In [ ]:
mts.data

In [ ]:

a = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP\Core\hb_attractions\hb_normits_pure_demand_2023_dvec.h5")

In [ ]:
a.data

In [ ]:
model.attraction_model_paths.export_paths.pure_demand[2023]

In [ ]:
export_paths.hb_attraction.__dict__

In [13]:
a = ct.AttractionModelPaths_TP([2023], 
                           export_home=r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export",
                           report_home=r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_test\Core\hb_attractions\reports",
                           zoning_system="normits",
                           _trip_origin="hb"
)

In [ ]:
a.test

In [3]:
trip_rates_paths = {
    "p1": r"T:\ThomasPrince\hb_attraction_triprates_p1.dvec"
}

In [4]:
landuse_paths = {
    "2023": r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf"
}

In [ ]:
export_paths.nhb_attraction#.path_years

In [ ]:
export_paths.hb_attraction._zoning_system

In [ ]:
ct.AttractionModel_TP(**export_paths.hb_attraction.__dict__)

In [ ]:
ct.AttractionModel(trip_rates_paths, landuse_paths, export_home="", zoning_system=cb.ZoningSystem.get_zoning("normits"))

In [ ]:
export_paths.hb_attraction

In [ ]:
model_paths = ct.TEMModelPaths(
    path_years=export_paths.path_years,
    export_home=,
    report_home=
)

In [ ]:
export_paths.hb_attraction

In [2]:
def TP_generate_attraction(trip_rate_dvec, landuse_dvec):
    """
    Two Inputs: 
        1. Trip Rates Path
        2. Land Use Path
    """
    #trip_rate_dvec = cb.DVector.load(trip_rates_path)
    #landuse_dvec = cb.DVector.load(landuse_path)

    attr = trip_rate_dvec * landuse_dvec
    
    return attr
    

    """
        Applies trip rates to the given HB employment.

        Parameters
        ----------
        emp_dvec:
            Dvector containing the employment.

        Returns
        -------
        pure_attraction:
            Returns the product of employment and attraction trip rate Dvector.
            ie., pure attraction
        

        # Define the zoning and segmentations we want to use
        
        attr_dict = {}
        segs = []
        longest = []
        # Different purposes have different segmentations
        for purpose, path in self.trip_rates_paths.items():
            trip_rate = cb.DVector.load(path)
            landuse = cb.DVector.load[self.landuse_paths[purpose]]
            attr = landuse * trip_rate
            for seg in attr.segmentation.names:
                if seg not in segs:
                    segs.append(seg)
            attr_dict[purpose] = attr
            if len(attr) > len(longest):
                longest = attr
        for purpose, dvec in attr_dict.items():
            if dvec == longest:
                continue
            attr_dict[purpose] = dvec.expand_to_other(longest, match_props=True)
        purp_seg = cb.segments.SegmentsSuper("p").get_segment(
            subset=list(attr_dict.keys())
        )
        zone_system = longest.zone_system
        attr_dvec = cb.DVector.combine_from_dic(attr_dict, purp_seg, zone_system)

        return attr_dvec
        """

In [3]:
trip_rates_path = Path(r"T:\ThomasPrince\hb_attraction_triprates_p1.dvec")
landuse_path = Path(r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf")

#TP_generate_attraction(trip_rates_path, landuse_path)

In [4]:
trip_rate_dvec = cb.DVector.load(trip_rates_path)
landuse_dvec = cb.DVector.load(landuse_path)

landuse_dvec = cb.DVector(segmentation=landuse_dvec.segmentation, import_data=landuse_dvec.data,zoning_system=cb.ZoningSystem.get_zoning("lsoa_2021"))

In [ ]:
trip_rate_dvec = trip_rate_dvec.translate_zoning(cb.ZoningSystem.get_zoning("normits"), check_totals=False, no_factors=True)
landuse_dvec = landuse_dvec.translate_zoning(cb.ZoningSystem.get_zoning("normits"), check_totals=False, no_factors=True)

In [ ]:
attr = trip_rate_dvec * landuse_dvec

In [ ]:
attr.data

In [ ]:
trip_rate_dvec.data

In [ ]:
landuse_dvec.data

In [ ]:
attr.aggregate(["soc", "sic_2_digit"]).data

In [ ]:
(landuse_dvec.aggregate(["soc", "sic_2_digit"]) * trip_rate_dvec).data

In [ ]:
trip_rate_dvec.data

In [ ]:
landuse_dvec.translate_zoning()

In [ ]:
TP_generate_attraction(trip_rate_dvec, landuse_dvec)

In [ ]:
trip_rate_dvec.zoning_system.name

In [ ]:
cb.DVector(segmentation=landuse_dvec.segmentation, import_data=landuse_dvec.data,zoning_system=cb.ZoningSystem.get_zoning("lsoa_2021"))

In [ ]:
landuse_dvec.data#zoning_system.name

In [ ]:
landuse_dvec.translate_zoning(cb.ZoningSystem.get_zoning("normits"))

In [ ]:
trip_rate_dvec.zoning_system.name

In [ ]:
landuse_dvec.translate_zoning(cb.ZoningSystem.get_zoning("normits"))

In [2]:
dir = r"T:\ThomasPrince"
triprates_paths = {
    "": dir 
}

In [3]:
TEM_Paths = ct.TEMModelPaths(
    path_years=[2023],
    export_home=r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export",
    report_home=r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Reports",
    zoning_system="normits"
)

In [4]:
HB_Attr_TEM_Paths = ct.AttractionModelPaths(
    "hb",
    TEM_Paths.path_years, 
    TEM_Paths.export_home,
    TEM_Paths.report_home,
    TEM_Paths._zoning_system
)

In [16]:
a = ct.Scenarios("Core")

In [ ]:
ct.TEMExportPaths(
        path_years=[2023],
        scenario=a,
        iteration_name="iter1",
        export_home=pathlib.Path(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export")
)

In [ ]:
ct.attraction_models

In [ ]:
HB_TEM_Paths

In [ ]:
ct.inputs.AttractionModelPaths(HB_TEM_Paths)

In [ ]:
ct.inputs.AttrInput(
    triprates={}, # dict[str, os.PathLike] # purpose: path, goes to directory, reads in purpose for each one.
    landuse={"2023": r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf"}, # dict[str, os.PathLike] # year: directory, within dir have emp, household, etc., download lu and same folder.
    balance_paths={}, # dict[str, os.PathLike] # might be obsolete - attractions balanced to prods.
    balance_zoning=cb.BalancingZones()# cb.BalancingZones
)

In [10]:
emp_landuse = cb.DVector.load(HBAttr.emp_landuse_paths[2023])
emp_landuse = cb.DVector(segmentation=emp_landuse.segmentation, import_data=emp_landuse.data, zoning_system=cb.ZoningSystem.get_zoning("lsoa_2021"))
desired_zoning = cb.ZoningSystem.get_zoning(HBAttr.export_paths._zoning_system)
#emp_landuse = emp_landuse.translate_zoning(desired_zoning, check_totals=False, no_factors=True)

In [19]:
emp_landuse.save(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Land Use\employment\Output E6.hdf")

In [6]:
HBAttr.emp_landuse_paths[2023]

'F:\\Deliverables\\Land-Use\\241213_Employment\\02_Final Outputs\\Output E6.hdf'

In [7]:
emp_landuse = cb.DVector.load(HBAttr.emp_landuse_paths[2023])

In [20]:
emp_landuse.zoning_system.name

'lsoa_2021'

In [21]:
import pathlib

In [25]:
dvecs: list[cb.DVector] = []
for region in [
    "EM",
    "EoE",
    "Lon",
    "NE",
    "NW",
    "SE",
    "SW",
    "Wales",
    "WM",
    "YH",
    "Scotland"
]:
    
    dvec = cb.DVector.load(
            pathlib.Path(HBAttr.hh_landuse_dirs[2023])
            / f"{HBAttr.hh_landuse_prefix}_{region}.hdf"
        )
    
    #dvecs.append(
    #    cb.DVector.load(
    #        pathlib.Path(HBAttr.hh_landuse_dirs[2023])
    #        / f"{HBAttr.hh_landuse_prefix}_{region}.hdf"
    #    )
    #)  # .aggregate(SEG_HH)) # I don't know what SEG_HH should be
    dvec_out = cb.DVector(
        import_data=dvec.data,
        segmentation=dvec.segmentation,
        zoning_system=cb.ZoningSystem.get_zoning("lsoa_2021"),
    )  # I don't know what TT_HH should be - TT defined in utils? assuming it's TT from utils - changed segmentation to be the same as the first dvec read
    #dvec_out = dvec_out.translate_zoning(
    #    cb.ZoningSystem.get_zoning(HBAttr.export_paths._zoning_system)
    #)
    dvec_out.save(rf"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Land Use\population\{HBAttr.hh_landuse_prefix}_{region}.hdf")


#data = pd.concat([d.data for d in dvecs], axis=1)
#hh_landuse = cb.DVector(
#    import_data=data,
#    segmentation=dvecs[0].segmentation,
#    zoning_system=cb.ZoningSystem.get_zoning("lsoa_2021"),
#)  # I don't know what TT_HH should be - TT defined in utils? assuming it's TT from utils - changed segmentation to be the same as the first dvec read
#hh_landuse = hh_landuse.translate_zoning(
#    cb.ZoningSystem.get_zoning(HBAttr.export_paths._zoning_system)
#)

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 39801 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 38890 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 37654 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 40966 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 38081 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 37077 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 39241 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 40731 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 39074 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 39293 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\data_structures.py:487: UserWarning: 35672 zone IDs from zoning system lsoa_2021 aren't found in the DVector data. This may be by design e.g. you are using a subset of a zoning system.
  warnings.warn(

In [ ]:
emp_landuse.save(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Land Use\employment\Output E6.hdf")

In [26]:
dvec_out.data

DZ2011                                                          35673  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.861361
                                       2        1            0.072166
                      2                1        1            9.903979
                                       2        1            0.864034
                      3                1        1            1.927950
...                                                               ...
5       5      3      1                2        15           0.000004
                      2                1        15           0.000263
                                       2        15           0.000031
                      3                1        15           0.000133
                                       2        15           0.000028

DZ2011                                                          35674  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.708599
                                       2        1            0.050301
                      2                1        1            8.509488
                                       2        1            0.601233
                      3                1        1            1.467721
...                                                               ...
5       5      3      1                2        15           0.000002
                      2                1        15           0.000176
                                       2        15           0.000016
                      3                1        15           0.000096
                                       2        15           0.000015

DZ2011                                                          35675  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.862809
                                       2        1            0.047968
                      2                1        1            4.820027
                                       2        1            0.569529
                      3                1        1            0.996445
...                                                               ...
5       5      3      1                2        15           0.000002
                      2                1        15           0.000134
                                       2        15           0.000016
                      3                1        15           0.000066
                                       2        15           0.000015

DZ2011                                                          35676  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.054223
                                       2        1            0.045417
                      2                1        1            5.433679
                                       2        1            0.538024
                      3                1        1            1.004940
...                                                               ...
5       5      3      1                2        15           0.000002
                      2                1        15           0.000136
                                       2        15           0.000016
                      3                1        15           0.000073
                                       2        15           0.000015

DZ2011                                                          35677  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.390831
                                       2        1            0.042673
                      2                1        1            6.882641
                                       2        1            0.507871
                      3                1        1            1.274290
...                                                               ...
5       5      3      1                2        15           0.000002
                      2                1        15           0.000155
                                       2        15           0.000018
                      3                1        15           0.000082
                                       2        15           0.000016

DZ2011                                                          35678  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.647403
                                       2        1            0.040543
                      2                1        1            8.316823
                                       2        1            0.487345
                      3                1        1            1.471381
...                                                               ...
5       5      3      1                2        15           0.000002
                      2                1        15           0.000191
                                       2        15           0.000019
                      3                1        15           0.000100
                                       2        15           0.000016

DZ2011                                                          35679  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.363921
                                       2        1            0.032072
                      2                1        1            7.112372
                                       2        1            0.383651
                      3                1        1            1.286952
...                                                               ...
5       5      3      1                2        15           0.000002
                      2                1        15           0.000164
                                       2        15           0.000017
                      3                1        15           0.000090
                                       2        15           0.000015

DZ2011                                                           35680  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1             2.660244
                                       2        1             0.078043
                      2                1        1            12.347161
                                       2        1             0.931092
                      3                1        1             2.046825
...                                                                ...
5       5      3      1                2        15            0.000002
                      2                1        15            0.000208
                                       2        15            0.000021
                      3                1        15            0.000116
                                       2        15            0.000018

DZ2011                                                           35681  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1             2.050419
                                       2        1             0.067049
                      2                1        1            10.630126
                                       2        1             0.800733
                      3                1        1             2.011690
...                                                                ...
5       5      3      1                2        15            0.000004
                      2                1        15            0.000254
                                       2        15            0.000029
                      3                1        15            0.000130
                                       2        15            0.000026

DZ2011                                                          35682  ...  \
accom_h ns_sec adults car_availability children adult_nssec            ...
1       1      1      1                1        1            1.278860  ...
                                       2        1            0.051840  ...
                      2                1        1            7.003697  ...
                                       2        1            0.620134  ...
                      3                1        1            1.385612  ...
...                                                               ...  ...
5       5      3      1                2        15           0.000003  ...
                      2                1        15           0.000191  ...
                                       2        15           0.000023  ...
                      3                1        15           0.000095  ...
                                       2        15           0.000020  ...

DZ2011                                                          42639  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.888400
                                       2        1            0.084189
                      2                1        1            3.911562
                                       2        1            0.375415
                      3                1        1            0.612802
...                                                               ...
5       5      3      1                2        15           0.000028
                      2                1        15           0.000227
                                       2        15           0.000027
                      3                1        15           0.000113
                                       2        15           0.000010

DZ2011                                                          42640  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.520171
                                       2        1            0.085702
                      2                1        1            2.578880
                                       2        1            0.378319
                      3                1        1            0.489452
...                                                               ...
5       5      3      1                2        15           0.000027
                      2                1        15           0.000220
                                       2        15           0.000026
                      3                1        15           0.000111
                                       2        15           0.000010

DZ2011                                                          42641  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.522148
                                       2        1            0.068325
                      2                1        1            2.464238
                                       2        1            0.304799
                      3                1        1            0.424257
...                                                               ...
5       5      3      1                2        15           0.000021
                      2                1        15           0.000178
                                       2        15           0.000021
                      3                1        15           0.000088
                                       2        15           0.000007

DZ2011                                                          42642  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.774555
                                       2        1            0.050883
                      2                1        1            3.445812
                                       2        1            0.222222
                      3                1        1            0.513132
...                                                               ...
5       5      3      1                2        15           0.000018
                      2                1        15           0.000185
                                       2        15           0.000017
                      3                1        15           0.000091
                                       2        15           0.000006

DZ2011                                                          42643  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.805405
                                       2        1            0.051874
                      2                1        1            3.447353
                                       2        1            0.228872
                      3                1        1            0.496059
...                                                               ...
5       5      3      1                2        15           0.000017
                      2                1        15           0.000177
                                       2        15           0.000017
                      3                1        15           0.000088
                                       2        15           0.000006

DZ2011                                                          42644  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.781274
                                       2        1            0.049675
                      2                1        1            3.492370
                                       2        1            0.222953
                      3                1        1            0.516194
...                                                               ...
5       5      3      1                2        15           0.000014
                      2                1        15           0.000150
                                       2        15           0.000014
                      3                1        15           0.000074
                                       2        15           0.000005

DZ2011                                                          42645  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.826339
                                       2        1            0.092921
                      2                1        1            3.817540
                                       2        1            0.412068
                      3                1        1            0.641846
...                                                               ...
5       5      3      1                2        15           0.000029
                      2                1        15           0.000272
                                       2        15           0.000028
                      3                1        15           0.000136
                                       2        15           0.000010

DZ2011                                                          42646  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.006360
                                       2        1            0.067236
                      2                1        1            4.301426
                                       2        1            0.298411
                      3                1        1            0.616983
...                                                               ...
5       5      3      1                2        15           0.000021
                      2                1        15           0.000217
                                       2        15           0.000021
                      3                1        15           0.000108
                                       2        15           0.000007

DZ2011                                                          42647  \
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            0.888090
                                       2        1            0.059791
                      2                1        1            3.809759
                                       2        1            0.267294
                      3                1        1            0.567733
...                                                               ...
5       5      3      1                2        15           0.000021
                      2                1        15           0.000185
                                       2        15           0.000021
                      3                1        15           0.000090
                                       2        15           0.000007

DZ2011                                                          42648
accom_h ns_sec adults car_availability children adult_nssec
1       1      1      1                1        1            1.009488
                                       2        1            0.126068
                      2                1        1            4.549804
                                       2        1            0.553863
                      3                1        1            0.741387
...                                                               ...
5       5      3      1                2        15           0.000029
                      2                1        15           0.000315
                                       2        15           0.000028
                      3                1        15           0.000160
                                       2        15           0.000010

[450 rows x 6976 columns]

In [34]:
dvec_out.data.columns.name #zoning_system.name

'DZ2011'

In [50]:
pop = cb.DVector.load(r"F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs\Output P11_EM.hdf")

FileNotFoundError: File F:\Deliverables\Land-Use\241220_Populationv2\02_Final Outputs\Output P11.1_EM.hdf does not exist

In [ ]:
pop.data# ["age_9", "g", "ns_sec", "soc", "pop_emp", "adults", "adult_nssec", "car_availability"]

LSOA2021                                                                                                       E01013453  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1           2.838697e-03
                                                                                            2   1           1.050612e-03
                                                                                    2       1   1           2.715717e-04
                                                                                            2   1           5.197295e-04
                                                                    2               3       4   2           3.555390e-04
...                                                                                                                  ...
5       5      3      3                2        15          8     2 4               3       4   2           0.000000e+00
                                                                    5               4       4   3           6.100810e-20
                                                                    6               3       4   3           3.248365e-19
                                                            9     1 6               5       4   3           5.810526e-07
                                                                  2 6               5       4   3           2.548992e-18

LSOA2021                                                                                                       E01013454  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1           5.368624e-04
                                                                                            2   1           1.952006e-04
                                                                                    2       1   1           5.136040e-05
                                                                                            2   1           9.656420e-05
                                                                    2               3       4   2           8.703444e-05
...                                                                                                                  ...
5       5      3      3                2        15          8     2 4               3       4   2           0.000000e+00
                                                                    5               4       4   3           1.073343e-19
                                                                    6               3       4   3           3.830660e-19
                                                            9     1 6               5       4   3           2.306729e-07
                                                                  2 6               5       4   3           8.791101e-19

LSOA2021                                                                                                    E01013455  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1            0.007940
                                                                                            2   1            0.002093
                                                                                    2       1   1            0.000900
                                                                                            2   1            0.000847
                                                                    2               3       4   2            0.001337
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2            0.000000
                                                                    5               4       4   3            0.000000
                                                                    6               3       4   3            0.000000
                                                            9     1 6               5       4   3            0.000000
                                                                  2 6               5       4   3            0.000000

LSOA2021                                                                                                       E01013456  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1           1.985586e-03
                                                                                            2   1           7.149697e-04
                                                                                    2       1   1           1.899565e-04
                                                                                            2   1           3.536898e-04
                                                                    2               3       4   2           4.541461e-04
...                                                                                                                  ...
5       5      3      3                2        15          8     2 4               3       4   2           0.000000e+00
                                                                    5               4       4   3           2.913291e-20
                                                                    6               3       4   3           2.201725e-19
                                                            9     1 6               5       4   3           4.454527e-07
                                                                  2 6               5       4   3           9.632895e-19

LSOA2021                                                                                                    E01013457  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1            0.003986
                                                                                            2   1            0.001416
                                                                                    2       1   1            0.000381
                                                                                            2   1            0.000700
                                                                    2               3       4   2            0.000788
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2            0.000000
                                                                    5               4       4   3            0.000000
                                                                    6               3       4   3            0.000000
                                                            9     1 6               5       4   3            0.000000
                                                                  2 6               5       4   3            0.000000

LSOA2021                                                                                                    E01013458  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1            0.007437
                                                                                            2   1            0.001350
                                                                                    2       1   1            0.000843
                                                                                            2   1            0.000546
                                                                    2               3       4   2            0.001610
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2            0.000000
                                                                    5               4       4   3            0.000000
                                                                    6               3       4   3            0.000000
                                                            9     1 6               5       4   3            0.000000
                                                                  2 6               5       4   3            0.000000

LSOA2021                                                                                                    E01013459  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1            0.000625
                                                                                            2   1            0.000257
                                                                                    2       1   1            0.000073
                                                                                            2   1            0.000127
                                                                    2               3       4   2            0.000122
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2            0.000000
                                                                    5               4       4   3            0.000000
                                                                    6               3       4   3            0.000000
                                                            9     1 6               5       4   3            0.000000
                                                                  2 6               5       4   3            0.000000

LSOA2021                                                                                                    E01013460  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1            0.000881
                                                                                            2   1            0.000319
                                                                                    2       1   1            0.000084
                                                                                            2   1            0.000158
                                                                    2               3       4   2            0.000146
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2            0.000000
                                                                    5               4       4   3            0.000000
                                                                    6               3       4   3            0.000000
                                                            9     1 6               5       4   3            0.000000
                                                                  2 6               5       4   3            0.000000

LSOA2021                                                                                                    E01013461  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1                 0.0
                                                                                            2   1                 0.0
                                                                                    2       1   1                 0.0
                                                                                            2   1                 0.0
                                                                    2               3       4   2                 0.0
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2                 0.0
                                                                    5               4       4   3                 0.0
                                                                    6               3       4   3                 0.0
                                                            9     1 6               5       4   3                 0.0
                                                                  2 6               5       4   3                 0.0

LSOA2021                                                                                                    E01013462  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1                 0.0
                                                                                            2   1                 0.0
                                                                                    2       1   1                 0.0
                                                                                            2   1                 0.0
                                                                    2               3       4   2                 0.0
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2                 0.0
                                                                    5               4       4   3                 0.0
                                                                    6               3       4   3                 0.0
                                                            9     1 6               5       4   3                 0.0
                                                                  2 6               5       4   3                 0.0

LSOA2021                                                                                                    ...  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps  ...
1       1      1      1                1        1           4     1 1               1       1   1           ...
                                                                                            2   1           ...
                                                                                    2       1   1           ...
                                                                                            2   1           ...
                                                                    2               3       4   2           ...
...                                                                                                         ...
5       5      3      3                2        15          8     2 4               3       4   2           ...
                                                                    5               4       4   3           ...
                                                                    6               3       4   3           ...
                                                            9     1 6               5       4   3           ...
                                                                  2 6               5       4   3           ...

LSOA2021                                                                                                    E01035501  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1            0.000060
                                                                                            2   1            0.000005
                                                                                    2       1   1            0.000010
                                                                                            2   1            0.000006
                                                                    2               3       4   2            0.000012
...                                                                                                               ...
5       5      3      3                2        15          8     2 4               3       4   2            0.000000
                                                                    5               4       4   3            0.000000
                                                                    6               3       4   3            0.000000
                                                            9     1 6               5       4   3            0.000000
                                                                  2 6               5       4   3            0.000000

LSOA2021                                                                                                       E01035502  \
accom_h ns_sec adults car_availability children adult_nssec age_9 g economic_status pop_emp soc status_aps
1       1      1      1                1        1           4     1 1               1       1   1           1.975949e-05
                                                                                            2   1           2.833624e-07
                                                                                    2       1   1           3.170227e-06
                                                                                            2   1           3.440712e-07
                                                                    2               3       4   2           1.694573e-06
...                                                                                                                  ...
5       5      3      3                2        15          8     2 4               3       4   2           0.000000e+00
                                                                    5               4       4   3           0.000000e+00
                                                                    6               3       4   3           0.000000e+00
                                                            9     1 6               5       4   3           0.000000e+00
                                                                  2 6               5       4   3           0.000000e+00


In [43]:
pop2 = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\(normitsefs) Transfer\TP_20250128-copy\tem_inputs\pop_2023.dvec")

In [44]:
pop2.data

normits_id                                    1001001    1001002    1001003   \
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1        16.115144  31.540102  22.133277
                                    2        86.320916  74.810286  32.392453
            2        1      1   2   1        11.335776  15.757461  28.795600
                                    2        77.356720  31.486947  36.983509
                                3   1         0.585331   0.965858   2.051799
...                                                ...        ...        ...
15          3        5      4   5   7         0.380569   0.645701   0.973415
                                    8         0.870336   0.374375   0.564758
                                6   6         0.040457   0.092239   0.331611
                                    7         0.082182   0.136864   0.217869
                                    8         0.026793   0.030377   0.097917

normits_id                                    1001004    1001005    1001006   \
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1        24.821626  16.992135  16.639163
                                    2        31.612050  36.759427  48.291901
            2        1      1   2   1        14.257934  10.332018  10.928583
                                    2        26.215958  21.147155  37.843552
                                3   1         1.192211   0.688715   0.658768
...                                                ...        ...        ...
15          3        5      4   5   7         0.440460   0.717727   0.252389
                                    8         0.226401   0.682636   0.241583
                                6   6         0.044752   0.162290   0.036389
                                    7         0.063926   0.231709   0.050941
                                    8         0.009583   0.058931   0.013610

normits_id                                    1001007    1001008    1001009   \
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1         3.019096  39.721790   5.724114
                                    2        49.892957  66.707620  80.196906
            2        1      1   2   1         6.808599  14.593062   9.990965
                                    2        48.837428  21.313007  97.773847
                                3   1         0.323894   1.051717   0.628627
...                                                ...        ...        ...
15          3        5      4   5   7         0.365565   0.508841   0.500212
                                    8         0.326896   0.386285   0.553120
                                6   6         0.010088   0.051553   0.112567
                                    7         0.036649   0.112783   0.187858
                                    8         0.033177   0.047282   0.093922

normits_id                                     1001010   ...    11357010  \
adult_nssec gender_3 ns_sec soc aws hh_type              ...
1           1        1      4   1   1         19.689141  ...   48.843471
                                    2         46.057644  ...  140.840229
            2        1      1   2   1         45.316498  ...   82.279917
                                    2        121.583901  ...  199.288721
                                3   1          2.566871  ...    4.483315
...                                                 ...  ...         ...
15          3        5      4   5   7          1.461792  ...    3.265986
                                    8          1.528764  ...    3.605127
                                6   6          0.185525  ...    1.028429
                                    7          0.239641  ...    0.664825
                                    8          0.137949  ...    0.386322

normits_id                                    11358001    11358002  \
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1         5.434040  185.663621
                                    2        32.216135  535.354993
            2        1      1   2   1         5.474601  415.849107
                                    2        29.254939  925.089987
                                3   1         0.391574   22.233763
...                                                ...         ...
15          3        5      4   5   7         0.088188   23.164652
                                    8         0.215617   24.958779
                                6   6         0.027557    2.796530
                                    7         0.030468    1.807809
                                    8         0.026178    1.050498

normits_id                                     11358003    11358004  \
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1        201.322911   87.330975
                                    2        580.529884  251.806556
            2        1      1   2   1        353.776560  164.136922
                                    2        829.702507  376.406100
                                3   1         19.142503    8.836968
...                                                 ...         ...
15          3        5      4   5   7         15.818458    7.450143
                                    8         17.420467    8.174153
                                6   6          2.913990    1.106409
                                    7          1.883741    0.715235
                                    8          1.094621    0.415615

normits_id                                     11358005    11358006  \
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1        117.326228   98.060574
                                    2        338.301613  282.741634
            2        1      1   2   1        259.990154  413.549596
                                    2        575.577866  812.047832
                                3   1         13.886863   21.513276
...                                                 ...         ...
15          3        5      4   5   7         13.994602   27.573295
                                    8         15.075509   29.024181
                                6   6          1.721770    1.213755
                                    7          1.113033    0.784629
                                    8          0.646771    0.455939

normits_id                                     11358007    11358008  \
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1        174.156444  118.069810
                                    2        502.172718  340.437918
            2        1      1   2   1        381.578668  196.892151
                                    2        857.022744  454.533210
                                3   1         20.471116   10.618771
...                                                 ...         ...
15          3        5      4   5   7         17.481062    9.148014
                                    8         19.118586   10.009559
                                6   6          2.456222    1.362864
                                    7          1.587818    0.881020
                                    8          0.922663    0.511951

normits_id                                     11358009
adult_nssec gender_3 ns_sec soc aws hh_type
1           1        1      4   1   1        153.732266
                                    2        443.252174
            2        1      1   2   1        311.376952
                                    2        702.241907
                                3   1         16.710793
...                                                 ...
15          3        5      4   5   7         14.204993
                                    8         15.487321
                                6   6          2.127334
                                    7          1.375209
                                    8          0.799119

[712 rows x 5430 columns]

In [77]:
trip_rate = cb.DVector.load(HBAttr.trip_rates_paths[1])
trip_rate_ = trip_rate.translate_zoning(
            cb.ZoningSystem.get_zoning(HBAttr.export_paths._zoning_system),
            check_totals=False,
            no_factors=True,
        )

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\zoning.py:681: TranslationWarning: 20 tfn_at zones have splitting factors which don't sum to 1 (value totals may change during zone_translation), the maximum difference is 7.7e+02
  warnings.warn(

In [78]:
trip_rate.data

tfn_at_id,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
soc,,,,,,,,,,,,,,,,,,,,
1,3.019889,3.16053,3.004098,2.956092,3.037491,3.019408,2.975141,2.855524,2.979358,2.918414,2.927104,2.903693,3.026621,2.994132,3.057548,3.299394,2.905692,2.622396,3.238929,3.177777
2,3.594541,3.530581,3.636769,3.570859,3.500373,3.725084,3.457529,3.463843,3.27895,3.381844,3.416496,3.459558,3.461247,3.591673,3.485421,3.780472,3.692169,3.821466,3.392436,3.687125
3,4.106846,4.166243,4.071976,4.108835,4.157966,4.314613,4.327899,4.335413,4.242488,4.124257,4.115332,4.054986,4.206412,4.242028,4.133448,4.226974,4.32206,3.160958,3.859612,4.304755
4,2.904472,5.497156,7.865269,6.354678,6.590449,6.834944,5.427596,5.991144,5.903358,5.070115,6.196961,7.806034,6.563651,5.078837,5.867247,6.138731,5.981463,6.493856,2.343703,5.295873

In [79]:
trip_rate_.data

normits_id,1001001,1001002,1001003,1001004,1001005,1001006,1001007,1001008,1001009,1001010,...,11357010,11358001,11358002,11358003,11358004,11358005,11358006,11358007,11358008,11358009
soc,,,,,,,,,,,,,,,,,,,,,
1,3.057548,3.057548,3.057548,3.057548,3.057548,3.057548,3.057548,3.057548,3.057548,3.057548,...,3.177777,2.905692,3.177777,3.177777,3.177777,3.177777,3.177777,3.177777,3.177777,3.177777
2,3.485421,3.485421,3.485421,3.485421,3.485421,3.485421,3.485421,3.485421,3.485421,3.485421,...,3.687125,3.692169,3.687125,3.687125,3.687125,3.687125,3.687125,3.687125,3.687125,3.687125
3,4.133448,4.133448,4.133448,4.133448,4.133448,4.133448,4.133448,4.133448,4.133448,4.133448,...,4.304755,4.322060,4.304755,4.304755,4.304755,4.304755,4.304755,4.304755,4.304755,4.304755
4,5.867247,5.867247,5.867247,5.867247,5.867247,5.867247,5.867247,5.867247,5.867247,5.867247,...,5.295873,5.981463,5.295873,5.295873,5.295873,5.295873,5.295873,5.295873,5.295873,5.295873

In [29]:
prod = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM\Export\TP_v3\Core\hb_productions\hb_normits_tem_segmented_2023_dvec.h5")

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level p is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [31]:
prod.data

normits_id                                      7294002     7300001  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.313249    9.580920
                 2       1        1            0.151105    9.728457
                 3       1        2            1.080462   30.511476
                 4       1        2            7.076441  359.556767
                 5       1        2            0.494937   23.445386
...                                                 ...         ...
8 6   4   5      6       3        15           0.095401    8.037112
                 7       2        15           0.026242    4.401600
                         3        15           0.019513    2.809774
                 8       2        15           0.016972    1.887854
                         3        15           0.011470    1.134887

normits_id                                        7305004     7306005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             13.615169    7.657227
                 2       1        1             10.901597    9.865916
                 3       1        2             37.044660   21.851379
                 4       1        2            374.712877  393.115294
                 5       1        2              9.619440   21.633907
...                                                   ...         ...
8 6   4   5      6       3        15             1.694288    6.085480
                 7       2        15             1.728158    4.351812
                         3        15             1.238918    3.006858
                 8       2        15             0.587040    2.033811
                         3        15             0.480968    1.023472

normits_id                                        7307006     7312002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              9.339888   11.862930
                 2       1        1             13.635719    9.680031
                 3       1        2             24.428142   27.475625
                 4       1        2            489.146671  299.604341
                 5       1        2             29.701615   10.512776
...                                                   ...         ...
8 6   4   5      6       3        15             1.774001    5.430465
                 7       2        15             2.558564    3.564083
                         3        15             1.696127    2.161217
                 8       2        15             1.195858    1.421234
                         3        15             0.863464    0.860006

normits_id                                        7313003     7315005  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              5.669655   12.405102
                 2       1        1              8.060367   17.505798
                 3       1        2             18.627661   25.705002
                 4       1        2            243.573021  486.842302
                 5       1        2             24.269095   24.810451
...                                                   ...         ...
8 6   4   5      6       3        15             4.370449    2.593577
                 7       2        15             3.885543    2.198381
                         3        15             2.369484    1.696777
                 8       2        15             2.761352    0.999852
                         3        15             1.310707    0.659768

normits_id                                        7316006     7318008  ...  \
p aws soc ns_sec hh_type gender_3 adult_nssec                          ...
1 1   4   1      1       1        1             12.702372    8.911514  ...
                 2       1        1             23.320755   11.251901  ...
                 3       1        2             26.471989   27.984913  ...
                 4       1        2            646.968469  361.196607  ...
                 5       1        2             36.628288   17.867437  ...
...                                                   ...         ...  ...
8 6   4   5      6       3        15             2.972614    4.114171  ...
                 7       2        15             3.965451    6.404432  ...
                         3        15             2.716394    4.995465  ...
                 8       2        15             2.125822    2.998513  ...
                         3        15             1.357996    2.380013  ...

normits_id                                       6255001    6255002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.054578   0.236815
                 2       1        1             1.309479   3.046713
                 3       1        2             0.147817   0.337238
                 4       1        2            23.412928  40.197876
                 5       1        2            26.715225  30.700061
...                                                  ...        ...
8 6   4   5      6       3        15            0.038061   0.038168
                 7       2        15            0.034807   0.040111
                         3        15            0.032652   0.021814
                 8       2        15            0.062286   0.102891
                         3        15            0.049232   0.056713

normits_id                                       6255005     6255006  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.238060    2.252650
                 2       1        1             1.599194   10.089501
                 3       1        2             0.196724    2.989700
                 4       1        2            22.259417  165.238644
                 5       1        2            11.622010   62.463525
...                                                  ...         ...
8 6   4   5      6       3        15            0.189353    2.210982
                 7       2        15            0.289403    1.681657
                         3        15            0.153220    1.300795
                 8       2        15            0.302689    1.359804
                         3        15            0.159754    1.141283

normits_id                                        6255007    6256002  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              3.673018   0.263692
                 2       1        1             21.038480   4.806764
                 3       1        2              3.145661   0.122506
                 4       1        2            341.060562  80.680369
                 5       1        2            137.787136  52.272639
...                                                   ...        ...
8 6   4   5      6       3        15             0.280794   0.010708
                 7       2        15             0.536038   0.017950
                         3        15             0.379264   0.027166
                 8       2        15             0.611441   0.028445
                         3        15             0.408374   0.022127

normits_id                                       6256006     6256009  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1             0.254156    3.032856
                 2       1        1             3.173634   24.247488
                 3       1        2             0.252875    3.198995
                 4       1        2            51.729753  380.454820
                 5       1        2            30.613523  158.623127
...                                                  ...         ...
8 6   4   5      6       3        15            0.001879    0.044729
                 7       2        15            0.012211    0.104724
                         3        15            0.012766    0.079433
                 8       2        15            0.017760    0.121347
                         3        15            0.018002    0.078842

normits_id                                        6256010     6257001
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1              1.275689    6.532106
                 2       1        1             14.725667   30.193443
                 3       1        2              1.765148    7.907665
                 4       1        2            291.720822  402.116212
                 5       1        2            105.806366  194.403722
...                                                   ...         ...
8 6   4   5      6       3        15             0.029889    0.221753
                 7       2        15             0.030839    0.719602
                         3        15             0.027393    0.445577
                 8       2        15             0.033454    0.519208
                         3        15             0.028675    0.327299

[5696 rows x 5430 columns]