1. Zone Translation

In [ ]:
csv_zone = "C:/Users/Spiral/Documents/Thomas Prince/NoTEMinputs/normits_v3.3_lsoa21_trans.csv"

In [ ]:
def settlement(self, col_type: str = 'hhold') -> Dict:
        # ruc 2011 to area type
        set_01id = self.dct_to_specs(self.set_01id)
        out_dict = {
            "col": f"{col_type}ruc2011_b01id",
            "typ": str,
            "log": f"{col_type}ruc_2011",
            "val": {
                1: set_01id["major"],
                2: set_01id["minor"],
                3: set_01id["city"],
                4: set_01id["town"],
                5: set_01id["village"],
            },
            "out": {
                1: "Major",
                2: "Minor",
                3: "City",
                4: "Town",
                5: "Village",
            },
        }
        out_dict["val"] = fun.itm_to_key(out_dict["val"])
        return out_dict

In [ ]:
def _zone_system(self, get_uniq: bool = False):
        col_sett, ruc_aggr = 'ruc11cd', self.luk.settlement()
        self.sys_zone = fun.csv_to_dfr(self.csv_zone)
        col_type = [self.col_zone] + list({self.col_report, 'gor', 'tfn_at'})
        self.sys_zone = self._as_type(self.sys_zone, col_type)
        self.sys_zone[self.col_lsoa] = self.sys_zone[self.col_lsoa].str.upper()
        self.sys_zone[col_sett] = self.sys_zone[col_sett].str.lower()

In [1]:
import caf.base as cb

In [ ]:
(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NoTEM Input\NTS Output\productions\nhb\mode_time_splits")

In [31]:
hb_prod = cb.DVector.load(r"C:\Users\Spiral\Documents\Thomas Prince\NTS Processing DVec\outputs_is\productions\hb\trip_rates\hb_trip_rates_production_dvector.dvec")

In [38]:
lu_emp.data

                                          E01000001    E01000002  E01000003  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           452.133349  1374.705643   23.36568
 1          1    1           1             0.000000     0.000000    0.00000
                             2             0.000000     0.000000    0.00000
                             3             0.000000     0.000000    0.00000
                             4             0.000000     0.000000    0.00000
...                                             ...          ...        ...
 20         3    98          614           0.000000     0.000000    0.00000
                             615           0.000000     0.000000    0.00000
 21         1    99          616           0.000000     0.000000    0.00000
            2    99          616           0.000000     0.000000    0.00000
            3    99          616           0.000000     0.000000    0.00000

                                            E01000005     E01000006  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           6.847462e+02  4.325380e+00
 1          1    1           1           3.751173e-14  8.852917e-03
                             2           3.751173e-14  4.359828e-13
                             3           3.751173e-14  4.359828e-13
                             4           3.751173e-14  4.359828e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            E01000007     E01000008  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           4.578384e+01  4.787163e+01
 1          1    1           1           1.208852e-02  1.158169e-02
                             2           4.359826e-13  4.316112e-13
                             3           4.359826e-13  4.316112e-13
                             4           4.359826e-13  4.316112e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            E01000009     E01000011  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           2.893181e+01  3.728634e+00
 1          1    1           1           7.730599e-03  5.535892e-03
                             2           4.359829e-13  4.359828e-13
                             3           4.359829e-13  4.359828e-13
                             4           4.359829e-13  4.359828e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            E01000012  ...     W01002031  \
sic_1_digit soc sic_2_digit sic_4_digit                ...
-1          4   -1          -1           7.158826e+00  ...  4.954895e+00
 1          1    1           1           8.399335e-03  ...  4.590315e-02
                             2           4.316380e-13  ...  1.199581e-13
                             3           4.316380e-13  ...  1.199581e-13
                             4           4.316380e-13  ...  1.199581e-13
...                                               ...  ...           ...
 20         3    98          614         0.000000e+00  ...  0.000000e+00
                             615         0.000000e+00  ...  0.000000e+00
 21         1    99          616         0.000000e+00  ...  0.000000e+00
            2    99          616         0.000000e+00  ...  0.000000e+00
            3    99          616         0.000000e+00  ...  0.000000e+00

                                            W01002032     W01002033  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           3.288834e+01  2.075594e+02
 1          1    1           1           3.352047e-01  2.115488e+00
                             2           1.206457e-13  1.205458e-13
                             3           1.206457e-13  1.205458e-13
                             4           1.206457e-13  1.205458e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002034     W01002035  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           7.354577e+00  2.933634e+00
 1          1    1           1           1.480102e-01  5.903912e-02
                             2           1.206457e-13  1.206457e-13
                             3           1.206457e-13  1.206457e-13
                             4           1.206457e-13  1.206457e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002036     W01002037  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           2.207929e+01  1.615205e+01
 1          1    1           1           7.189201e-02  5.259242e-02
                             2           1.225430e-13  1.225430e-13
                             3           1.225430e-13  1.225430e-13
                             4           1.225430e-13  1.225430e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002038     W01002039  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           3.237869e+01  6.008077e+00
 1          1    1           1           6.464614e-01  1.199551e-01
                             2           1.225430e-13  1.221727e-13
                             3           1.225430e-13  1.221727e-13
                             4           1.225430e-13  1.221727e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002040
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           1.526167e+01
 1          1    1           1           1.259940e-01
                             2           1.225477e-13
                             3           1.225477e-13
                             4           1.225477e-13
...                                               ...
 20         3    98          614         0.000000e+00
                             615         0.000000e+00
 21         1    99          616         0.000000e+00
            2    99          616         0.000000e+00
            3    99          616         0.000000e+00

[1849 rows x 42648 columns]

In [36]:
hb_prod.data

                                                      1         2         3  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.007905  0.014785  0.040716
                 2       1        1            0.013089  0.021696  0.065175
                 3       1        2            0.007254  0.012891  0.032245
                 4       1        2            0.055611  0.105189  0.282388
                 5       1        2            0.017164  0.029233  0.081469
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.168882  0.135028  0.141341
                 7       2        15           0.506160  0.440260  0.471015
                         3        15           0.335909  0.285860  0.308587
                 8       2        15           0.630635  0.828064  0.571972
                         3        15           0.432040  0.539231  0.362945

                                                      4         5         6  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.021608  0.028700  0.036847
                 2       1        1            0.035957  0.046342  0.062144
                 3       1        2            0.023958  0.025984  0.035110
                 4       1        2            0.169451  0.205875  0.273344
                 5       1        2            0.046586  0.056295  0.071256
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.115564  0.107696  0.145048
                 7       2        15           0.394626  0.426106  0.490627
                         3        15           0.258106  0.219246  0.296748
                 8       2        15           0.489652  0.499022  0.587258
                         3        15           0.314154  0.333153  0.383186

                                                      7         8         9  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.020657  0.020283  0.034148
                 2       1        1            0.040156  0.039379  0.047195
                 3       1        2            0.024985  0.022839  0.028854
                 4       1        2            0.191913  0.172094  0.215683
                 5       1        2            0.048853  0.045471  0.060919
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.192470  0.139262  0.145298
                 7       2        15           0.619737  0.471813  0.486686
                         3        15           0.418859  0.307637  0.319909
                 8       2        15           0.737675  0.558485  0.593760
                         3        15           0.497354  0.365914  0.381189

                                                     10        11        12  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.036338  0.029644  0.029764
                 2       1        1            0.056855  0.056177  0.053397
                 3       1        2            0.034872  0.030451  0.035693
                 4       1        2            0.252671  0.244490  0.233538
                 5       1        2            0.072426  0.065917  0.064347
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.166717  0.187901  0.138746
                 7       2        15           0.562528  0.576935  0.454883
                         3        15           0.363129  0.390114  0.297195
                 8       2        15           0.673347  0.698433  0.540324
                         3        15           0.431382  0.482425  0.318520

                                                     13        14        15  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.049293  0.032254  0.030055
                 2       1        1            0.070968  0.060264  0.060580
                 3       1        2            0.038334  0.033750  0.033101
                 4       1        2            0.325651  0.258862  0.276551
                 5       1        2            0.086187  0.073228  0.073460
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.157592  0.182304  0.176421
                 7       2        15           0.520116  0.530565  0.584408
                         3        15           0.342113  0.349512  0.382232
                 8       2        15           0.560358  0.714369  0.693121
                         3        15           0.406929  0.472960  0.453009

                                                     16        17        18  \
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.031605  0.022620  0.022265
                 2       1        1            0.052636  0.037829  0.036420
                 3       1        2            0.021661  0.024822  0.026800
                 4       1        2            0.235306  0.179406  0.173384
                 5       1        2            0.065068  0.050138  0.045107
...                                                 ...       ...       ...
8 6   4   5      6       3        15           0.219683  0.153960  0.126949
                 7       2        15           0.695135  0.499272  0.411482
                         3        15           0.462217  0.334332  0.271362
                 8       2        15           0.846628  0.599091  0.427562
                         3        15           0.580419  0.390083  0.312567

                                                     19        20
p aws soc ns_sec hh_type gender_3 adult_nssec
1 1   4   1      1       1        1            0.032650  0.047289
                 2       1        1            0.052326  0.077026
                 3       1        2            0.027005  0.041723
                 4       1        2            0.238100  0.309877
                 5       1        2            0.062817  0.083678
...                                                 ...       ...
8 6   4   5      6       3        15           0.152679  0.136877
                 7       2        15           0.531050  0.454089
                         3        15           0.347176  0.278561
                 8       2        15           0.626486  0.540531
                         3        15           0.389860  0.355910

[5696 rows x 20 columns]

In [20]:
hb_attr1 = cb.DVector.load(r"T:\ThomasPrince\hb_attraction_triprates_p1.dvec")
hb_attr2 = cb.DVector.load(r"T:\ThomasPrince\hb_attraction_triprates_p2.dvec")
hb_attr3 = cb.DVector.load(r"T:\ThomasPrince\hb_attraction_triprates_p3.dvec")
hb_attr4 = cb.DVector.load(r"T:\ThomasPrince\hb_attraction_triprates_p4.dvec")
hb_attr5 = cb.DVector.load(r"T:\ThomasPrince\hb_attraction_triprates_p5.dvec")
hb_attr6 = cb.DVector.load(r"T:\ThomasPrince\hb_attraction_triprates_p6.dvec")

C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(
C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\caf.base\src\caf\base\segmentation.py:342: SegmentationWarning: Read in level sic_2_digit is a subset of the segment. If this was not expected check the input segmentation.
  warnings.warn(

In [21]:
hb_attr5.data

tfn_at,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
sic_2_digit,,,,,,,,,,,,,,,,,,,,
56,1.26393,4.47438,44.168443,6.389222,0.06591,6.002881,3.80116,26.097942,13.043821,4.192794,9.88771,0.0,22.306465,1.090728,6.34826,0.0,11.236667,19.163963,0.0,7.956971
64,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
65,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
66,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
68,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
69,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
75,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
77,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
79,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
80,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
86,1.605145,10.59077,0.0,8.855501,7.515055,8.884033,9.169221,5.827483,3.603441,9.241643,11.312255,11.260215,4.2404,14.668616,10.196696,36.728357,16.908804,0.782552,11.092221,11.815761
95,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0
96,3.967848,9.99687,0.0,6.101963,10.526631,4.894893,7.830746,0.0,8.918166,10.17289,0.0,8.889054,8.537158,0.0,6.571051,14.720117,11.957131,11.73585,19.148322,0.0

In [23]:
lu_emp = cb.DVector.load(r"F:\Deliverables\Land-Use\241213_Employment\02_Final Outputs\Output E6.hdf")

In [24]:
lu_emp.data

                                          E01000001    E01000002  E01000003  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           452.133349  1374.705643   23.36568
 1          1    1           1             0.000000     0.000000    0.00000
                             2             0.000000     0.000000    0.00000
                             3             0.000000     0.000000    0.00000
                             4             0.000000     0.000000    0.00000
...                                             ...          ...        ...
 20         3    98          614           0.000000     0.000000    0.00000
                             615           0.000000     0.000000    0.00000
 21         1    99          616           0.000000     0.000000    0.00000
            2    99          616           0.000000     0.000000    0.00000
            3    99          616           0.000000     0.000000    0.00000

                                            E01000005     E01000006  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           6.847462e+02  4.325380e+00
 1          1    1           1           3.751173e-14  8.852917e-03
                             2           3.751173e-14  4.359828e-13
                             3           3.751173e-14  4.359828e-13
                             4           3.751173e-14  4.359828e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            E01000007     E01000008  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           4.578384e+01  4.787163e+01
 1          1    1           1           1.208852e-02  1.158169e-02
                             2           4.359826e-13  4.316112e-13
                             3           4.359826e-13  4.316112e-13
                             4           4.359826e-13  4.316112e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            E01000009     E01000011  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           2.893181e+01  3.728634e+00
 1          1    1           1           7.730599e-03  5.535892e-03
                             2           4.359829e-13  4.359828e-13
                             3           4.359829e-13  4.359828e-13
                             4           4.359829e-13  4.359828e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            E01000012  ...     W01002031  \
sic_1_digit soc sic_2_digit sic_4_digit                ...
-1          4   -1          -1           7.158826e+00  ...  4.954895e+00
 1          1    1           1           8.399335e-03  ...  4.590315e-02
                             2           4.316380e-13  ...  1.199581e-13
                             3           4.316380e-13  ...  1.199581e-13
                             4           4.316380e-13  ...  1.199581e-13
...                                               ...  ...           ...
 20         3    98          614         0.000000e+00  ...  0.000000e+00
                             615         0.000000e+00  ...  0.000000e+00
 21         1    99          616         0.000000e+00  ...  0.000000e+00
            2    99          616         0.000000e+00  ...  0.000000e+00
            3    99          616         0.000000e+00  ...  0.000000e+00

                                            W01002032     W01002033  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           3.288834e+01  2.075594e+02
 1          1    1           1           3.352047e-01  2.115488e+00
                             2           1.206457e-13  1.205458e-13
                             3           1.206457e-13  1.205458e-13
                             4           1.206457e-13  1.205458e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002034     W01002035  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           7.354577e+00  2.933634e+00
 1          1    1           1           1.480102e-01  5.903912e-02
                             2           1.206457e-13  1.206457e-13
                             3           1.206457e-13  1.206457e-13
                             4           1.206457e-13  1.206457e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002036     W01002037  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           2.207929e+01  1.615205e+01
 1          1    1           1           7.189201e-02  5.259242e-02
                             2           1.225430e-13  1.225430e-13
                             3           1.225430e-13  1.225430e-13
                             4           1.225430e-13  1.225430e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002038     W01002039  \
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           3.237869e+01  6.008077e+00
 1          1    1           1           6.464614e-01  1.199551e-01
                             2           1.225430e-13  1.221727e-13
                             3           1.225430e-13  1.221727e-13
                             4           1.225430e-13  1.221727e-13
...                                               ...           ...
 20         3    98          614         0.000000e+00  0.000000e+00
                             615         0.000000e+00  0.000000e+00
 21         1    99          616         0.000000e+00  0.000000e+00
            2    99          616         0.000000e+00  0.000000e+00
            3    99          616         0.000000e+00  0.000000e+00

                                            W01002040
sic_1_digit soc sic_2_digit sic_4_digit
-1          4   -1          -1           1.526167e+01
 1          1    1           1           1.259940e-01
                             2           1.225477e-13
                             3           1.225477e-13
                             4           1.225477e-13
...                                               ...
 20         3    98          614         0.000000e+00
                             615         0.000000e+00
 21         1    99          616         0.000000e+00
            2    99          616         0.000000e+00
            3    99          616         0.000000e+00

[1849 rows x 42648 columns]

In [26]:
lu_emp.segmentation

'DZ2011+LSOA2021'

In [ ]:
ct.inputs.TEMSegmentations():
    prod_pure_report: cb.SegmentationInput
    prod_full_tfnat: cb.SegmentationInput
    prod_full: cb.SegmentationInput
    prod_return_seg: cb.SegmentationInput
    lad_report_seg = cb.SegmentationInput(
        enum_segments=["p", "m", "tp"],
        naming_order=["p", "m", "tp"],
        subsets={"tp": [1, 2, 3, 4, 5, 6]},
    )
    output: cb.SegmentationInput
    area_type: cb.SegmentationInput
    trip_rates: cb.SegmentationInput
    trip_weights: cb.SegmentationInput
    employment: cb.SegmentationInput
    attr_pure: cb.SegmentationInput

TranslationError: A zone_translation between DZ2011+LSOA2021 and tfn_at does not exist and cannot be generated. To perform this zone_translation you must generate a zone_translation using caf.space.

In [2]:
import caf.base as cb
import caf.toolkit as ctk

In [6]:
ctk.BaseConfig

In [7]:
import caf.tem as ct

In [12]:
#ct.inputs.TEMSegmentations
ctk.BaseConfig.from_yaml(r"C:\Users\Spiral\Documents\Thomas Prince\Common Analytical Framework\NTS-Processing_python-refactor\NoTEM\inputs\config.yml")

ValidationError: 1 validation error for BaseConfig
  Input should be a valid dictionary or instance of BaseConfig [type=model_type, input_value='C:\\Users\\Spiral\\Docum...TEM\\inputs\\config.yml', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type